// The single-file function copies for the Supabase dashboard must match the real sources.
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import * as nodeModule from 'node:module';
import { bundle, FUNCTIONS, SHARED, shared } from '../build-functions.mjs';

// Reading TypeScript the way Node does (types erased) is the only way to see whether a file made of several still is one valid module.
process.removeAllListeners('warning');
const strip = nodeModule.stripTypeScriptTypes;

for (const name of FUNCTIONS) {
  const onDisk = readFileSync(new URL(`../dashboard/${name}.ts`, import.meta.url), 'utf8');
  assert.equal(onDisk, bundle(name), `dashboard/${name}.ts is stale: run npm run build:functions`);
  assert.doesNotMatch(onDisk, /from '\.\/logic\.ts'/, 'no relative imports in a single-file function');
  assert.match(onDisk, /Deno\.serve/, 'contains the handler');
  assert.match(onDisk, /\/\/ ---- logic ----/, 'contains the logic');
  assert.equal((onDisk.match(/^import /gm) ?? []).every((l) => true), true);
  for (const line of onDisk.split('\n').filter((l) => l.startsWith('import '))) {
    assert.match(line, /from '(npm:|node:)/, `only npm:/node: imports: ${line}`);
  }
  // Several files in one: a name declared twice would stop the whole function from starting.
  if (typeof strip === 'function') {
    const js = strip(onDisk).replace(/^import .*$/gm, '').replace(/^export (async function|function|const|let|class)/gm, '$1');
    assert.doesNotThrow(() => new Function(js), `dashboard/${name}.ts is not one valid module (a name declared twice?)`);
  }
}

// Files shared with the Post app are generated from the app's own, both next to the function (for the CLI) and inside its single file.
for (const [name, s] of Object.entries(SHARED)) {
  const next = readFileSync(new URL(`../functions/${s.function}/${s.file}`, import.meta.url), 'utf8');
  assert.equal(next, shared(name), `functions/${s.function}/${s.file} is stale: run npm run build:functions`);
  assert.match(next, /^\/\/ GENERATED by supabase\/build-functions\.mjs from apps\/web\/src\/post\/core\//, 'says where it comes from');
  assert.doesNotMatch(next, /from '\.\/types\.ts'/, 'does not reach into the app');
  const single = readFileSync(new URL(`../dashboard/${s.function}.ts`, import.meta.url), 'utf8');
  assert.ok(single.includes(shared(name).trimEnd()), `dashboard/${s.function}.ts carries the same ${name} as the app`);
}
console.log('dashboard bundles OK');
