// Concatenates migrations into setup.sql: one file to paste into the Supabase SQL editor.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

export function buildSetup() {
  const dir = new URL('./migrations/', import.meta.url);
  const parts = readdirSync(dir).filter((f) => f.endsWith('.sql')).sort()
    .map((f) => `-- ===== ${f} =====\n${readFileSync(new URL(f, dir), 'utf8').trim()}\n`);
  return `-- Generated by build-setup.mjs. Paste into Supabase > SQL Editor > New query, then Run.\n-- Run it once on a fresh project.\n\n${parts.join('\n')}`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(new URL('./setup.sql', import.meta.url), buildSetup());
  console.log('wrote supabase/setup.sql');
}
