// Concatenates migrations into setup.sql: one file to paste into the Supabase SQL editor.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

// Migrations up to and including this number are what earlier setup.sql pastes already contained.
export const UPGRADE_AFTER = 5;

export function buildSetup(after = 0) {
  const dir = new URL('./migrations/', import.meta.url);
  const parts = readdirSync(dir).filter((f) => f.endsWith('.sql') && Number(f.slice(0, 4)) > after).sort()
    .map((f) => `-- ===== ${f} =====\n${readFileSync(new URL(f, dir), 'utf8').trim()}\n`);
  const note = after
    ? `-- Upgrade for projects that already ran setup.sql up to migration ${String(after).padStart(4, '0')}. Run once.`
    : '-- Run it once on a fresh project.';
  return `-- Generated by build-setup.mjs. Paste into Supabase > SQL Editor > New query, then Run.\n${note}\n\n${parts.join('\n')}`;
}

/** Only what Post needs (its tables and setup helpers: the migrations named post_), for a project where Home Memory is already set up. */
export function buildPost() {
  const dir = new URL('./migrations/', import.meta.url);
  const parts = readdirSync(dir).filter((f) => f.endsWith('.sql') && f.includes('_post_')).sort()
    .map((f) => `-- ===== ${f} =====\n${readFileSync(new URL(f, dir), 'utf8').trim()}\n`);
  return `-- Generated by build-setup.mjs. The Post mail app's tables and setup helpers only. Paste into Supabase > SQL Editor > New query, then Run. Safe to run again.\n\n${parts.join('\n')}`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(new URL('./setup.sql', import.meta.url), buildSetup());
  writeFileSync(new URL('./upgrade.sql', import.meta.url), buildSetup(UPGRADE_AFTER));
  writeFileSync(new URL('./post.sql', import.meta.url), buildPost());
  console.log('wrote supabase/setup.sql, supabase/upgrade.sql and supabase/post.sql');
}
