-- Generated by build-setup.mjs. Paste into Supabase > SQL Editor > New query, then Run.
-- Run it once on a fresh project.

-- ===== 0001_init.sql =====
-- Home Memory: Milestone 1 schema.
-- A household is the sharing unit (you + spouse). Everything else hangs off it.

create table public.households (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  invite_code text not null unique default substr(replace(gen_random_uuid()::text, '-', ''), 1, 8),
  created_at timestamptz not null default now()
);

create table public.household_members (
  household_id uuid not null references public.households (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  display_name text,
  role text not null default 'member' check (role in ('owner', 'member')),
  joined_at timestamptz not null default now(),
  primary key (household_id, user_id)
);
create index household_members_user_idx on public.household_members (user_id);

-- Membership check used by every policy. SECURITY DEFINER avoids recursive RLS on household_members.
create function public.is_member(hid uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.household_members m
    where m.household_id = hid and m.user_id = auth.uid()
  );
$$;

-- Saved places. 'fixed' = a point with a radius; 'category' = "any pharmacy" (resolved to nearby POIs later).
create table public.places (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  name text not null,
  kind text not null default 'fixed' check (kind in ('fixed', 'category')),
  category text,
  lat double precision,
  lon double precision,
  radius_m integer not null default 150 check (radius_m between 50 and 2000),
  created_at timestamptz not null default now(),
  check (
    (kind = 'fixed' and lat is not null and lon is not null)
    or (kind = 'category' and category is not null)
  )
);
create index places_household_idx on public.places (household_id);

-- A memory starts as raw capture in the inbox. Anchors (place) are optional and additive.
create table public.memories (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  author_id uuid not null default auth.uid() references auth.users (id),
  body text not null default '',
  status text not null default 'inbox' check (status in ('inbox', 'active', 'done', 'dismissed')),
  place_id uuid references public.places (id) on delete set null,
  place_category text,
  capture_lat double precision,
  capture_lon double precision,
  capture_accuracy_m real,
  -- "Not now" keeps the memory for the next visit: no push again until this passes.
  snoozed_until timestamptz,
  last_surfaced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  done_at timestamptz
);
create index memories_household_status_idx on public.memories (household_id, status, created_at desc);
create index memories_place_idx on public.memories (place_id) where place_id is not null;

create table public.media (
  id uuid primary key default gen_random_uuid(),
  memory_id uuid not null references public.memories (id) on delete cascade,
  household_id uuid not null references public.households (id) on delete cascade,
  kind text not null default 'photo' check (kind in ('photo', 'voice')),
  storage_path text not null,
  created_at timestamptz not null default now()
);
create index media_memory_idx on public.media (memory_id);

create table public.push_tokens (
  token text primary key,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  platform text not null check (platform in ('ios', 'web')),
  updated_at timestamptz not null default now()
);

create function public.touch_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
create trigger memories_touch before update on public.memories
  for each row execute function public.touch_updated_at();

-- Bootstrap and invite flow. Direct inserts into households/household_members are not allowed.
create function public.create_household(p_name text, p_display_name text default null)
returns uuid language plpgsql security definer set search_path = public as $$
declare hid uuid;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  insert into public.households (name) values (p_name) returning id into hid;
  insert into public.household_members (household_id, user_id, display_name, role)
    values (hid, auth.uid(), p_display_name, 'owner');
  return hid;
end;
$$;

create function public.join_household(p_invite_code text, p_display_name text default null)
returns uuid language plpgsql security definer set search_path = public as $$
declare hid uuid;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  select id into hid from public.households where invite_code = lower(trim(p_invite_code));
  if hid is null then raise exception 'invalid invite code'; end if;
  insert into public.household_members (household_id, user_id, display_name)
    values (hid, auth.uid(), p_display_name)
    on conflict do nothing;
  return hid;
end;
$$;

-- Row level security
alter table public.households enable row level security;
alter table public.household_members enable row level security;
alter table public.places enable row level security;
alter table public.memories enable row level security;
alter table public.media enable row level security;
alter table public.push_tokens enable row level security;

create policy households_select on public.households for select using (public.is_member(id));
create policy households_update on public.households for update using (public.is_member(id)) with check (public.is_member(id));

create policy members_select on public.household_members for select using (public.is_member(household_id));
create policy members_update_self on public.household_members for update
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy members_delete_self on public.household_members for delete using (user_id = auth.uid());

create policy places_all on public.places for all
  using (public.is_member(household_id)) with check (public.is_member(household_id));

create policy memories_select on public.memories for select using (public.is_member(household_id));
create policy memories_insert on public.memories for insert
  with check (public.is_member(household_id) and author_id = auth.uid());
create policy memories_update on public.memories for update
  using (public.is_member(household_id)) with check (public.is_member(household_id));
create policy memories_delete on public.memories for delete using (public.is_member(household_id));

create policy media_all on public.media for all
  using (public.is_member(household_id)) with check (public.is_member(household_id));

create policy push_tokens_own on public.push_tokens for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

grant usage on schema public to authenticated;
grant select, update on public.households to authenticated;
grant select, update, delete on public.household_members to authenticated;
grant select, insert, update, delete on public.places, public.memories, public.media, public.push_tokens to authenticated;
grant execute on function public.create_household(text, text), public.join_household(text, text) to authenticated;
grant execute on function public.is_member(uuid) to authenticated;

-- Private photo bucket. Objects live under <household_id>/<memory_id>/<file>.
insert into storage.buckets (id, name, public) values ('media', 'media', false)
on conflict (id) do nothing;

create policy media_objects_all on storage.objects for all
  using (bucket_id = 'media' and public.is_member(((storage.foldername(name))[1])::uuid))
  with check (bucket_id = 'media' and public.is_member(((storage.foldername(name))[1])::uuid));

-- ===== 0002_capture_keys.sql =====
-- Capture keys let something with no login (an iOS Shortcut, Siri, Action button, a script on Windows)
-- drop a memory into the household inbox. Only the sha256 hash of the key is stored.

create table public.capture_keys (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  label text not null default 'Shortcut',
  key_hash bytea not null unique,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);
create index capture_keys_user_idx on public.capture_keys (user_id);

alter table public.capture_keys enable row level security;
-- Members can list/revoke their own keys. Creation goes through create_capture_key (needs the plaintext once).
create policy capture_keys_select on public.capture_keys for select using (user_id = auth.uid());
create policy capture_keys_delete on public.capture_keys for delete using (user_id = auth.uid());
grant select, delete on public.capture_keys to authenticated;

-- Returns the plaintext key exactly once.
create function public.create_capture_key(p_household_id uuid, p_label text default 'Shortcut')
returns text language plpgsql security definer set search_path = public as $$
declare k text;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if not public.is_member(p_household_id) then raise exception 'not a member'; end if;
  k := 'hm_' || replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '');
  insert into public.capture_keys (household_id, user_id, label, key_hash)
    values (p_household_id, auth.uid(), coalesce(nullif(trim(p_label), ''), 'Shortcut'), sha256(convert_to(k, 'utf8')));
  return k;
end;
$$;

-- Callable without login (anon role). The key is the credential.
create function public.capture_memory(
  p_key text,
  p_body text,
  p_lat double precision default null,
  p_lon double precision default null
) returns void language plpgsql security definer set search_path = public as $$
declare ck public.capture_keys;
begin
  select * into ck from public.capture_keys where key_hash = sha256(convert_to(coalesce(p_key, ''), 'utf8'));
  if not found then raise exception 'invalid capture key' using errcode = '28000'; end if;
  if p_body is null or length(trim(p_body)) = 0 then raise exception 'empty memory'; end if;
  if length(p_body) > 5000 then raise exception 'memory too long'; end if;

  insert into public.memories (household_id, author_id, body, capture_lat, capture_lon)
    values (ck.household_id, ck.user_id, trim(p_body), p_lat, p_lon);
  update public.capture_keys set last_used_at = now() where id = ck.id;
end;
$$;

grant execute on function public.create_capture_key(uuid, text) to authenticated;
grant execute on function public.capture_memory(text, text, double precision, double precision) to anon, authenticated;

-- ===== 0003_maintenance.sql =====
-- Recurring house maintenance. Completing a task records history and schedules the next occurrence.
-- No "overdue" state on purpose: a task is either coming up or due, never red (docs/DESIGN.md principle 7).

create table public.maintenance_tasks (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  template_key text,
  title text not null,
  notes text,
  zone text not null default 'house' check (zone in ('house', 'garden', 'other')),
  -- interval: every N months after it was last done. seasonal: a yearly window (e.g. Sep-Oct).
  schedule text not null check (schedule in ('interval', 'seasonal')),
  interval_months integer check (interval_months between 1 and 240),
  window_start_month integer check (window_start_month between 1 and 12),
  window_end_month integer check (window_end_month between 1 and 12),
  next_due_at date not null,
  due_until date,
  last_done_at date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (household_id, template_key),
  check (
    (schedule = 'interval' and interval_months is not null)
    or (schedule = 'seasonal' and window_start_month is not null and window_end_month is not null)
  )
);
create index maintenance_tasks_due_idx on public.maintenance_tasks (household_id, next_due_at) where active;

create table public.maintenance_events (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.maintenance_tasks (id) on delete cascade,
  household_id uuid not null references public.households (id) on delete cascade,
  done_at date not null default current_date,
  done_by uuid default auth.uid() references auth.users (id),
  cost_nok numeric(12, 2),
  note text,
  created_at timestamptz not null default now()
);
create index maintenance_events_task_idx on public.maintenance_events (task_id, done_at desc);

-- Start and end date of the window whose start is `start_year`-`start_month`-01.
create function public.season_window(p_start_month int, p_end_month int, p_start_year int)
returns table (window_start date, window_end date)
language sql immutable as $$
  select make_date(p_start_year, p_start_month, 1),
         (make_date(p_start_year + case when p_end_month < p_start_month then 1 else 0 end, p_end_month, 1)
           + interval '1 month - 1 day')::date;
$$;

-- Next occurrence after a completion. Seasonal: done within 3 months before the window (or during/after it)
-- counts for that window, so the next one is next year's; earlier than that it is this year's window.
create function public.next_maintenance_due(
  p_schedule text, p_interval_months int, p_ws int, p_we int, p_from date
) returns table (next_due date, due_until date)
language plpgsql immutable as $$
declare cand date;
begin
  if p_schedule = 'interval' then
    return query select (p_from + make_interval(months => p_interval_months))::date, null::date;
    return;
  end if;
  cand := make_date(extract(year from p_from)::int, p_ws, 1);
  if p_from >= (cand - interval '3 months')::date then cand := (cand + interval '1 year')::date; end if;
  return query select w.window_start, w.window_end
    from public.season_window(p_ws, p_we, extract(year from cand)::int) w;
end;
$$;

-- First occurrence for a freshly seeded seasonal task: the current window if we are inside it, else the next one.
create function public.first_seasonal_due(p_ws int, p_we int, p_today date)
returns table (next_due date, due_until date)
language sql immutable as $$
  with this_year as (select * from public.season_window(p_ws, p_we, extract(year from p_today)::int)),
       prev_year as (select * from public.season_window(p_ws, p_we, extract(year from p_today)::int - 1)),
       next_year as (select * from public.season_window(p_ws, p_we, extract(year from p_today)::int + 1))
  select window_start, window_end from prev_year where p_today <= window_end
  union all
  select window_start, window_end from this_year where p_today <= window_end
    and not exists (select 1 from prev_year where p_today <= window_end)
  union all
  select window_start, window_end from next_year
    where not exists (select 1 from prev_year where p_today <= window_end)
      and not exists (select 1 from this_year where p_today <= window_end)
  limit 1;
$$;

create function public.complete_maintenance(
  p_task_id uuid, p_done_at date default current_date, p_cost numeric default null, p_note text default null
) returns void language plpgsql security definer set search_path = public as $$
declare t public.maintenance_tasks; n record;
begin
  select * into t from public.maintenance_tasks where id = p_task_id;
  if not found or not public.is_member(t.household_id) then raise exception 'not found'; end if;
  insert into public.maintenance_events (task_id, household_id, done_at, cost_nok, note)
    values (t.id, t.household_id, p_done_at, p_cost, nullif(trim(p_note), ''));
  select * into n from public.next_maintenance_due(t.schedule, t.interval_months, t.window_start_month, t.window_end_month, p_done_at);
  update public.maintenance_tasks
    set last_done_at = greatest(coalesce(last_done_at, p_done_at), p_done_at), next_due_at = n.next_due, due_until = n.due_until
    where id = t.id;
end;
$$;

-- Norway-oriented starter template. Timings are a starting point to edit, not professional advice: check local
-- rules (kommune, feiervesen) and product manuals. p_profile flags switch on optional groups.
create function public.seed_house_template(p_household_id uuid, p_profile jsonb default '{}', p_today date default current_date)
returns integer language plpgsql security definer set search_path = public as $$
declare inserted integer;
begin
  if not public.is_member(p_household_id) then raise exception 'not a member'; end if;

  with tpl (key, cond, title, notes, zone, schedule, months, ws, we) as (values
    ('gutters_autumn', null, 'Clean gutters and downpipes (takrenner)', 'Before first frost. Clear leaves; check joints and brackets.', 'house', 'seasonal', null::int, 9, 10),
    ('gutters_spring', null, 'Check gutters after winter', 'Ice and snow can bend brackets and loosen joints.', 'house', 'seasonal', null, 4, 5),
    ('drain_taps', null, 'Drain and shut off outdoor taps (utekran)', 'Close the indoor valve, open the outdoor tap so it drains. Do it before the first hard frost.', 'house', 'seasonal', null, 10, 11),
    ('yard_drains', null, 'Clear yard drains and grates (sluk)', 'Leaves and silt in drains cause water against the foundation.', 'house', 'seasonal', null, 9, 10),
    ('snow_prep', null, 'Get snow gear ready; check roof snow guards', 'Shovels, salt/grit, snow guards (snøfangere). Know where the roof access is.', 'house', 'seasonal', null, 10, 11),
    ('roof_moss', null, 'Inspect the roof and remove moss', 'From the ground or with binoculars first. Only go up when safe, or hire someone.', 'house', 'seasonal', null, 4, 5),
    ('windows_seals', null, 'Check window and door seals; oil hinges', 'Draughts, cracked sealant, sticking locks.', 'house', 'seasonal', null, 8, 9),
    ('smoke_detectors', null, 'Test smoke detectors', 'Press the test button; replace batteries when they chirp or yearly. Check local guidance.', 'house', 'interval', 3, null, null),
    ('fire_extinguisher', null, 'Check fire extinguisher and fire blanket', 'Gauge in the green, within date, easy to reach.', 'house', 'interval', 12, null, null),
    ('earth_fault_test', null, 'Test earth-fault breakers (jordfeilbryter)', 'Press the test button on the fuse box; it should trip. Reset afterwards.', 'house', 'interval', 6, null, null),
    ('wet_rooms', null, 'Check silicone and grout in bathroom and laundry', 'Cracks let water into the structure. Redo sealant when it is broken or mouldy.', 'house', 'interval', 12, null, null),
    ('water_heater', null, 'Check water heater and its safety valve', 'Look for leaks or corrosion; operate the safety valve per the manual.', 'house', 'interval', 12, null, null),
    ('chimney', 'has_wood_stove', 'Chimney sweep and fire inspection (feiing)', 'The kommune schedules this; check your interval and that they have access.', 'house', 'interval', 24, null, null),
    ('heat_pump_filters', 'has_heat_pump', 'Clean heat pump filters', 'Rinse indoor unit filters; clear leaves and snow around the outdoor unit.', 'house', 'interval', 3, null, null),
    ('ventilation_filters', 'has_balanced_ventilation', 'Replace ventilation filters', 'Balanced ventilation with heat recovery: check filter type in the manual.', 'house', 'interval', 6, null, null),
    ('basement_damp', 'has_basement', 'Check basement for damp, mould and humidity', 'Look at corners, floor drains and stored boxes. Note humidity readings.', 'house', 'interval', 12, null, null),
    ('facade', 'has_wooden_facade', 'Inspect wooden facade and paint or stain', 'Look for peeling, cracks and rot near the ground. Restain cycles vary widely.', 'house', 'seasonal', null, 5, 6),
    ('septic', 'has_septic', 'Septic tank emptying (slamavskiller)', 'Interval is set by the kommune and the tank type. Confirm yours.', 'house', 'interval', 24, null, null),
    ('well_water', 'has_well', 'Test well water quality', 'Bacteria and nitrate at minimum; more if there are taste or colour changes.', 'house', 'interval', 12, null, null),
    ('mower_service', 'has_garden', 'Service the lawn mower and garden tools', 'Blades, oil, spark plug or battery, before the season.', 'garden', 'seasonal', null, 3, 4),
    ('garden_spring', 'has_garden', 'Spring garden clean-up and lawn care', 'Rake, dethatch, reseed bare patches, first cut.', 'garden', 'seasonal', null, 4, 5),
    ('fence_gates', 'has_garden', 'Check fence, gates and garden structures', 'Posts, hinges, rot; treat or repair.', 'garden', 'seasonal', null, 5, 6),
    ('garden_autumn', 'has_garden', 'Autumn garden: rake leaves, prune, winterise', 'Store hoses, cover tender plants, plant bulbs.', 'garden', 'seasonal', null, 9, 10)
  ), picked as (
    select t.*, row_number() over (order by t.key) as rn
    from tpl t
    where t.cond is null or coalesce((p_profile ->> t.cond)::boolean, false)
  ), ins as (
    insert into public.maintenance_tasks
      (household_id, template_key, title, notes, zone, schedule, interval_months, window_start_month, window_end_month, next_due_at, due_until)
    select p_household_id, p.key, p.title, p.notes, p.zone, p.schedule, p.months, p.ws, p.we,
           case when p.schedule = 'seasonal' then (select f.next_due from public.first_seasonal_due(p.ws, p.we, p_today) f)
                else p_today + (7 + (p.rn % 8) * 7)::int end,
           case when p.schedule = 'seasonal' then (select f.due_until from public.first_seasonal_due(p.ws, p.we, p_today) f) end
    from picked p
    on conflict (household_id, template_key) do nothing
    returning 1
  )
  select count(*) into inserted from ins;
  return inserted;
end;
$$;

alter table public.maintenance_tasks enable row level security;
alter table public.maintenance_events enable row level security;

create policy maintenance_tasks_all on public.maintenance_tasks for all
  using (public.is_member(household_id)) with check (public.is_member(household_id));
create policy maintenance_events_select on public.maintenance_events for select using (public.is_member(household_id));

grant select, insert, update, delete on public.maintenance_tasks to authenticated;
grant select on public.maintenance_events to authenticated;
grant execute on function public.complete_maintenance(uuid, date, numeric, text) to authenticated;
grant execute on function public.seed_house_template(uuid, jsonb, date) to authenticated;

-- ===== 0004_suggestions.sql =====
-- AI place suggestions. The `suggest` edge function proposes a place for a to-do; the user confirms in the app.
-- suggested_at marks "already asked", so each to-do costs at most one model call.
alter table public.memories
  add column suggestion jsonb,
  add column suggested_at timestamptz;

-- ===== 0005_hardening.sql =====
-- Security hardening found in review.
-- 1. Invite codes: longer for new households, throttled guessing, and a way to rotate.
-- 2. Cross-household references: a to-do may only point at a place of its own household, media only at its own to-dos.

alter table public.households
  alter column invite_code set default substr(replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''), 1, 16);

-- Failed join attempts, used to throttle guessing. No policies: only the security definer functions touch it.
create table public.join_attempts (
  user_id uuid not null references auth.users (id) on delete cascade,
  at timestamptz not null default now()
);
create index join_attempts_user_idx on public.join_attempts (user_id, at desc);
alter table public.join_attempts enable row level security;

-- An unknown code now returns NULL (not an exception) so the failed attempt is recorded before the caller sees it.
create or replace function public.join_household(p_invite_code text, p_display_name text default null)
returns uuid language plpgsql security definer set search_path = public as $$
declare hid uuid; recent integer;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  select count(*) into recent from public.join_attempts where user_id = auth.uid() and at > now() - interval '1 hour';
  if recent >= 10 then raise exception 'too many attempts, try again later'; end if;

  select id into hid from public.households where invite_code = lower(trim(p_invite_code));
  if hid is null then
    insert into public.join_attempts (user_id) values (auth.uid());
    return null;
  end if;
  insert into public.household_members (household_id, user_id, display_name)
    values (hid, auth.uid(), p_display_name)
    on conflict do nothing;
  return hid;
end;
$$;

-- Any member can replace the household's invite code, which invalidates the old one.
create function public.rotate_invite_code(p_household_id uuid) returns text
language plpgsql security definer set search_path = public as $$
declare code text;
begin
  if not public.is_member(p_household_id) then raise exception 'not a member'; end if;
  code := substr(replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''), 1, 16);
  update public.households set invite_code = code where id = p_household_id;
  return code;
end;
$$;
grant execute on function public.rotate_invite_code(uuid) to authenticated;

create function public.check_same_household() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if tg_table_name = 'memories' then
    if new.place_id is not null and not exists (
      select 1 from public.places p where p.id = new.place_id and p.household_id = new.household_id
    ) then
      raise exception 'place belongs to another household';
    end if;
  elsif tg_table_name = 'media' then
    if not exists (select 1 from public.memories m where m.id = new.memory_id and m.household_id = new.household_id) then
      raise exception 'memory belongs to another household';
    end if;
  end if;
  return new;
end;
$$;
create trigger memories_same_household before insert or update of place_id on public.memories
  for each row execute function public.check_same_household();
create trigger media_same_household before insert or update of memory_id on public.media
  for each row execute function public.check_same_household();

-- ===== 0006_facts_and_custom_tasks.sql =====
-- House facts: things you need to look up in the shop or in an emergency (paint code, bulb type, measurements,
-- where the water shutoff is). surface_at lists shop categories where the fact should appear on the store list.

create table if not exists public.house_facts (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  title text not null,
  value text not null default '',
  category text not null default 'other' check (category in ('emergency', 'measurement', 'paint', 'appliance', 'other')),
  surface_at text[] not null default '{}',
  created_by uuid default auth.uid() references auth.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists house_facts_household_idx on public.house_facts (household_id, category);
drop trigger if exists house_facts_touch on public.house_facts;
create trigger house_facts_touch before update on public.house_facts
  for each row execute function public.touch_updated_at();

alter table public.house_facts enable row level security;
drop policy if exists house_facts_select on public.house_facts;
create policy house_facts_select on public.house_facts for select using (public.is_member(household_id));
drop policy if exists house_facts_insert on public.house_facts;
create policy house_facts_insert on public.house_facts for insert
  with check (public.is_member(household_id) and created_by = auth.uid());
-- Either partner may edit or delete a shared fact.
drop policy if exists house_facts_update on public.house_facts;
create policy house_facts_update on public.house_facts for update
  using (public.is_member(household_id)) with check (public.is_member(household_id));
drop policy if exists house_facts_delete on public.house_facts;
create policy house_facts_delete on public.house_facts for delete using (public.is_member(household_id));
grant select, insert, update, delete on public.house_facts to authenticated;

-- Your own recurring task. `p_last_done` (optional) says when it was last done, so the first due date is right.
create or replace function public.add_maintenance_task(
  p_household_id uuid, p_title text, p_notes text, p_schedule text,
  p_interval_months int default null, p_ws int default null, p_we int default null,
  p_last_done date default null, p_today date default current_date
) returns uuid language plpgsql security definer set search_path = public as $$
declare n record; new_id uuid;
begin
  if not public.is_member(p_household_id) then raise exception 'not a member'; end if;
  if coalesce(trim(p_title), '') = '' then raise exception 'title required'; end if;
  if p_schedule = 'interval' and p_interval_months is null then raise exception 'interval required'; end if;
  if p_schedule = 'seasonal' and (p_ws is null or p_we is null) then raise exception 'season required'; end if;

  if p_last_done is not null then
    select * into n from public.next_maintenance_due(p_schedule, p_interval_months, p_ws, p_we, p_last_done);
  elsif p_schedule = 'seasonal' then
    select * into n from public.first_seasonal_due(p_ws, p_we, p_today);
  else
    select (p_today + make_interval(months => p_interval_months))::date as next_due, null::date as due_until into n;
  end if;

  insert into public.maintenance_tasks
    (household_id, title, notes, zone, schedule, interval_months, window_start_month, window_end_month, next_due_at, due_until, last_done_at)
  values (p_household_id, trim(p_title), nullif(trim(p_notes), ''), 'house', p_schedule, p_interval_months, p_ws, p_we, n.next_due, n.due_until, p_last_done)
  returning id into new_id;
  return new_id;
end;
$$;
grant execute on function public.add_maintenance_task(uuid, text, text, text, int, int, int, date, date) to authenticated;

-- Make the API pick up the new table and function right away.
notify pgrst, 'reload schema';

-- ===== 0007_feed_keys.sql =====
-- Read-only "reminder keys". A key opens links on the web app's own domain (/api/remind and /calendar.ics) that
-- iPhone Shortcuts automations and the Calendar app call, so reminders work without a native app.
-- The key is a secret in the link: only its sha256 hash is stored, it can be revoked, and it only ever READS
-- to-dos, house tasks and facts that were tagged for a shop. It cannot change anything.

create table if not exists public.feed_keys (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  label text not null default 'iPhone',
  key_hash bytea not null unique,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);
create index if not exists feed_keys_user_idx on public.feed_keys (user_id);

alter table public.feed_keys enable row level security;
drop policy if exists feed_keys_select on public.feed_keys;
create policy feed_keys_select on public.feed_keys for select using (user_id = auth.uid());
drop policy if exists feed_keys_delete on public.feed_keys;
create policy feed_keys_delete on public.feed_keys for delete using (user_id = auth.uid());
grant select, delete on public.feed_keys to authenticated;

-- Returns the plaintext key exactly once.
create or replace function public.create_feed_key(p_household_id uuid, p_label text default 'iPhone')
returns text language plpgsql security definer set search_path = public as $$
declare k text;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if not public.is_member(p_household_id) then raise exception 'not a member'; end if;
  k := 'hmr_' || replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '');
  insert into public.feed_keys (household_id, user_id, label, key_hash)
    values (p_household_id, auth.uid(), coalesce(nullif(trim(p_label), ''), 'iPhone'), sha256(convert_to(k, 'utf8')));
  return k;
end;
$$;
grant execute on function public.create_feed_key(uuid, text) to authenticated;

-- What the reminder links show. Callable without login (anon): the key is the credential. Unknown or revoked key: NULL.
-- Deliberately narrow: no authors, no photos, and only facts that were tagged for a shop (the emergency card stays private).
create or replace function public.reminder_feed(p_key text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare fk public.feed_keys; result jsonb;
begin
  select * into fk from public.feed_keys where key_hash = sha256(convert_to(coalesce(p_key, ''), 'utf8'));
  if not found then return null; end if;
  update public.feed_keys set last_used_at = now() where id = fk.id;

  select jsonb_build_object(
    'household', (select h.name from public.households h where h.id = fk.household_id),
    'generated_at', now(),
    'places', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'name', p.name, 'kind', p.kind, 'category', p.category, 'radius_m', p.radius_m) order by p.created_at)
      from public.places p where p.household_id = fk.household_id), '[]'::jsonb),
    'todos', coalesce((
      select jsonb_agg(jsonb_build_object('id', m.id, 'body', left(m.body, 300), 'place_id', m.place_id, 'created_at', m.created_at) order by m.created_at desc)
      from (select * from public.memories where household_id = fk.household_id and status in ('inbox', 'active')
            order by created_at desc limit 300) m), '[]'::jsonb),
    'tasks', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', t.id, 'title', t.title, 'notes', t.notes, 'schedule', t.schedule, 'interval_months', t.interval_months,
        'window_start_month', t.window_start_month, 'window_end_month', t.window_end_month,
        'next_due_at', t.next_due_at, 'due_until', t.due_until, 'last_done_at', t.last_done_at) order by t.next_due_at)
      from public.maintenance_tasks t where t.household_id = fk.household_id and t.active), '[]'::jsonb),
    'facts', coalesce((
      select jsonb_agg(jsonb_build_object('title', f.title, 'value', f.value, 'surface_at', f.surface_at))
      from public.house_facts f where f.household_id = fk.household_id and cardinality(f.surface_at) > 0), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;
grant execute on function public.reminder_feed(text) to anon, authenticated;

-- ===== 0008_due_dates_and_addresses.sql =====
-- To-dos can have a date and an optional time; places can have an address; shared to-dos update live;
-- and the reminder feed carries the new fields. Written to be safe to run more than once.

alter table public.memories add column if not exists due_on date;
alter table public.memories add column if not exists due_time time;
alter table public.memories drop constraint if exists memories_due_time_needs_date;
alter table public.memories add constraint memories_due_time_needs_date check (due_time is null or due_on is not null);
create index if not exists memories_due_idx on public.memories (household_id, due_on)
  where due_on is not null and status in ('inbox', 'active');

alter table public.places add column if not exists address text;

-- Same narrow feed as before, now with due dates/times on to-dos and the address of places.
create or replace function public.reminder_feed(p_key text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare fk public.feed_keys; result jsonb;
begin
  select * into fk from public.feed_keys where key_hash = sha256(convert_to(coalesce(p_key, ''), 'utf8'));
  if not found then return null; end if;
  update public.feed_keys set last_used_at = now() where id = fk.id;

  select jsonb_build_object(
    'household', (select h.name from public.households h where h.id = fk.household_id),
    'generated_at', now(),
    'places', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'name', p.name, 'kind', p.kind, 'category', p.category, 'radius_m', p.radius_m, 'address', p.address) order by p.created_at)
      from public.places p where p.household_id = fk.household_id), '[]'::jsonb),
    'todos', coalesce((
      select jsonb_agg(jsonb_build_object('id', m.id, 'body', left(m.body, 300), 'place_id', m.place_id, 'created_at', m.created_at,
                                          'due_on', m.due_on, 'due_time', m.due_time) order by m.created_at desc)
      from (select * from public.memories where household_id = fk.household_id and status in ('inbox', 'active')
            order by created_at desc limit 300) m), '[]'::jsonb),
    'tasks', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', t.id, 'template_key', t.template_key, 'title', t.title, 'notes', t.notes, 'schedule', t.schedule, 'interval_months', t.interval_months,
        'window_start_month', t.window_start_month, 'window_end_month', t.window_end_month,
        'next_due_at', t.next_due_at, 'due_until', t.due_until, 'last_done_at', t.last_done_at) order by t.next_due_at)
      from public.maintenance_tasks t where t.household_id = fk.household_id and t.active), '[]'::jsonb),
    'facts', coalesce((
      select jsonb_agg(jsonb_build_object('title', f.title, 'value', f.value, 'surface_at', f.surface_at))
      from public.house_facts f where f.household_id = fk.household_id and cardinality(f.surface_at) > 0), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;
grant execute on function public.reminder_feed(text) to anon, authenticated;

-- ===== 0009_repeat_pushes_recap.sql =====
-- Repeating to-dos, who ticked something off, web push subscriptions, and a weekly "done" count in the reminder feed.
-- Written to be safe to run more than once.

alter table public.memories add column if not exists repeat_rule text;
alter table public.memories drop constraint if exists memories_repeat_rule_valid;
alter table public.memories add constraint memories_repeat_rule_valid
  check (repeat_rule is null or (repeat_rule in ('daily', 'weekly', 'monthly', 'yearly') and due_on is not null));
alter table public.memories add column if not exists done_by uuid references auth.users (id) on delete set null;

-- Ticks a to-do off. A repeating one also creates the next occurrence (the following date that is still in the future),
-- and returns that new to-do's id so the caller can undo. Runs as the definer but only for household members.
create or replace function public.complete_memory(p_id uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare m public.memories; nd date; nid uuid;
begin
  select * into m from public.memories where id = p_id;
  if not found or not public.is_member(m.household_id) then return null; end if;
  if m.status = 'done' then return null; end if;
  update public.memories set status = 'done', done_at = now(), done_by = auth.uid() where id = p_id;
  if m.repeat_rule is null or m.due_on is null then return null; end if;
  nd := m.due_on;
  loop
    nd := case m.repeat_rule
      when 'daily' then nd + 1
      when 'weekly' then nd + 7
      when 'monthly' then (nd + interval '1 month')::date
      else (nd + interval '1 year')::date end;
    exit when nd > current_date;
  end loop;
  insert into public.memories (household_id, author_id, body, status, place_id, place_category, due_on, due_time, repeat_rule)
  values (m.household_id, m.author_id, m.body, 'active', m.place_id, m.place_category, nd, m.due_time, m.repeat_rule)
  returning id into nid;
  return nid;
end;
$$;
grant execute on function public.complete_memory(uuid) to authenticated;

-- Web push: one row per browser/phone that wants to be told when the partner adds something.
create table if not exists public.web_push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  lang text not null default 'en' check (lang in ('en', 'nb')),
  created_at timestamptz not null default now()
);
alter table public.web_push_subscriptions enable row level security;
grant select, insert, update, delete on public.web_push_subscriptions to authenticated;
drop policy if exists web_push_own on public.web_push_subscriptions;
create policy web_push_own on public.web_push_subscriptions for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- A device that signs in as someone else takes its subscription over (the endpoint is unique per device).
create or replace function public.save_push_subscription(p_endpoint text, p_p256dh text, p_auth text, p_lang text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'not signed in'; end if;
  insert into public.web_push_subscriptions (user_id, endpoint, p256dh, auth, lang)
  values (auth.uid(), p_endpoint, p_p256dh, p_auth, case when p_lang = 'nb' then 'nb' else 'en' end)
  on conflict (endpoint) do update set user_id = auth.uid(), p256dh = excluded.p256dh, auth = excluded.auth, lang = excluded.lang;
end;
$$;
grant execute on function public.save_push_subscription(text, text, text, text) to authenticated;

-- The feed now carries repeat rules and how many to-dos were finished in the last 7 days.
create or replace function public.reminder_feed(p_key text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare fk public.feed_keys; result jsonb;
begin
  select * into fk from public.feed_keys where key_hash = sha256(convert_to(coalesce(p_key, ''), 'utf8'));
  if not found then return null; end if;
  update public.feed_keys set last_used_at = now() where id = fk.id;

  select jsonb_build_object(
    'household', (select h.name from public.households h where h.id = fk.household_id),
    'generated_at', now(),
    'done_week', (select count(*) from public.memories d where d.household_id = fk.household_id and d.status = 'done' and d.done_at > now() - interval '7 days'),
    'places', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'name', p.name, 'kind', p.kind, 'category', p.category, 'radius_m', p.radius_m, 'address', p.address) order by p.created_at)
      from public.places p where p.household_id = fk.household_id), '[]'::jsonb),
    'todos', coalesce((
      select jsonb_agg(jsonb_build_object('id', m.id, 'body', left(m.body, 300), 'place_id', m.place_id, 'created_at', m.created_at,
                                          'due_on', m.due_on, 'due_time', m.due_time, 'repeat_rule', m.repeat_rule) order by m.created_at desc)
      from (select * from public.memories where household_id = fk.household_id and status in ('inbox', 'active')
            order by created_at desc limit 300) m), '[]'::jsonb),
    'tasks', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', t.id, 'template_key', t.template_key, 'title', t.title, 'notes', t.notes, 'schedule', t.schedule, 'interval_months', t.interval_months,
        'window_start_month', t.window_start_month, 'window_end_month', t.window_end_month,
        'next_due_at', t.next_due_at, 'due_until', t.due_until, 'last_done_at', t.last_done_at) order by t.next_due_at)
      from public.maintenance_tasks t where t.household_id = fk.household_id and t.active), '[]'::jsonb),
    'facts', coalesce((
      select jsonb_agg(jsonb_build_object('title', f.title, 'value', f.value, 'surface_at', f.surface_at))
      from public.house_facts f where f.household_id = fk.household_id and cardinality(f.surface_at) > 0), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;
grant execute on function public.reminder_feed(text) to anon, authenticated;

-- ===== 0010_ai_limits_and_account_delete.sql =====
-- Daily limits for the AI features (they cost money per use), and a way to delete your own account.
-- Written to be safe to run more than once.

create table if not exists public.ai_usage (
  user_id uuid not null references auth.users (id) on delete cascade,
  day date not null default current_date,
  fn text not null,
  n integer not null default 0,
  primary key (user_id, day, fn)
);
alter table public.ai_usage enable row level security;

-- Counts one use of an AI function for the signed-in user today. Returns false when the daily limit is already reached
-- (the edge function then refuses before it calls the model).
create or replace function public.ai_take(p_fn text, p_limit integer) returns boolean
language plpgsql security definer set search_path = public as $$
declare used integer;
begin
  if auth.uid() is null then return false; end if;
  insert into public.ai_usage (user_id, day, fn, n) values (auth.uid(), current_date, p_fn, 0)
  on conflict (user_id, day, fn) do nothing;
  update public.ai_usage set n = n + 1
  where user_id = auth.uid() and day = current_date and fn = p_fn and n < p_limit
  returning n into used;
  return used is not null;
end;
$$;
grant execute on function public.ai_take(text, integer) to authenticated;

-- Deletes the signed-in user. Households where they are the only member are deleted with everything in them; in shared
-- households their to-dos stay (handed to another member) and only their membership goes.
create or replace function public.delete_my_account() returns void
language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid(); h record; other uuid;
begin
  if me is null then raise exception 'not signed in'; end if;
  for h in select household_id from public.household_members where user_id = me loop
    select user_id into other from public.household_members where household_id = h.household_id and user_id <> me order by joined_at nulls last, user_id limit 1;
    if other is null then
      delete from public.households where id = h.household_id;
    else
      update public.memories set author_id = other where household_id = h.household_id and author_id = me;
      delete from public.household_members where household_id = h.household_id and user_id = me;
    end if;
  end loop;
  -- Rows that point at the user without cascading are detached first.
  update public.maintenance_events set done_by = null where done_by = me;
  update public.house_facts set created_by = null where created_by = me;
  delete from auth.users where id = me;
end;
$$;
grant execute on function public.delete_my_account() to authenticated;

-- ===== 0011_assignee_and_pin.sql =====
-- Who a to-do is for, and pinning a to-do to the top of its list. Written to be safe to run more than once.

alter table public.memories add column if not exists assignee_id uuid references auth.users (id) on delete set null;
alter table public.memories add column if not exists pinned boolean not null default false;

-- A to-do can only be given to someone who is in the same household.
create or replace function public.check_assignee() returns trigger
language plpgsql set search_path = public as $$
begin
  if new.assignee_id is not null and not exists (
    select 1 from public.household_members hm where hm.household_id = new.household_id and hm.user_id = new.assignee_id
  ) then
    raise exception 'assignee is not in this household' using errcode = '23514';
  end if;
  return new;
end;
$$;
drop trigger if exists memories_check_assignee on public.memories;
create trigger memories_check_assignee before insert or update of assignee_id, household_id on public.memories
  for each row execute function public.check_assignee();

-- Same as before, and a repeating to-do keeps who it is for.
create or replace function public.complete_memory(p_id uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare m public.memories; nd date; nid uuid;
begin
  select * into m from public.memories where id = p_id;
  if not found or not public.is_member(m.household_id) then return null; end if;
  if m.status = 'done' then return null; end if;
  update public.memories set status = 'done', done_at = now(), done_by = auth.uid(), pinned = false where id = p_id;
  if m.repeat_rule is null or m.due_on is null then return null; end if;
  nd := m.due_on;
  loop
    nd := case m.repeat_rule
      when 'daily' then nd + 1
      when 'weekly' then nd + 7
      when 'monthly' then (nd + interval '1 month')::date
      else (nd + interval '1 year')::date end;
    exit when nd > current_date;
  end loop;
  insert into public.memories (household_id, author_id, body, status, place_id, place_category, due_on, due_time, repeat_rule, assignee_id)
  values (m.household_id, m.author_id, m.body, 'active', m.place_id, m.place_category, nd, m.due_time, m.repeat_rule, m.assignee_id)
  returning id into nid;
  return nid;
end;
$$;
grant execute on function public.complete_memory(uuid) to authenticated;

-- ===== 0012_due_pushes.sql =====
-- Reminders at a to-do's due time ("Call the plumber" at 18:00) as push notifications. This table remembers which to-dos were
-- already announced so nobody is told twice. Only the server (service role) uses it. Safe to run more than once.
create table if not exists public.due_pushes (
  memory_id uuid primary key references public.memories (id) on delete cascade,
  sent_at timestamptz not null default now()
);
alter table public.due_pushes enable row level security;
revoke all on public.due_pushes from anon, authenticated;

notify pgrst, 'reload schema';

-- ===== 0013_todo_details.sql =====
-- To-do details: notes, a checklist, priority and "remind me before", plus two more ways to repeat (weekdays, every other week).
-- Written to be safe to run more than once.

alter table public.memories add column if not exists notes text;
alter table public.memories add column if not exists checklist jsonb not null default '[]'::jsonb;
alter table public.memories add column if not exists priority smallint not null default 0;
alter table public.memories add column if not exists remind_before integer;

alter table public.memories drop constraint if exists memories_priority_valid;
alter table public.memories add constraint memories_priority_valid check (priority between 0 and 3);
alter table public.memories drop constraint if exists memories_remind_before_valid;
alter table public.memories add constraint memories_remind_before_valid check (remind_before is null or (remind_before between 0 and 20160));
alter table public.memories drop constraint if exists memories_checklist_valid;
alter table public.memories add constraint memories_checklist_valid check (jsonb_typeof(checklist) = 'array' and jsonb_array_length(checklist) <= 100);

alter table public.memories drop constraint if exists memories_repeat_rule_valid;
alter table public.memories add constraint memories_repeat_rule_valid
  check (repeat_rule is null or (repeat_rule in ('daily', 'weekdays', 'weekly', 'biweekly', 'monthly', 'yearly') and due_on is not null));

-- Ticking off a repeating to-do creates the next one. It now keeps notes, priority and reminder, and its checklist starts unticked.
create or replace function public.complete_memory(p_id uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare m public.memories; nd date; nid uuid;
begin
  select * into m from public.memories where id = p_id;
  if not found or not public.is_member(m.household_id) then return null; end if;
  if m.status = 'done' then return null; end if;
  update public.memories set status = 'done', done_at = now(), done_by = auth.uid(), pinned = false where id = p_id;
  if m.repeat_rule is null or m.due_on is null then return null; end if;
  nd := m.due_on;
  loop
    nd := case m.repeat_rule
      when 'daily' then nd + 1
      when 'weekdays' then nd + case extract(dow from nd)::int when 5 then 3 when 6 then 2 else 1 end
      when 'weekly' then nd + 7
      when 'biweekly' then nd + 14
      when 'monthly' then (nd + interval '1 month')::date
      else (nd + interval '1 year')::date end;
    exit when nd > current_date;
  end loop;
  insert into public.memories (household_id, author_id, body, status, place_id, place_category, due_on, due_time, repeat_rule, assignee_id, notes, checklist, priority, remind_before)
  values (m.household_id, m.author_id, m.body, 'active', m.place_id, m.place_category, nd, m.due_time, m.repeat_rule, m.assignee_id, m.notes,
    (select coalesce(jsonb_agg(jsonb_set(e, '{done}', 'false'::jsonb)), '[]'::jsonb) from jsonb_array_elements(m.checklist) e), m.priority, m.remind_before)
  returning id into nid;
  return nid;
end;
$$;
grant execute on function public.complete_memory(uuid) to authenticated;

notify pgrst, 'reload schema';

-- ===== 0014_tags_and_order.sql =====
-- Tags on a to-do, and a manual order (drag or move up/down). Written to be safe to run more than once.
alter table public.memories add column if not exists tags text[] not null default '{}';
alter table public.memories add column if not exists sort_order double precision;

alter table public.memories drop constraint if exists memories_tags_valid;
alter table public.memories add constraint memories_tags_valid check (coalesce(array_length(tags, 1), 0) <= 12);
create index if not exists memories_tags_idx on public.memories using gin (tags);

-- A repeating to-do keeps its tags (its place in a manual order starts fresh).
create or replace function public.complete_memory(p_id uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare m public.memories; nd date; nid uuid;
begin
  select * into m from public.memories where id = p_id;
  if not found or not public.is_member(m.household_id) then return null; end if;
  if m.status = 'done' then return null; end if;
  update public.memories set status = 'done', done_at = now(), done_by = auth.uid(), pinned = false where id = p_id;
  if m.repeat_rule is null or m.due_on is null then return null; end if;
  nd := m.due_on;
  loop
    nd := case m.repeat_rule
      when 'daily' then nd + 1
      when 'weekdays' then nd + case extract(dow from nd)::int when 5 then 3 when 6 then 2 else 1 end
      when 'weekly' then nd + 7
      when 'biweekly' then nd + 14
      when 'monthly' then (nd + interval '1 month')::date
      else (nd + interval '1 year')::date end;
    exit when nd > current_date;
  end loop;
  insert into public.memories (household_id, author_id, body, status, place_id, place_category, due_on, due_time, repeat_rule, assignee_id, notes, checklist, priority, remind_before, tags)
  values (m.household_id, m.author_id, m.body, 'active', m.place_id, m.place_category, nd, m.due_time, m.repeat_rule, m.assignee_id, m.notes,
    (select coalesce(jsonb_agg(jsonb_set(e, '{done}', 'false'::jsonb)), '[]'::jsonb) from jsonb_array_elements(m.checklist) e), m.priority, m.remind_before, m.tags)
  returning id into nid;
  return nid;
end;
$$;
grant execute on function public.complete_memory(uuid) to authenticated;

notify pgrst, 'reload schema';

-- ===== 0015_duration_and_travel.sql =====
-- How long a to-do takes (minutes), and "remind me when it is time to leave" (travel time to the place). Safe to run more than once.
alter table public.memories add column if not exists duration_min integer;
alter table public.memories add column if not exists remind_travel boolean not null default false;

alter table public.memories drop constraint if exists memories_duration_valid;
alter table public.memories add constraint memories_duration_valid check (duration_min is null or (duration_min between 1 and 1440));

-- A repeating to-do keeps both.
create or replace function public.complete_memory(p_id uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare m public.memories; nd date; nid uuid;
begin
  select * into m from public.memories where id = p_id;
  if not found or not public.is_member(m.household_id) then return null; end if;
  if m.status = 'done' then return null; end if;
  update public.memories set status = 'done', done_at = now(), done_by = auth.uid(), pinned = false where id = p_id;
  if m.repeat_rule is null or m.due_on is null then return null; end if;
  nd := m.due_on;
  loop
    nd := case m.repeat_rule
      when 'daily' then nd + 1
      when 'weekdays' then nd + case extract(dow from nd)::int when 5 then 3 when 6 then 2 else 1 end
      when 'weekly' then nd + 7
      when 'biweekly' then nd + 14
      when 'monthly' then (nd + interval '1 month')::date
      else (nd + interval '1 year')::date end;
    exit when nd > current_date;
  end loop;
  insert into public.memories (household_id, author_id, body, status, place_id, place_category, due_on, due_time, repeat_rule, assignee_id, notes, checklist, priority, remind_before, tags, duration_min, remind_travel)
  values (m.household_id, m.author_id, m.body, 'active', m.place_id, m.place_category, nd, m.due_time, m.repeat_rule, m.assignee_id, m.notes,
    (select coalesce(jsonb_agg(jsonb_set(e, '{done}', 'false'::jsonb)), '[]'::jsonb) from jsonb_array_elements(m.checklist) e), m.priority, m.remind_before, m.tags, m.duration_min, m.remind_travel)
  returning id into nid;
  return nid;
end;
$$;
grant execute on function public.complete_memory(uuid) to authenticated;

notify pgrst, 'reload schema';
