-- Generated by build-setup.mjs. Paste into Supabase > SQL Editor > New query, then Run.
-- Upgrade for projects that already ran setup.sql up to migration 0005. Run once.

-- ===== 0006_facts_and_custom_tasks.sql =====
-- House facts: things you need to look up in the shop or in an emergency (paint code, bulb type, measurements,
-- where the water shutoff is). surface_at lists shop categories where the fact should appear on the store list.

create table if not exists public.house_facts (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  title text not null,
  value text not null default '',
  category text not null default 'other' check (category in ('emergency', 'measurement', 'paint', 'appliance', 'other')),
  surface_at text[] not null default '{}',
  created_by uuid default auth.uid() references auth.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists house_facts_household_idx on public.house_facts (household_id, category);
drop trigger if exists house_facts_touch on public.house_facts;
create trigger house_facts_touch before update on public.house_facts
  for each row execute function public.touch_updated_at();

alter table public.house_facts enable row level security;
drop policy if exists house_facts_select on public.house_facts;
create policy house_facts_select on public.house_facts for select using (public.is_member(household_id));
drop policy if exists house_facts_insert on public.house_facts;
create policy house_facts_insert on public.house_facts for insert
  with check (public.is_member(household_id) and created_by = auth.uid());
-- Either partner may edit or delete a shared fact.
drop policy if exists house_facts_update on public.house_facts;
create policy house_facts_update on public.house_facts for update
  using (public.is_member(household_id)) with check (public.is_member(household_id));
drop policy if exists house_facts_delete on public.house_facts;
create policy house_facts_delete on public.house_facts for delete using (public.is_member(household_id));
grant select, insert, update, delete on public.house_facts to authenticated;

-- Your own recurring task. `p_last_done` (optional) says when it was last done, so the first due date is right.
create or replace function public.add_maintenance_task(
  p_household_id uuid, p_title text, p_notes text, p_schedule text,
  p_interval_months int default null, p_ws int default null, p_we int default null,
  p_last_done date default null, p_today date default current_date
) returns uuid language plpgsql security definer set search_path = public as $$
declare n record; new_id uuid;
begin
  if not public.is_member(p_household_id) then raise exception 'not a member'; end if;
  if coalesce(trim(p_title), '') = '' then raise exception 'title required'; end if;
  if p_schedule = 'interval' and p_interval_months is null then raise exception 'interval required'; end if;
  if p_schedule = 'seasonal' and (p_ws is null or p_we is null) then raise exception 'season required'; end if;

  if p_last_done is not null then
    select * into n from public.next_maintenance_due(p_schedule, p_interval_months, p_ws, p_we, p_last_done);
  elsif p_schedule = 'seasonal' then
    select * into n from public.first_seasonal_due(p_ws, p_we, p_today);
  else
    select (p_today + make_interval(months => p_interval_months))::date as next_due, null::date as due_until into n;
  end if;

  insert into public.maintenance_tasks
    (household_id, title, notes, zone, schedule, interval_months, window_start_month, window_end_month, next_due_at, due_until, last_done_at)
  values (p_household_id, trim(p_title), nullif(trim(p_notes), ''), 'house', p_schedule, p_interval_months, p_ws, p_we, n.next_due, n.due_until, p_last_done)
  returning id into new_id;
  return new_id;
end;
$$;
grant execute on function public.add_maintenance_task(uuid, text, text, text, int, int, int, date, date) to authenticated;

-- Make the API pick up the new table and function right away.
notify pgrst, 'reload schema';

-- ===== 0007_feed_keys.sql =====
-- Read-only "reminder keys". A key opens links on the web app's own domain (/api/remind and /calendar.ics) that
-- iPhone Shortcuts automations and the Calendar app call, so reminders work without a native app.
-- The key is a secret in the link: only its sha256 hash is stored, it can be revoked, and it only ever READS
-- to-dos, house tasks and facts that were tagged for a shop. It cannot change anything.

create table if not exists public.feed_keys (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  label text not null default 'iPhone',
  key_hash bytea not null unique,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);
create index if not exists feed_keys_user_idx on public.feed_keys (user_id);

alter table public.feed_keys enable row level security;
drop policy if exists feed_keys_select on public.feed_keys;
create policy feed_keys_select on public.feed_keys for select using (user_id = auth.uid());
drop policy if exists feed_keys_delete on public.feed_keys;
create policy feed_keys_delete on public.feed_keys for delete using (user_id = auth.uid());
grant select, delete on public.feed_keys to authenticated;

-- Returns the plaintext key exactly once.
create or replace function public.create_feed_key(p_household_id uuid, p_label text default 'iPhone')
returns text language plpgsql security definer set search_path = public as $$
declare k text;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if not public.is_member(p_household_id) then raise exception 'not a member'; end if;
  k := 'hmr_' || replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '');
  insert into public.feed_keys (household_id, user_id, label, key_hash)
    values (p_household_id, auth.uid(), coalesce(nullif(trim(p_label), ''), 'iPhone'), sha256(convert_to(k, 'utf8')));
  return k;
end;
$$;
grant execute on function public.create_feed_key(uuid, text) to authenticated;

-- What the reminder links show. Callable without login (anon): the key is the credential. Unknown or revoked key: NULL.
-- Deliberately narrow: no authors, no photos, and only facts that were tagged for a shop (the emergency card stays private).
create or replace function public.reminder_feed(p_key text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare fk public.feed_keys; result jsonb;
begin
  select * into fk from public.feed_keys where key_hash = sha256(convert_to(coalesce(p_key, ''), 'utf8'));
  if not found then return null; end if;
  update public.feed_keys set last_used_at = now() where id = fk.id;

  select jsonb_build_object(
    'household', (select h.name from public.households h where h.id = fk.household_id),
    'generated_at', now(),
    'places', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'name', p.name, 'kind', p.kind, 'category', p.category, 'radius_m', p.radius_m) order by p.created_at)
      from public.places p where p.household_id = fk.household_id), '[]'::jsonb),
    'todos', coalesce((
      select jsonb_agg(jsonb_build_object('id', m.id, 'body', left(m.body, 300), 'place_id', m.place_id, 'created_at', m.created_at) order by m.created_at desc)
      from (select * from public.memories where household_id = fk.household_id and status in ('inbox', 'active')
            order by created_at desc limit 300) m), '[]'::jsonb),
    'tasks', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', t.id, 'title', t.title, 'notes', t.notes, 'schedule', t.schedule, 'interval_months', t.interval_months,
        'window_start_month', t.window_start_month, 'window_end_month', t.window_end_month,
        'next_due_at', t.next_due_at, 'due_until', t.due_until, 'last_done_at', t.last_done_at) order by t.next_due_at)
      from public.maintenance_tasks t where t.household_id = fk.household_id and t.active), '[]'::jsonb),
    'facts', coalesce((
      select jsonb_agg(jsonb_build_object('title', f.title, 'value', f.value, 'surface_at', f.surface_at))
      from public.house_facts f where f.household_id = fk.household_id and cardinality(f.surface_at) > 0), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;
grant execute on function public.reminder_feed(text) to anon, authenticated;

-- ===== 0008_due_dates_and_addresses.sql =====
-- To-dos can have a date and an optional time; places can have an address; shared to-dos update live;
-- and the reminder feed carries the new fields. Written to be safe to run more than once.

alter table public.memories add column if not exists due_on date;
alter table public.memories add column if not exists due_time time;
alter table public.memories drop constraint if exists memories_due_time_needs_date;
alter table public.memories add constraint memories_due_time_needs_date check (due_time is null or due_on is not null);
create index if not exists memories_due_idx on public.memories (household_id, due_on)
  where due_on is not null and status in ('inbox', 'active');

alter table public.places add column if not exists address text;

-- Same narrow feed as before, now with due dates/times on to-dos and the address of places.
create or replace function public.reminder_feed(p_key text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare fk public.feed_keys; result jsonb;
begin
  select * into fk from public.feed_keys where key_hash = sha256(convert_to(coalesce(p_key, ''), 'utf8'));
  if not found then return null; end if;
  update public.feed_keys set last_used_at = now() where id = fk.id;

  select jsonb_build_object(
    'household', (select h.name from public.households h where h.id = fk.household_id),
    'generated_at', now(),
    'places', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'name', p.name, 'kind', p.kind, 'category', p.category, 'radius_m', p.radius_m, 'address', p.address) order by p.created_at)
      from public.places p where p.household_id = fk.household_id), '[]'::jsonb),
    'todos', coalesce((
      select jsonb_agg(jsonb_build_object('id', m.id, 'body', left(m.body, 300), 'place_id', m.place_id, 'created_at', m.created_at,
                                          'due_on', m.due_on, 'due_time', m.due_time) order by m.created_at desc)
      from (select * from public.memories where household_id = fk.household_id and status in ('inbox', 'active')
            order by created_at desc limit 300) m), '[]'::jsonb),
    'tasks', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', t.id, 'template_key', t.template_key, 'title', t.title, 'notes', t.notes, 'schedule', t.schedule, 'interval_months', t.interval_months,
        'window_start_month', t.window_start_month, 'window_end_month', t.window_end_month,
        'next_due_at', t.next_due_at, 'due_until', t.due_until, 'last_done_at', t.last_done_at) order by t.next_due_at)
      from public.maintenance_tasks t where t.household_id = fk.household_id and t.active), '[]'::jsonb),
    'facts', coalesce((
      select jsonb_agg(jsonb_build_object('title', f.title, 'value', f.value, 'surface_at', f.surface_at))
      from public.house_facts f where f.household_id = fk.household_id and cardinality(f.surface_at) > 0), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;
grant execute on function public.reminder_feed(text) to anon, authenticated;

-- ===== 0009_repeat_pushes_recap.sql =====
-- Repeating to-dos, who ticked something off, web push subscriptions, and a weekly "done" count in the reminder feed.
-- Written to be safe to run more than once.

alter table public.memories add column if not exists repeat_rule text;
alter table public.memories drop constraint if exists memories_repeat_rule_valid;
alter table public.memories add constraint memories_repeat_rule_valid
  check (repeat_rule is null or (repeat_rule in ('daily', 'weekly', 'monthly', 'yearly') and due_on is not null));
alter table public.memories add column if not exists done_by uuid references auth.users (id) on delete set null;

-- Ticks a to-do off. A repeating one also creates the next occurrence (the following date that is still in the future),
-- and returns that new to-do's id so the caller can undo. Runs as the definer but only for household members.
create or replace function public.complete_memory(p_id uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare m public.memories; nd date; nid uuid;
begin
  select * into m from public.memories where id = p_id;
  if not found or not public.is_member(m.household_id) then return null; end if;
  if m.status = 'done' then return null; end if;
  update public.memories set status = 'done', done_at = now(), done_by = auth.uid() where id = p_id;
  if m.repeat_rule is null or m.due_on is null then return null; end if;
  nd := m.due_on;
  loop
    nd := case m.repeat_rule
      when 'daily' then nd + 1
      when 'weekly' then nd + 7
      when 'monthly' then (nd + interval '1 month')::date
      else (nd + interval '1 year')::date end;
    exit when nd > current_date;
  end loop;
  insert into public.memories (household_id, author_id, body, status, place_id, place_category, due_on, due_time, repeat_rule)
  values (m.household_id, m.author_id, m.body, 'active', m.place_id, m.place_category, nd, m.due_time, m.repeat_rule)
  returning id into nid;
  return nid;
end;
$$;
grant execute on function public.complete_memory(uuid) to authenticated;

-- Web push: one row per browser/phone that wants to be told when the partner adds something.
create table if not exists public.web_push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  lang text not null default 'en' check (lang in ('en', 'nb')),
  created_at timestamptz not null default now()
);
alter table public.web_push_subscriptions enable row level security;
grant select, insert, update, delete on public.web_push_subscriptions to authenticated;
drop policy if exists web_push_own on public.web_push_subscriptions;
create policy web_push_own on public.web_push_subscriptions for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- A device that signs in as someone else takes its subscription over (the endpoint is unique per device).
create or replace function public.save_push_subscription(p_endpoint text, p_p256dh text, p_auth text, p_lang text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'not signed in'; end if;
  insert into public.web_push_subscriptions (user_id, endpoint, p256dh, auth, lang)
  values (auth.uid(), p_endpoint, p_p256dh, p_auth, case when p_lang = 'nb' then 'nb' else 'en' end)
  on conflict (endpoint) do update set user_id = auth.uid(), p256dh = excluded.p256dh, auth = excluded.auth, lang = excluded.lang;
end;
$$;
grant execute on function public.save_push_subscription(text, text, text, text) to authenticated;

-- The feed now carries repeat rules and how many to-dos were finished in the last 7 days.
create or replace function public.reminder_feed(p_key text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare fk public.feed_keys; result jsonb;
begin
  select * into fk from public.feed_keys where key_hash = sha256(convert_to(coalesce(p_key, ''), 'utf8'));
  if not found then return null; end if;
  update public.feed_keys set last_used_at = now() where id = fk.id;

  select jsonb_build_object(
    'household', (select h.name from public.households h where h.id = fk.household_id),
    'generated_at', now(),
    'done_week', (select count(*) from public.memories d where d.household_id = fk.household_id and d.status = 'done' and d.done_at > now() - interval '7 days'),
    'places', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'name', p.name, 'kind', p.kind, 'category', p.category, 'radius_m', p.radius_m, 'address', p.address) order by p.created_at)
      from public.places p where p.household_id = fk.household_id), '[]'::jsonb),
    'todos', coalesce((
      select jsonb_agg(jsonb_build_object('id', m.id, 'body', left(m.body, 300), 'place_id', m.place_id, 'created_at', m.created_at,
                                          'due_on', m.due_on, 'due_time', m.due_time, 'repeat_rule', m.repeat_rule) order by m.created_at desc)
      from (select * from public.memories where household_id = fk.household_id and status in ('inbox', 'active')
            order by created_at desc limit 300) m), '[]'::jsonb),
    'tasks', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', t.id, 'template_key', t.template_key, 'title', t.title, 'notes', t.notes, 'schedule', t.schedule, 'interval_months', t.interval_months,
        'window_start_month', t.window_start_month, 'window_end_month', t.window_end_month,
        'next_due_at', t.next_due_at, 'due_until', t.due_until, 'last_done_at', t.last_done_at) order by t.next_due_at)
      from public.maintenance_tasks t where t.household_id = fk.household_id and t.active), '[]'::jsonb),
    'facts', coalesce((
      select jsonb_agg(jsonb_build_object('title', f.title, 'value', f.value, 'surface_at', f.surface_at))
      from public.house_facts f where f.household_id = fk.household_id and cardinality(f.surface_at) > 0), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;
grant execute on function public.reminder_feed(text) to anon, authenticated;

-- ===== 0010_ai_limits_and_account_delete.sql =====
-- Daily limits for the AI features (they cost money per use), and a way to delete your own account.
-- Written to be safe to run more than once.

create table if not exists public.ai_usage (
  user_id uuid not null references auth.users (id) on delete cascade,
  day date not null default current_date,
  fn text not null,
  n integer not null default 0,
  primary key (user_id, day, fn)
);
alter table public.ai_usage enable row level security;

-- Counts one use of an AI function for the signed-in user today. Returns false when the daily limit is already reached
-- (the edge function then refuses before it calls the model).
create or replace function public.ai_take(p_fn text, p_limit integer) returns boolean
language plpgsql security definer set search_path = public as $$
declare used integer;
begin
  if auth.uid() is null then return false; end if;
  insert into public.ai_usage (user_id, day, fn, n) values (auth.uid(), current_date, p_fn, 0)
  on conflict (user_id, day, fn) do nothing;
  update public.ai_usage set n = n + 1
  where user_id = auth.uid() and day = current_date and fn = p_fn and n < p_limit
  returning n into used;
  return used is not null;
end;
$$;
grant execute on function public.ai_take(text, integer) to authenticated;

-- Deletes the signed-in user. Households where they are the only member are deleted with everything in them; in shared
-- households their to-dos stay (handed to another member) and only their membership goes.
create or replace function public.delete_my_account() returns void
language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid(); h record; other uuid;
begin
  if me is null then raise exception 'not signed in'; end if;
  for h in select household_id from public.household_members where user_id = me loop
    select user_id into other from public.household_members where household_id = h.household_id and user_id <> me order by joined_at nulls last, user_id limit 1;
    if other is null then
      delete from public.households where id = h.household_id;
    else
      update public.memories set author_id = other where household_id = h.household_id and author_id = me;
      delete from public.household_members where household_id = h.household_id and user_id = me;
    end if;
  end loop;
  -- Rows that point at the user without cascading are detached first.
  update public.maintenance_events set done_by = null where done_by = me;
  update public.house_facts set created_by = null where created_by = me;
  delete from auth.users where id = me;
end;
$$;
grant execute on function public.delete_my_account() to authenticated;

-- ===== 0011_assignee_and_pin.sql =====
-- Who a to-do is for, and pinning a to-do to the top of its list. Written to be safe to run more than once.

alter table public.memories add column if not exists assignee_id uuid references auth.users (id) on delete set null;
alter table public.memories add column if not exists pinned boolean not null default false;

-- A to-do can only be given to someone who is in the same household.
create or replace function public.check_assignee() returns trigger
language plpgsql set search_path = public as $$
begin
  if new.assignee_id is not null and not exists (
    select 1 from public.household_members hm where hm.household_id = new.household_id and hm.user_id = new.assignee_id
  ) then
    raise exception 'assignee is not in this household' using errcode = '23514';
  end if;
  return new;
end;
$$;
drop trigger if exists memories_check_assignee on public.memories;
create trigger memories_check_assignee before insert or update of assignee_id, household_id on public.memories
  for each row execute function public.check_assignee();

-- Same as before, and a repeating to-do keeps who it is for.
create or replace function public.complete_memory(p_id uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare m public.memories; nd date; nid uuid;
begin
  select * into m from public.memories where id = p_id;
  if not found or not public.is_member(m.household_id) then return null; end if;
  if m.status = 'done' then return null; end if;
  update public.memories set status = 'done', done_at = now(), done_by = auth.uid(), pinned = false where id = p_id;
  if m.repeat_rule is null or m.due_on is null then return null; end if;
  nd := m.due_on;
  loop
    nd := case m.repeat_rule
      when 'daily' then nd + 1
      when 'weekly' then nd + 7
      when 'monthly' then (nd + interval '1 month')::date
      else (nd + interval '1 year')::date end;
    exit when nd > current_date;
  end loop;
  insert into public.memories (household_id, author_id, body, status, place_id, place_category, due_on, due_time, repeat_rule, assignee_id)
  values (m.household_id, m.author_id, m.body, 'active', m.place_id, m.place_category, nd, m.due_time, m.repeat_rule, m.assignee_id)
  returning id into nid;
  return nid;
end;
$$;
grant execute on function public.complete_memory(uuid) to authenticated;

-- ===== 0012_due_pushes.sql =====
-- Reminders at a to-do's due time ("Call the plumber" at 18:00) as push notifications. This table remembers which to-dos were
-- already announced so nobody is told twice. Only the server (service role) uses it. Safe to run more than once.
create table if not exists public.due_pushes (
  memory_id uuid primary key references public.memories (id) on delete cascade,
  sent_at timestamptz not null default now()
);
alter table public.due_pushes enable row level security;
revoke all on public.due_pushes from anon, authenticated;

notify pgrst, 'reload schema';

-- ===== 0013_todo_details.sql =====
-- To-do details: notes, a checklist, priority and "remind me before", plus two more ways to repeat (weekdays, every other week).
-- Written to be safe to run more than once.

alter table public.memories add column if not exists notes text;
alter table public.memories add column if not exists checklist jsonb not null default '[]'::jsonb;
alter table public.memories add column if not exists priority smallint not null default 0;
alter table public.memories add column if not exists remind_before integer;

alter table public.memories drop constraint if exists memories_priority_valid;
alter table public.memories add constraint memories_priority_valid check (priority between 0 and 3);
alter table public.memories drop constraint if exists memories_remind_before_valid;
alter table public.memories add constraint memories_remind_before_valid check (remind_before is null or (remind_before between 0 and 20160));
alter table public.memories drop constraint if exists memories_checklist_valid;
alter table public.memories add constraint memories_checklist_valid check (jsonb_typeof(checklist) = 'array' and jsonb_array_length(checklist) <= 100);

alter table public.memories drop constraint if exists memories_repeat_rule_valid;
alter table public.memories add constraint memories_repeat_rule_valid
  check (repeat_rule is null or (repeat_rule in ('daily', 'weekdays', 'weekly', 'biweekly', 'monthly', 'yearly') and due_on is not null));

-- Ticking off a repeating to-do creates the next one. It now keeps notes, priority and reminder, and its checklist starts unticked.
create or replace function public.complete_memory(p_id uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare m public.memories; nd date; nid uuid;
begin
  select * into m from public.memories where id = p_id;
  if not found or not public.is_member(m.household_id) then return null; end if;
  if m.status = 'done' then return null; end if;
  update public.memories set status = 'done', done_at = now(), done_by = auth.uid(), pinned = false where id = p_id;
  if m.repeat_rule is null or m.due_on is null then return null; end if;
  nd := m.due_on;
  loop
    nd := case m.repeat_rule
      when 'daily' then nd + 1
      when 'weekdays' then nd + case extract(dow from nd)::int when 5 then 3 when 6 then 2 else 1 end
      when 'weekly' then nd + 7
      when 'biweekly' then nd + 14
      when 'monthly' then (nd + interval '1 month')::date
      else (nd + interval '1 year')::date end;
    exit when nd > current_date;
  end loop;
  insert into public.memories (household_id, author_id, body, status, place_id, place_category, due_on, due_time, repeat_rule, assignee_id, notes, checklist, priority, remind_before)
  values (m.household_id, m.author_id, m.body, 'active', m.place_id, m.place_category, nd, m.due_time, m.repeat_rule, m.assignee_id, m.notes,
    (select coalesce(jsonb_agg(jsonb_set(e, '{done}', 'false'::jsonb)), '[]'::jsonb) from jsonb_array_elements(m.checklist) e), m.priority, m.remind_before)
  returning id into nid;
  return nid;
end;
$$;
grant execute on function public.complete_memory(uuid) to authenticated;

notify pgrst, 'reload schema';

-- ===== 0014_tags_and_order.sql =====
-- Tags on a to-do, and a manual order (drag or move up/down). Written to be safe to run more than once.
alter table public.memories add column if not exists tags text[] not null default '{}';
alter table public.memories add column if not exists sort_order double precision;

alter table public.memories drop constraint if exists memories_tags_valid;
alter table public.memories add constraint memories_tags_valid check (coalesce(array_length(tags, 1), 0) <= 12);
create index if not exists memories_tags_idx on public.memories using gin (tags);

-- A repeating to-do keeps its tags (its place in a manual order starts fresh).
create or replace function public.complete_memory(p_id uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare m public.memories; nd date; nid uuid;
begin
  select * into m from public.memories where id = p_id;
  if not found or not public.is_member(m.household_id) then return null; end if;
  if m.status = 'done' then return null; end if;
  update public.memories set status = 'done', done_at = now(), done_by = auth.uid(), pinned = false where id = p_id;
  if m.repeat_rule is null or m.due_on is null then return null; end if;
  nd := m.due_on;
  loop
    nd := case m.repeat_rule
      when 'daily' then nd + 1
      when 'weekdays' then nd + case extract(dow from nd)::int when 5 then 3 when 6 then 2 else 1 end
      when 'weekly' then nd + 7
      when 'biweekly' then nd + 14
      when 'monthly' then (nd + interval '1 month')::date
      else (nd + interval '1 year')::date end;
    exit when nd > current_date;
  end loop;
  insert into public.memories (household_id, author_id, body, status, place_id, place_category, due_on, due_time, repeat_rule, assignee_id, notes, checklist, priority, remind_before, tags)
  values (m.household_id, m.author_id, m.body, 'active', m.place_id, m.place_category, nd, m.due_time, m.repeat_rule, m.assignee_id, m.notes,
    (select coalesce(jsonb_agg(jsonb_set(e, '{done}', 'false'::jsonb)), '[]'::jsonb) from jsonb_array_elements(m.checklist) e), m.priority, m.remind_before, m.tags)
  returning id into nid;
  return nid;
end;
$$;
grant execute on function public.complete_memory(uuid) to authenticated;

notify pgrst, 'reload schema';

-- ===== 0015_duration_and_travel.sql =====
-- How long a to-do takes (minutes), and "remind me when it is time to leave" (travel time to the place). Safe to run more than once.
alter table public.memories add column if not exists duration_min integer;
alter table public.memories add column if not exists remind_travel boolean not null default false;

alter table public.memories drop constraint if exists memories_duration_valid;
alter table public.memories add constraint memories_duration_valid check (duration_min is null or (duration_min between 1 and 1440));

-- A repeating to-do keeps both.
create or replace function public.complete_memory(p_id uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare m public.memories; nd date; nid uuid;
begin
  select * into m from public.memories where id = p_id;
  if not found or not public.is_member(m.household_id) then return null; end if;
  if m.status = 'done' then return null; end if;
  update public.memories set status = 'done', done_at = now(), done_by = auth.uid(), pinned = false where id = p_id;
  if m.repeat_rule is null or m.due_on is null then return null; end if;
  nd := m.due_on;
  loop
    nd := case m.repeat_rule
      when 'daily' then nd + 1
      when 'weekdays' then nd + case extract(dow from nd)::int when 5 then 3 when 6 then 2 else 1 end
      when 'weekly' then nd + 7
      when 'biweekly' then nd + 14
      when 'monthly' then (nd + interval '1 month')::date
      else (nd + interval '1 year')::date end;
    exit when nd > current_date;
  end loop;
  insert into public.memories (household_id, author_id, body, status, place_id, place_category, due_on, due_time, repeat_rule, assignee_id, notes, checklist, priority, remind_before, tags, duration_min, remind_travel)
  values (m.household_id, m.author_id, m.body, 'active', m.place_id, m.place_category, nd, m.due_time, m.repeat_rule, m.assignee_id, m.notes,
    (select coalesce(jsonb_agg(jsonb_set(e, '{done}', 'false'::jsonb)), '[]'::jsonb) from jsonb_array_elements(m.checklist) e), m.priority, m.remind_before, m.tags, m.duration_min, m.remind_travel)
  returning id into nid;
  return nid;
end;
$$;
grant execute on function public.complete_memory(uuid) to authenticated;

notify pgrst, 'reload schema';

-- ===== 0016_post_alerts.sql =====
-- Post (the mail app): instant new-mail alerts. Microsoft calls the `post-alerts` edge function when mail arrives; the function decides
-- whether it deserves an alert (people yes, newsletters no, your work hours respected) and sends a Web Push to the "Post alerts"
-- home-screen web app. These tables are server-only (no policies, no grants): the function uses the service role. Safe to run more than once.

-- One row per mailbox being watched. The refresh token is stored encrypted (AES-GCM, key in the function's secrets), never in clear text.
create table if not exists public.post_alert_accounts (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  label text not null default '',
  provider text not null default 'microsoft' check (provider in ('microsoft')),
  refresh_token_enc text not null,
  client_state text not null,
  subscription_id text,
  subscription_expires_at timestamptz,
  inbox_folder_id text,
  mode text not null default 'people' check (mode in ('people', 'all', 'vips', 'off')),
  vips text[] not null default '{}',
  quiet jsonb,
  tz text not null default 'Europe/Oslo',
  last_alert_at timestamptz,
  created_at timestamptz not null default now()
);

-- Messages already announced, so a retry from Microsoft never alerts twice.
create table if not exists public.post_alert_seen (
  account_id uuid not null references public.post_alert_accounts (id) on delete cascade,
  message_id text not null,
  seen_at timestamptz not null default now(),
  primary key (account_id, message_id)
);

-- The phones (home-screen web app) that receive alerts.
create table if not exists public.post_alert_devices (
  id uuid primary key default gen_random_uuid(),
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  lang text not null default 'en',
  badge integer not null default 0,
  created_at timestamptz not null default now()
);
-- The number on the icon: alerts delivered since that phone last opened Post. Safe on tables made before this column existed.
alter table public.post_alert_devices add column if not exists badge integer not null default 0;

alter table public.post_alert_accounts enable row level security;
alter table public.post_alert_seen enable row level security;
alter table public.post_alert_devices enable row level security;
revoke all on public.post_alert_accounts, public.post_alert_seen, public.post_alert_devices from anon, authenticated;

notify pgrst, 'reload schema';

-- ===== 0017_post_sessions.sql =====
-- Post: signing in without a shared key. Each phone or computer that signs in to a mailbox gets a secret; only its SHA-256 is stored here
-- (at most 8 per mailbox, the oldest drop off). Safe to run more than once.
alter table public.post_alert_accounts add column if not exists session_hashes text[] not null default '{}';

-- A finished sign-in waits here (sealed with the function's key) until the app that started it collects it. Removed when collected, or after 30 minutes.
create table if not exists public.post_signins (
  handle text primary key,
  result_enc text not null,
  created_at timestamptz not null default now()
);
alter table public.post_signins enable row level security;
revoke all on public.post_signins from anon, authenticated;

notify pgrst, 'reload schema';

-- ===== 0018_post_setup.sql =====
-- Post: setup that lives in the database, so nothing has to be typed into Supabase's Secrets page, and the 6-hourly renewal needs no Cron form.
-- Safe to run more than once.
--
--   select post_setup('<Application (client) ID from Azure>', 'you@outlook.com');   -- once
--   select post_allow('you@yourfirm.no');                                            -- to let another mailbox sign in
--
-- Server-only (no policies, no grants): only the edge function (service role) and you in the SQL editor can read it.
create table if not exists public.post_config (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);
alter table public.post_config enable row level security;
revoke all on public.post_config from anon, authenticated;

-- Why a mailbox is not getting new-mail alerts (Microsoft refused the subscription). The mailbox itself still works; the schedule tries again.
alter table public.post_alert_accounts add column if not exists sub_error text;
alter table public.post_alert_accounts add column if not exists sub_error_at timestamptz;

-- Lets one more mailbox sign in to Post's server.
create or replace function public.post_allow(p_email text) returns text
language plpgsql security definer set search_path = public as $$
declare
  em text := lower(trim(coalesce(p_email, '')));
  cur text;
begin
  if em !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'That does not look like an email address: %', p_email;
  end if;
  select value into cur from public.post_config where key = 'allowed_emails';
  if cur is null or cur = '' then
    cur := em;
  elsif not (em = any (string_to_array(cur, ','))) then
    cur := cur || ',' || em;
  end if;
  insert into public.post_config (key, value) values ('allowed_emails', cur)
    on conflict (key) do update set value = excluded.value, updated_at = now();
  return 'These mailboxes can sign in: ' || cur;
end $$;
revoke all on function public.post_allow(text) from public, anon, authenticated;

-- Stores your Microsoft Application (client) ID and, optionally, the first mailbox that may sign in.
create or replace function public.post_setup(p_client_id text, p_email text default null) returns text
language plpgsql security definer set search_path = public as $$
declare
  cid text := lower(trim(coalesce(p_client_id, '')));
  msg text;
begin
  if cid !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
    raise exception 'That does not look like an Application (client) ID. It is 36 characters, like 11111111-2222-3333-4444-555555555555.';
  end if;
  insert into public.post_config (key, value) values ('ms_client_id', cid)
    on conflict (key) do update set value = excluded.value, updated_at = now();
  if coalesce(trim(p_email), '') <> '' then
    msg := public.post_allow(p_email);
  else
    msg := coalesce((select 'These mailboxes can sign in: ' || value from public.post_config where key = 'allowed_emails'),
                    'No mailbox may sign in yet: run select post_allow(''you@outlook.com'');');
  end if;
  return 'Post is set up with client ID ' || cid || '. ' || msg;
end $$;
revoke all on function public.post_setup(text, text) from public, anon, authenticated;

-- Renewal without a Cron form. Microsoft's alert subscriptions last under 3 days for personal accounts, so every 6 hours the database asks the
-- function to renew whatever is about to lapse. The function writes its own address and a renewal key into post_config the first time it runs.
create or replace function public.post_cron_renew() returns void
language plpgsql security definer set search_path = public, extensions as $$
declare
  u text;
  k text;
begin
  select value into u from public.post_config where key = 'function_url';
  select value into k from public.post_config where key = 'cron_key';
  if u is null or k is null then return; end if;
  perform net.http_post(url := u, headers := jsonb_build_object('Content-Type', 'application/json', 'x-alerts-key', k), body := '{"op":"renew"}'::jsonb);
end $$;
revoke all on function public.post_cron_renew() from public, anon, authenticated;

-- Schedule it when this project has the pg_cron and pg_net extensions (Supabase does). If not, Post still renews alerts every time it is opened.
do $$
begin
  begin create extension if not exists pg_net; exception when others then null; end;
  begin create extension if not exists pg_cron; exception when others then null; end;
  perform cron.schedule('post-alerts-renew', '0 */6 * * *', 'select public.post_cron_renew()');
exception when others then
  raise notice 'Post: could not schedule the 6-hourly alert renewal (%). Alerts still renew whenever Post is opened.', sqlerrm;
end $$;

notify pgrst, 'reload schema';
