// GENERATED by scripts/sync-shared.mjs from apps/web/src. Do not edit here: change the web file and run the script.
// The calendar view: how many to-dos fall on each day, and what is on a chosen day. Pure, unit tested.
import type { Memory } from './types';
import { compareTodos } from './todoGroups.ts';

type Dated = Pick<Memory, 'due_on' | 'due_time' | 'pinned' | 'priority' | 'sort_order'>;

/** Open to-dos per day (ISO date), and the highest priority on that day (for a dot colour). */
export function countsByDay(list: readonly Dated[]): Map<string, { count: number; top: number }> {
  const out = new Map<string, { count: number; top: number }>();
  for (const m of list) {
    if (!m.due_on) continue;
    const c = out.get(m.due_on) ?? { count: 0, top: 0 };
    out.set(m.due_on, { count: c.count + 1, top: Math.max(c.top, m.priority ?? 0) });
  }
  return out;
}

/** What is on one day: timed things first by time, then the rest by pin and priority. */
export function agendaFor<T extends Dated>(list: readonly T[], iso: string): T[] {
  return list.filter((m) => m.due_on === iso).sort((a, b) => {
    const ta = a.due_time ?? '99:99', tb = b.due_time ?? '99:99';
    return ta.localeCompare(tb) || compareTodos(a, b);
  });
}
