// GENERATED by scripts/sync-shared.mjs from apps/web/src. Do not edit here: change the web file and run the script.
// Small round initials for who added or finished something. Same person, same colour, everywhere.
export function initials(name: string | null | undefined): string {
  const parts = (name ?? '').trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return '?';
  const first = Array.from(parts[0])[0];
  const last = parts.length > 1 ? Array.from(parts[parts.length - 1])[0] : '';
  return (first + last).toLocaleUpperCase();
}

const PALETTE = [200, 24, 262, 152, 336, 46]; // hues: blue, orange, purple, green, pink, yellow
export function avatarHue(id: string): number {
  let h = 0;
  for (const c of id) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  return PALETTE[h % PALETTE.length];
}
