// GENERATED by scripts/sync-shared.mjs from apps/web/src. Do not edit here: change the web file and run the script.
// Language-aware labels for places, schedules and the house template.
import houseNb from '../i18n/houseTasks.nb.json';
import type { Lang, T } from '../i18n/core';

export const CATEGORIES = ['pharmacy', 'hardware', 'grocery', 'paint', 'garden'] as const;
export type Category = (typeof CATEGORIES)[number];
export const isCategory = (v: unknown): v is Category => typeof v === 'string' && (CATEGORIES as readonly string[]).includes(v);

export const categoryName = (cat: string, t: T): string => (isCategory(cat) ? t(`cat.${cat}` as const) : cat);
export const shopName = (cat: string, t: T): string => (isCategory(cat) ? t(`shop.${cat}` as const) : cat);

/** "Any pharmacy" places are shown in the reader's language; specific places keep the name you gave them. */
export function placeLabel(p: { name: string; kind: string; category: string | null }, t: T): string {
  return p.kind === 'category' && p.category && isCategory(p.category) ? categoryName(p.category, t) : p.name;
}

const NB_TASKS = houseNb as Record<string, { title: string; notes: string }>;

/** Titles and notes of the starter house calendar exist in Norwegian; your own tasks are shown as you wrote them. */
export function taskTitle(task: { template_key?: string | null; title: string }, lang: Lang): string {
  return (lang === 'nb' && task.template_key && NB_TASKS[task.template_key]?.title) || task.title;
}
export function taskNotes(task: { template_key?: string | null; notes: string | null }, lang: Lang): string | null {
  return (lang === 'nb' && task.template_key && NB_TASKS[task.template_key]?.notes) || task.notes;
}
export const hasNorwegianTask = (key: string) => key in NB_TASKS;

const month = (m: number, t: T) => t(`month.${m}` as 'month.1');

type Sched = { schedule: string; interval_months?: number | null; window_start_month?: number | null; window_end_month?: number | null };

export function scheduleLabel(s: Sched, t: T): string {
  if (s.schedule === 'seasonal' && s.window_start_month && s.window_end_month) {
    const a = month(s.window_start_month, t), b = month(s.window_end_month, t);
    return s.window_start_month === s.window_end_month ? t('sched.yearMonth', { a }) : t('sched.yearSeason', { a, b });
  }
  const n = s.interval_months ?? 12;
  if (n % 12 === 0) return n === 12 ? t('sched.year') : t('sched.years', { n: n / 12 });
  return n === 1 ? t('sched.month') : t('sched.months', { n });
}

/** For AI "make this recurring" suggestions (the function sends the raw fields; the words are made here). */
export function recurringLabel(r: { schedule: 'interval' | 'seasonal'; interval_months?: number; window_start?: number; window_end?: number }, t: T): string {
  return scheduleLabel({ schedule: r.schedule, interval_months: r.interval_months, window_start_month: r.window_start, window_end_month: r.window_end }, t);
}
