// GENERATED by scripts/sync-shared.mjs from apps/web/src. Do not edit here: change the web file and run the script.
// Drive times and the road line for the route planner. The public OSRM server is used (free, no key, but no live traffic):
// when it cannot be reached the times are estimated from straight-line distance, and the screen says so.
import { distanceM, type LatLon } from './geo.ts';
import type { Matrix } from './route.ts';

const OSRM = 'https://router.project-osrm.org';
const coords = (pts: LatLon[]) => pts.map((p) => `${p.lon.toFixed(6)},${p.lat.toFixed(6)}`).join(';');

/** Seconds between every pair of points, roughly: straight line x 1.3 for the road, at 40 km/h. */
export function estimateMatrix(pts: LatLon[]): Matrix {
  return pts.map((a) => pts.map((b) => (a === b ? 0 : (distanceM(a, b) * 1.3) / (40_000 / 3600))));
}

async function getJson(url: string, ms = 9000): Promise<unknown> {
  const ctl = new AbortController();
  const timer = setTimeout(() => ctl.abort(), ms);
  try {
    const res = await fetch(url, { signal: ctl.signal });
    if (!res.ok) throw new Error(String(res.status));
    return await res.json();
  } finally { clearTimeout(timer); }
}

/** Fills holes (null = no road found) from the estimate, so one odd point never breaks the plan. */
export function mergeDurations(rows: (number | null)[][], pts: LatLon[]): Matrix {
  const est = estimateMatrix(pts);
  return pts.map((_, i) => pts.map((__, j) => (i === j ? 0 : rows?.[i]?.[j] ?? est[i][j])));
}

export async function driveMatrix(pts: LatLon[]): Promise<{ matrix: Matrix; estimated: boolean }> {
  if (pts.length < 2) return { matrix: estimateMatrix(pts), estimated: false };
  try {
    const j = (await getJson(`${OSRM}/table/v1/driving/${coords(pts)}?annotations=duration`)) as { code?: string; durations?: (number | null)[][] };
    if (j.code !== 'Ok' || !j.durations) throw new Error('no table');
    return { matrix: mergeDurations(j.durations, pts), estimated: false };
  } catch {
    return { matrix: estimateMatrix(pts), estimated: true };
  }
}

/** The road line through the points in order, for drawing on the map. Null when it cannot be fetched (the stops are still shown). */
export async function driveLine(pts: LatLon[]): Promise<[number, number][] | null> {
  if (pts.length < 2) return null;
  try {
    const j = (await getJson(`${OSRM}/route/v1/driving/${coords(pts)}?overview=full&geometries=geojson`)) as { code?: string; routes?: { geometry?: { coordinates?: [number, number][] } }[] };
    const line = j.code === 'Ok' ? j.routes?.[0]?.geometry?.coordinates : null;
    return line && line.length > 1 ? line : null;
  } catch { return null; }
}
