// GENERATED by scripts/sync-shared.mjs from apps/web/src. Do not edit here: change the web file and run the script.
// Day route planner: given the drive times between the places you want to visit, find the order that gets everything done
// soonest, counting time spent at each stop, rush-hour slowdowns by time of day, and "before 21:00" deadlines.
// Pure functions (the drive times are passed in), so they are unit tested with plain Node.
import type { LatLon } from './geo.ts';

/** Seconds of driving between nodes. Node 0 is the start, nodes 1..n are the stops, node n+1 is the end. */
export type Matrix = number[][];
export type Stop = { id: string; dwellMin: number; byMin?: number | null };

export type RoutePlan = {
  order: number[]; // stop indexes (0..n-1) in driving order
  arriveMin: number[]; // minutes since midnight at each stop, in the same order
  legMin: number[]; // drive minutes for each leg: start -> first, ..., last -> end (n + 1 legs), traffic included
  freeFlowMin: number; // the same drive with no traffic, for comparison
  driveMin: number;
  stopMin: number;
  endMin: number; // arrival at the end, minutes since midnight
  late: number[]; // minutes late per stop in order (0 = on time)
};

/** How much slower than free-flow driving is at this time. An estimate for Norwegian towns, not live traffic. */
export function trafficFactor(minuteOfDay: number, weekday: number): number {
  const m = minuteOfDay % 1440;
  const workday = weekday >= 1 && weekday <= 5;
  if (workday) {
    if (m >= 7 * 60 && m < 9 * 60) return 1.3;
    if (m >= 15 * 60 && m < 17 * 60 + 30) return 1.35;
    if (m >= 9 * 60 && m < 15 * 60) return 1.08;
    return 1;
  }
  return m >= 11 * 60 && m < 15 * 60 ? 1.1 : 1;
}

const DWELL: Record<string, number> = { grocery: 15, pharmacy: 10, hardware: 25, paint: 15, garden: 20 };
/** Minutes to plan at a stop: by kind of shop, a few more for every extra thing to do there. */
export function dwellMinutes(category: string | null | undefined, tasks: number): number {
  return Math.min(60, (DWELL[category ?? ''] ?? 10) + Math.max(0, tasks - 1) * 3);
}

const LATE_WEIGHT = 4; // a minute late counts like four minutes of driving

function evaluate(order: number[], matrix: Matrix, stops: Stop[], startMin: number, weekday: number) {
  const n = stops.length;
  let t = startMin, prev = 0, drive = 0, free = 0, stop = 0, lateSum = 0;
  const arrive: number[] = [], leg: number[] = [], late: number[] = [];
  for (const i of order) {
    const base = matrix[prev][i + 1] / 60;
    const d = base * trafficFactor(t, weekday);
    t += d; drive += d; free += base; leg.push(d);
    arrive.push(t);
    const l = stops[i].byMin != null ? Math.max(0, t - (stops[i].byMin as number)) : 0;
    late.push(l); lateSum += l;
    t += stops[i].dwellMin; stop += stops[i].dwellMin;
    prev = i + 1;
  }
  const base = matrix[prev][n + 1] / 60;
  const d = base * trafficFactor(t, weekday);
  t += d; drive += d; free += base; leg.push(d);
  return { cost: t - startMin + LATE_WEIGHT * lateSum, plan: { arriveMin: arrive, legMin: leg, freeFlowMin: free, driveMin: drive, stopMin: stop, endMin: t, late } };
}

/** Cost and details of driving the stops in exactly this order (to compare with the best order). */
export function evaluateOrder(order: number[], matrix: Matrix, stops: Stop[], startMin: number, weekday: number) {
  return evaluate(order, matrix, stops, startMin, weekday).plan;
}

function* permutations(items: number[]): Generator<number[]> {
  const a = [...items];
  const c = new Array(a.length).fill(0);
  yield [...a];
  let i = 0;
  while (i < a.length) {
    if (c[i] < i) {
      const k = i % 2 === 0 ? 0 : c[i];
      [a[k], a[i]] = [a[i], a[k]];
      yield [...a];
      c[i]++; i = 0;
    } else { c[i] = 0; i++; }
  }
}

/** The best order for the stops. Exact for up to 8 stops; a nearest-neighbour start improved by swaps beyond that. */
export function planRoute(matrix: Matrix, stops: Stop[], startMin: number, weekday: number): RoutePlan {
  const n = stops.length;
  const idx = Array.from({ length: n }, (_, i) => i);
  let best: { order: number[]; cost: number } | null = null;
  const consider = (order: number[]) => { const c = evaluate(order, matrix, stops, startMin, weekday).cost; if (!best || c < best.cost - 1e-9) best = { order, cost: c }; };

  if (n <= 8) {
    for (const p of permutations(idx)) consider(p);
  } else {
    const left = new Set(idx);
    const order: number[] = [];
    let prev = 0;
    while (left.size) {
      let pick = -1;
      for (const i of left) if (pick < 0 || matrix[prev][i + 1] < matrix[prev][pick + 1]) pick = i;
      order.push(pick); left.delete(pick); prev = pick + 1;
    }
    consider(order);
    let improved = true;
    while (improved) {
      improved = false;
      const cur = best!.order;
      for (let i = 0; i < n - 1 && !improved; i++) for (let j = i + 1; j < n && !improved; j++) {
        const rev = [...cur.slice(0, i), ...cur.slice(i, j + 1).reverse(), ...cur.slice(j + 1)];
        const before = best!.cost;
        consider(rev);
        if (best!.cost < before - 1e-9) improved = true;
        else { // moving one stop elsewhere
          const moved = [...cur.slice(0, i), ...cur.slice(i + 1)]; moved.splice(j, 0, cur[i]);
          consider(moved);
          if (best!.cost < before - 1e-9) improved = true;
        }
      }
    }
  }
  const order = best ? (best as { order: number[] }).order : idx;
  const e = evaluate(order, matrix, stops, startMin, weekday);
  const sumDrive = e.plan.driveMin;
  return { order, ...e.plan, driveMin: sumDrive };
}

// ---- hand-off to a navigation app (these use live traffic when you actually drive) ----
const ll = (p: LatLon) => `${p.lat.toFixed(6)},${p.lon.toFixed(6)}`;

/** Google Maps directions with stops in order (it takes up to 9 stops in between). */
export function googleRouteUrl(start: LatLon, stops: LatLon[], end: LatLon): string {
  const mid = stops.slice(0, 9);
  return `https://www.google.com/maps/dir/?api=1&travelmode=driving&origin=${ll(start)}&destination=${ll(end)}${mid.length ? `&waypoints=${mid.map(ll).join('%7C')}` : ''}`;
}

/** Apple Maps directions: "daddr=A+to:B+to:C" is its way of saying several stops. */
export function appleRouteUrl(start: LatLon, stops: LatLon[], end: LatLon): string {
  return `https://maps.apple.com/?dirflg=d&saddr=${ll(start)}&daddr=${[...stops, end].map(ll).join('+to:')}`;
}

export const fmtClock = (min: number) => { const m = Math.round(min) % 1440; return `${String(Math.floor(m / 60)).padStart(2, '0')}:${String(m % 60).padStart(2, '0')}`; };
