// GENERATED by scripts/sync-shared.mjs from apps/web/src. Do not edit here: change the web file and run the script.
// Swipe a row: right to finish, left to delete. Pure decision logic, unit tested.
export type SwipeAction = 'done' | 'delete' | null;

export const SWIPE_COMMIT = 96; // px past which letting go does the action

/** Row offset while dragging: follows the finger, with resistance past the commit point. */
export function swipeOffset(dx: number, commit = SWIPE_COMMIT): number {
  const a = Math.abs(dx);
  const eased = a <= commit ? a : commit + (a - commit) * 0.35;
  return Math.sign(dx) * Math.min(eased, commit * 1.6);
}

/** What letting go means. A quick flick counts even if short; a mostly vertical drag is a scroll, not a swipe. */
export function swipeResult(dx: number, dy: number, ms: number, commit = SWIPE_COMMIT): SwipeAction {
  if (Math.abs(dy) > Math.abs(dx) * 0.8) return null;
  const fast = ms < 250 && Math.abs(dx) > 48;
  if (Math.abs(dx) < commit && !fast) return null;
  return dx > 0 ? 'done' : 'delete';
}

/** Whether a drag has turned into a horizontal swipe yet (so the page can stop scrolling under it). */
export const isHorizontal = (dx: number, dy: number) => Math.abs(dx) > 10 && Math.abs(dx) > Math.abs(dy) * 1.4;
