// GENERATED by supabase/build-functions.mjs from functions/notify-partner/{index,logic}.ts. Do not edit by hand.
// Paste this whole file into the Supabase dashboard editor for a function named "notify-partner".
// Supabase Edge Function (Deno): tells the other household members' phones that you added to-dos (Web Push).
// Called by the web app with the user's JWT right after adding. Secrets: VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY (required),
// VAPID_SUBJECT (optional, default mailto:admin@example.com). SUPABASE_SERVICE_ROLE_KEY is provided by Supabase.
import { createClient } from 'npm:@supabase/supabase-js@2';

// ---- logic ----
// Pure logic for the `notify-partner` edge function: Web Push (RFC 8030) with payload encryption (RFC 8291, aes128gcm)
// and VAPID (RFC 8292), written on WebCrypto so it runs in Deno, browsers and Node. Unit tested (tests/notify-partner.test.ts).

const enc = new TextEncoder();

export function b64uToBytes(s: string): Uint8Array {
  const b = s.replace(/-/g, '+').replace(/_/g, '/') + '='.repeat((4 - (s.length % 4)) % 4);
  return Uint8Array.from(atob(b), (c) => c.charCodeAt(0));
}
export function bytesToB64u(bytes: Uint8Array): string {
  let s = '';
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
const concat = (...parts: Uint8Array[]) => {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let o = 0;
  for (const p of parts) { out.set(p, o); o += p.length; }
  return out;
};

async function hkdf(salt: Uint8Array, ikm: Uint8Array, info: Uint8Array, bytes: number): Promise<Uint8Array> {
  const key = await crypto.subtle.importKey('raw', ikm, 'HKDF', false, ['deriveBits']);
  return new Uint8Array(await crypto.subtle.deriveBits({ name: 'HKDF', hash: 'SHA-256', salt, info }, key, bytes * 8));
}

export type EncryptOptions = { salt?: Uint8Array; senderKeys?: CryptoKeyPair };

/** Encrypts `payload` for a push subscription. Returns the request body (header + one record). */
export async function encryptPayload(payload: Uint8Array, uaPublic: Uint8Array, authSecret: Uint8Array, opts: EncryptOptions = {}): Promise<Uint8Array> {
  if (uaPublic.length !== 65 || uaPublic[0] !== 4) throw new Error('bad subscription key');
  if (payload.length > 3993) throw new Error('payload too large'); // one 4096-byte record: 4096 - 16 tag - 1 delimiter - 86 header
  const salt = opts.salt ?? crypto.getRandomValues(new Uint8Array(16));
  const sender = opts.senderKeys ?? (await crypto.subtle.generateKey({ name: 'ECDH', namedCurve: 'P-256' }, true, ['deriveBits']));
  const asPublic = new Uint8Array(await crypto.subtle.exportKey('raw', sender.publicKey));
  const uaKey = await crypto.subtle.importKey('raw', uaPublic, { name: 'ECDH', namedCurve: 'P-256' }, false, []);
  const ecdh = new Uint8Array(await crypto.subtle.deriveBits({ name: 'ECDH', public: uaKey }, sender.privateKey, 256));
  const keyInfo = concat(enc.encode('WebPush: info\0'), uaPublic, asPublic);
  const ikm = await hkdf(authSecret, ecdh, keyInfo, 32);
  const cek = await hkdf(salt, ikm, enc.encode('Content-Encoding: aes128gcm\0'), 16);
  const nonce = await hkdf(salt, ikm, enc.encode('Content-Encoding: nonce\0'), 12);
  const aes = await crypto.subtle.importKey('raw', cek, 'AES-GCM', false, ['encrypt']);
  const cipher = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv: nonce }, aes, concat(payload, new Uint8Array([2]))));
  const rs = new Uint8Array([0, 0, 0x10, 0]); // 4096, big endian
  return concat(salt, rs, new Uint8Array([asPublic.length]), asPublic, cipher);
}

/** VAPID `Authorization` header value for a push endpoint. `privateD` is the 32-byte private scalar, `publicKey` the 65-byte point. */
export async function vapidAuthorization(endpoint: string, subject: string, publicKey: Uint8Array, privateD: Uint8Array, now = Date.now()): Promise<string> {
  const key = await crypto.subtle.importKey(
    'jwk',
    { kty: 'EC', crv: 'P-256', x: bytesToB64u(publicKey.slice(1, 33)), y: bytesToB64u(publicKey.slice(33, 65)), d: bytesToB64u(privateD) },
    { name: 'ECDSA', namedCurve: 'P-256' }, false, ['sign'],
  );
  const part = (o: unknown) => bytesToB64u(enc.encode(JSON.stringify(o)));
  const signingInput = `${part({ typ: 'JWT', alg: 'ES256' })}.${part({ aud: new URL(endpoint).origin, exp: Math.floor(now / 1000) + 12 * 3600, sub: subject })}`;
  const sig = new Uint8Array(await crypto.subtle.sign({ name: 'ECDSA', hash: 'SHA-256' }, key, enc.encode(signingInput)));
  return `vapid t=${signingInput}.${bytesToB64u(sig)}, k=${bytesToB64u(publicKey)}`;
}

export type PushSub = { endpoint: string; p256dh: string; auth: string };

/** Builds and sends one push. Resolves with the push service's HTTP status. */
export async function sendPush(sub: PushSub, payload: unknown, vapid: { subject: string; publicKey: string; privateKey: string }, fetchImpl: typeof fetch = fetch): Promise<number> {
  const body = await encryptPayload(enc.encode(JSON.stringify(payload)), b64uToBytes(sub.p256dh), b64uToBytes(sub.auth));
  const res = await fetchImpl(sub.endpoint, {
    method: 'POST',
    headers: {
      Authorization: await vapidAuthorization(sub.endpoint, vapid.subject, b64uToBytes(vapid.publicKey), b64uToBytes(vapid.privateKey)),
      'Content-Encoding': 'aes128gcm', 'Content-Type': 'application/octet-stream', TTL: '86400', Urgency: 'normal',
    },
    body,
  });
  return res.status;
}

/** 404 and 410 mean the subscription is gone for good: forget it. */
export const isGone = (status: number) => status === 404 || status === 410;

const clip = (s: string, n: number) => (s.length > n ? `${s.slice(0, n - 1).trimEnd()}…` : s);
const firstLine = (s: string) => s.split('\n')[0].trim();

/** The notification a partner sees, in their language. */
export function buildMessage(lang: 'en' | 'nb', who: string, bodies: string[], forYou = false): { title: string; body: string; url: string } {
  const name = clip(who.trim() || (lang === 'nb' ? 'Partneren din' : 'Your partner'), 30);
  const texts = bodies.map(firstLine).filter(Boolean);
  const verb = lang === 'nb' ? (forYou ? 'ga deg' : 'la til') : forYou ? 'gave you' : 'added';
  let body: string;
  if (bodies.length === 1) body = texts[0] ? `${name} ${verb}: ${clip(texts[0], 120)}` : (lang === 'nb' ? `${name} la til et bilde` : `${name} added a photo`);
  else body = lang === 'nb' ? `${name} ${verb} ${bodies.length} oppgaver` : `${name} ${verb} ${bodies.length} to-dos`;
  return { title: 'Home Memory', body, url: '/' };
}

// ---- handler ----
const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};
const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...cors, 'Content-Type': 'application/json' } });

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors });

  const publicKey = Deno.env.get('VAPID_PUBLIC_KEY');
  const privateKey = Deno.env.get('VAPID_PRIVATE_KEY');
  if (!publicKey || !privateKey) return json({ error: 'not_configured' }, 503);
  const vapid = { publicKey, privateKey, subject: Deno.env.get('VAPID_SUBJECT') ?? 'mailto:admin@example.com' };

  const auth = req.headers.get('Authorization');
  if (!auth) return json({ error: 'unauthorized' }, 401);
  const url = Deno.env.get('SUPABASE_URL')!;
  const asCaller = createClient(url, Deno.env.get('SUPABASE_ANON_KEY')!, { global: { headers: { Authorization: auth } } });
  const { data: who } = await asCaller.auth.getUser();
  const me = who?.user?.id;
  if (!me) return json({ error: 'unauthorized' }, 401);

  let ids: string[];
  try {
    const body = await req.json();
    ids = Array.isArray(body.memory_ids) ? body.memory_ids.filter((x: unknown) => typeof x === 'string').slice(0, 20) : [];
  } catch {
    return json({ error: 'bad_request' }, 400);
  }
  if (ids.length === 0) return json({ error: 'bad_request' }, 400);

  // Row level security decides what the caller may see; only their own fresh to-dos are announced.
  const { data: memories } = await asCaller.from('memories').select('id, household_id, body, author_id, created_at, assignee_id').in('id', ids);
  const fresh = (memories ?? []).filter((m) => m.author_id === me && Date.now() - new Date(m.created_at).getTime() < 10 * 60_000);
  if (fresh.length === 0) return json({ sent: 0, removed: 0 });
  const householdId = fresh[0].household_id;
  const mine = fresh.filter((m) => m.household_id === householdId);

  const admin = createClient(url, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
  const { data: members } = await admin.from('household_members').select('user_id, display_name').eq('household_id', householdId);
  const others = (members ?? []).filter((m) => m.user_id !== me).map((m) => m.user_id);
  if (others.length === 0) return json({ sent: 0, removed: 0 });
  const name = (members ?? []).find((m) => m.user_id === me)?.display_name ?? '';
  const { data: subs } = await admin.from('web_push_subscriptions').select('id, user_id, endpoint, p256dh, auth, lang').in('user_id', others);

  let sent = 0;
  const gone: string[] = [];
  await Promise.all((subs ?? []).map(async (s) => {
    // Something given to the writer themselves is not for the partner; something given to this person says so.
    const relevant = mine.filter((m) => !m.assignee_id || m.assignee_id === s.user_id);
    if (relevant.length === 0) return;
    try {
      const forYou = relevant.every((m) => m.assignee_id === s.user_id);
      const status = await sendPush(s, buildMessage(s.lang === 'nb' ? 'nb' : 'en', name, relevant.map((m) => m.body), forYou), vapid);
      if (status >= 200 && status < 300) sent++;
      else if (isGone(status)) gone.push(s.id);
    } catch (e) {
      console.error('push failed', e instanceof Error ? e.message : e);
    }
  }));
  if (gone.length) await admin.from('web_push_subscriptions').delete().in('id', gone);
  return json({ sent, removed: gone.length });
});

