// GENERATED by supabase/build-functions.mjs from functions/post-alerts/{index,logic}.ts. Do not edit by hand.
// Paste this whole file into the Supabase dashboard editor for a function named "post-alerts".
// Supabase Edge Function (Deno): instant new-mail alerts for the Post mail app. Microsoft calls it when mail arrives; it decides whether the mail
// deserves an alert and sends a Web Push to the Post web app. The Post app signs in through it (Microsoft sign-in, no shared key to type) and then
// proves which mailbox it belongs to with a session secret (header x-post-session).
// Setup: `select post_setup('<Application (client) ID>', 'you@outlook.com')` in the SQL editor stores your Microsoft client ID and the address that may
import { createClient } from 'npm:@supabase/supabase-js@2';

// ---- logic (notify-partner) ----
// Pure logic for the `notify-partner` edge function: Web Push (RFC 8030) with payload encryption (RFC 8291, aes128gcm)
// and VAPID (RFC 8292), written on WebCrypto so it runs in Deno, browsers and Node. Unit tested (tests/notify-partner.test.ts).

const enc = new TextEncoder();

export function b64uToBytes(s: string): Uint8Array {
  const b = s.replace(/-/g, '+').replace(/_/g, '/') + '='.repeat((4 - (s.length % 4)) % 4);
  return Uint8Array.from(atob(b), (c) => c.charCodeAt(0));
}
export function bytesToB64u(bytes: Uint8Array): string {
  let s = '';
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
const concat = (...parts: Uint8Array[]) => {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let o = 0;
  for (const p of parts) { out.set(p, o); o += p.length; }
  return out;
};

async function hkdf(salt: Uint8Array, ikm: Uint8Array, info: Uint8Array, bytes: number): Promise<Uint8Array> {
  const key = await crypto.subtle.importKey('raw', ikm, 'HKDF', false, ['deriveBits']);
  return new Uint8Array(await crypto.subtle.deriveBits({ name: 'HKDF', hash: 'SHA-256', salt, info }, key, bytes * 8));
}

export type EncryptOptions = { salt?: Uint8Array; senderKeys?: CryptoKeyPair };

/** Encrypts `payload` for a push subscription. Returns the request body (header + one record). */
export async function encryptPayload(payload: Uint8Array, uaPublic: Uint8Array, authSecret: Uint8Array, opts: EncryptOptions = {}): Promise<Uint8Array> {
  if (uaPublic.length !== 65 || uaPublic[0] !== 4) throw new Error('bad subscription key');
  if (payload.length > 3993) throw new Error('payload too large'); // one 4096-byte record: 4096 - 16 tag - 1 delimiter - 86 header
  const salt = opts.salt ?? crypto.getRandomValues(new Uint8Array(16));
  const sender = opts.senderKeys ?? (await crypto.subtle.generateKey({ name: 'ECDH', namedCurve: 'P-256' }, true, ['deriveBits']));
  const asPublic = new Uint8Array(await crypto.subtle.exportKey('raw', sender.publicKey));
  const uaKey = await crypto.subtle.importKey('raw', uaPublic, { name: 'ECDH', namedCurve: 'P-256' }, false, []);
  const ecdh = new Uint8Array(await crypto.subtle.deriveBits({ name: 'ECDH', public: uaKey }, sender.privateKey, 256));
  const keyInfo = concat(enc.encode('WebPush: info\0'), uaPublic, asPublic);
  const ikm = await hkdf(authSecret, ecdh, keyInfo, 32);
  const cek = await hkdf(salt, ikm, enc.encode('Content-Encoding: aes128gcm\0'), 16);
  const nonce = await hkdf(salt, ikm, enc.encode('Content-Encoding: nonce\0'), 12);
  const aes = await crypto.subtle.importKey('raw', cek, 'AES-GCM', false, ['encrypt']);
  const cipher = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv: nonce }, aes, concat(payload, new Uint8Array([2]))));
  const rs = new Uint8Array([0, 0, 0x10, 0]); // 4096, big endian
  return concat(salt, rs, new Uint8Array([asPublic.length]), asPublic, cipher);
}

/** VAPID `Authorization` header value for a push endpoint. `privateD` is the 32-byte private scalar, `publicKey` the 65-byte point. */
export async function vapidAuthorization(endpoint: string, subject: string, publicKey: Uint8Array, privateD: Uint8Array, now = Date.now()): Promise<string> {
  const key = await crypto.subtle.importKey(
    'jwk',
    { kty: 'EC', crv: 'P-256', x: bytesToB64u(publicKey.slice(1, 33)), y: bytesToB64u(publicKey.slice(33, 65)), d: bytesToB64u(privateD) },
    { name: 'ECDSA', namedCurve: 'P-256' }, false, ['sign'],
  );
  const part = (o: unknown) => bytesToB64u(enc.encode(JSON.stringify(o)));
  const signingInput = `${part({ typ: 'JWT', alg: 'ES256' })}.${part({ aud: new URL(endpoint).origin, exp: Math.floor(now / 1000) + 12 * 3600, sub: subject })}`;
  const sig = new Uint8Array(await crypto.subtle.sign({ name: 'ECDSA', hash: 'SHA-256' }, key, enc.encode(signingInput)));
  return `vapid t=${signingInput}.${bytesToB64u(sig)}, k=${bytesToB64u(publicKey)}`;
}

export type PushSub = { endpoint: string; p256dh: string; auth: string };

/** Builds and sends one push. Resolves with the push service's HTTP status. */
export async function sendPush(sub: PushSub, payload: unknown, vapid: { subject: string; publicKey: string; privateKey: string }, fetchImpl: typeof fetch = fetch): Promise<number> {
  const body = await encryptPayload(enc.encode(JSON.stringify(payload)), b64uToBytes(sub.p256dh), b64uToBytes(sub.auth));
  const res = await fetchImpl(sub.endpoint, {
    method: 'POST',
    headers: {
      Authorization: await vapidAuthorization(sub.endpoint, vapid.subject, b64uToBytes(vapid.publicKey), b64uToBytes(vapid.privateKey)),
      'Content-Encoding': 'aes128gcm', 'Content-Type': 'application/octet-stream', TTL: '86400', Urgency: 'normal',
    },
    body,
  });
  return res.status;
}

/** 404 and 410 mean the subscription is gone for good: forget it. */
export const isGone = (status: number) => status === 404 || status === 410;

const clip = (s: string, n: number) => (s.length > n ? `${s.slice(0, n - 1).trimEnd()}…` : s);
const firstLine = (s: string) => s.split('\n')[0].trim();

/** The notification a partner sees, in their language. */
export function buildMessage(lang: 'en' | 'nb', who: string, bodies: string[], forYou = false): { title: string; body: string; url: string } {
  const name = clip(who.trim() || (lang === 'nb' ? 'Partneren din' : 'Your partner'), 30);
  const texts = bodies.map(firstLine).filter(Boolean);
  const verb = lang === 'nb' ? (forYou ? 'ga deg' : 'la til') : forYou ? 'gave you' : 'added';
  let body: string;
  if (bodies.length === 1) body = texts[0] ? `${name} ${verb}: ${clip(texts[0], 120)}` : (lang === 'nb' ? `${name} la til et bilde` : `${name} added a photo`);
  else body = lang === 'nb' ? `${name} ${verb} ${bodies.length} oppgaver` : `${name} ${verb} ${bodies.length} to-dos`;
  return { title: 'Home Memory', body, url: '/' };
}

// ---- reminders at the due time (called every few minutes by a schedule, see docs/NOTIFICATIONS.md) ----

export type DueMemory = { id: string; household_id: string; body: string; due_on: string | null; due_time: string | null; assignee_id: string | null; remind_before?: number | null };

/** The date (YYYY-MM-DD) and minutes since midnight at `now` in a time zone, e.g. "Europe/Oslo". */
export function localNow(now: Date, tz: string): { date: string; minutes: number } {
  const parts = new Intl.DateTimeFormat('en-CA', { timeZone: tz, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(now);
  const get = (t: string) => parts.find((p) => p.type === t)?.value ?? '00';
  return { date: `${get('year')}-${get('month')}-${get('day')}`, minutes: Number(get('hour')) * 60 + Number(get('minute')) };
}

const wallMinutes = (date: string, hhmm: string) => Date.UTC(+date.slice(0, 4), +date.slice(5, 7) - 1, +date.slice(8, 10), +hhmm.slice(0, 2), +hhmm.slice(3, 5)) / 60_000;

/** To-dos whose time has come: the reminder moment (the due time minus "remind me before") has passed, but by less than `windowMin`, so a missed run still catches up. */
export function dueNow(list: DueMemory[], now: Date, tz: string, windowMin = 30): DueMemory[] {
  const { date, minutes } = localNow(now, tz);
  const nowMin = wallMinutes(date, '00:00') + minutes;
  return list.filter((m) => {
    if (!m.due_on || !m.due_time || !/^\d\d:\d\d/.test(m.due_time)) return false;
    const at = wallMinutes(m.due_on, m.due_time) - (m.remind_before ?? 0);
    return nowMin >= at && nowMin < at + windowMin;
  });
}

/** Who hears about a due to-do: the person it is for, or everyone in the household when it is for anyone. */
export const recipientsFor = (m: Pick<DueMemory, 'assignee_id'>, memberIds: string[]): string[] =>
  m.assignee_id && memberIds.includes(m.assignee_id) ? [m.assignee_id] : memberIds;

/** "30 min", "2 h", "1 day" in the reader's language. */
export function leadText(lang: 'en' | 'nb', minutes: number): string {
  if (minutes % 1440 === 0) { const d = minutes / 1440; return lang === 'nb' ? `${d} ${d === 1 ? 'dag' : 'dager'}` : `${d} ${d === 1 ? 'day' : 'days'}`; }
  if (minutes % 60 === 0) return lang === 'nb' ? `${minutes / 60} t` : `${minutes / 60} h`;
  return `${minutes} min`;
}

export function buildDueMessage(lang: 'en' | 'nb', bodies: string[], lead = 0): { title: string; body: string; url: string } {
  const texts = bodies.map(firstLine).filter(Boolean);
  const when = lead > 0 ? (lang === 'nb' ? `Om ${leadText(lang, lead)}` : `In ${leadText(lang, lead)}`) : lang === 'nb' ? 'N\u00e5' : 'Now';
  const body = bodies.length === 1 && texts[0]
    ? `${when}: ${clip(texts[0], 120)}`
    : lang === 'nb' ? `${bodies.length} oppgaver skal gj\u00f8res ${lead > 0 ? `om ${leadText(lang, lead)}` : 'n\u00e5'}` : `${bodies.length} to-dos are due ${lead > 0 ? `in ${leadText(lang, lead)}` : 'now'}`;
  return { title: 'Home Memory', body, url: '/' };
}

// ---- shared with the Post app (classify) ----
// GENERATED by supabase/build-functions.mjs from apps/web/src/post/core/classify.ts. Do not edit by hand: the Post app and its alert server must sort mail the same way.
export type Kind = 'person' | 'transaction' | 'update' | 'promo';

// Which kind of mail is this, and WHY. Four kinds, like the tabs in iOS Mail: a person (Primary), a transaction (receipts, deliveries,
// bookings, security codes), an update (notifications, social, newsletters) or a promotion (marketing). The reasons are shown to the user
// ("why is this here?") and can always be overridden for one sender or for a whole company, because wrong guesses that hide mail are the
// thing people hate most in Apple Mail's categories. Nothing here ever hides a message: a kind only labels it and picks its tab, and
// when the evidence is thin the message stays with the people (a missed mail is worse than an extra one).
//
// The verdict is a pure function of what is saved about a message (sender, subject, preview, header marks) and of what Post has learned
// (your own choices, the people you have written to, your VIPs). That is what lets every rule change apply to old mail at once, without
// asking Outlook again.
//
// The alert server (the Supabase function post-alerts) sorts new mail with a copy of this very file, so the icon number follows the Primary
// tab: supabase/functions/post-alerts/classify.ts and the single-file function are generated from it. After changing this file run
// `npm run build:functions` in supabase/ and commit what it writes (the supabase tests fail while the copies are stale).

/** Bump when the saved header marks change meaning, so every message is asked about again. Rule changes never need a bump. */
export const CLASSIFIER_VERSION = 2;

export interface ClassifyInput {
  fromAddress: string;
  fromName?: string;
  subject: string;
  preview?: string;
  /** Marks from signalsFromHeaders. Undefined while the headers have not been read. */
  signals?: string[];
}

export interface ClassifyContext {
  /** The user's own choices: "anna@x.no" for one sender, "@x.no" for a whole company. */
  overrides?: Record<string, Kind>;
  /** Addresses the user has written to. */
  known?: ReadonlySet<string>;
  /** Addresses on the VIP list. */
  vips?: ReadonlySet<string>;
}

// ---- reading the headers ----------------------------------------------------------------------------------------------------------

// Headers that mailing services add. Receipts sent through the same services carry them too, so on their own they only count as weak evidence.
const ESP_HEADER = /^(x-mailgun|x-sg-|x-sendgrid|x-mailchimp|x-mc-|x-mandrill|x-campaign|x-cmail|x-ses-|x-postmark|x-pm-|x-sparkpost|x-msys|x-mailjet|x-mj-|x-sib-|x-brevo|x-klaviyo|x-hubspot|x-hs-|x-marketo|x-mkto|x-pardot|x-elq|x-emarsys|x-vero|x-customerio|x-iterable|x-braze|x-ctct|x-newsletter|x-bulk|feedback-id$)/i;
const ESP_MAILER = /(mailchimp|sendgrid|mailgun|mandrill|sendinblue|brevo|klaviyo|hubspot|marketo|campaign ?monitor|constant ?contact|salesforce|exacttarget|postmark|sparkpost|mailjet|braze|iterable|customer\.io|emarsys|dotdigital|activecampaign|convertkit|substack|beehiiv|cordial|listrak|responsys|eloqua|pardot)/i;

/**
 * Boils the headers down to a few short marks that are saved with the message:
 *   unsub (List-Unsubscribe), oneclick (List-Unsubscribe-Post), list (List-Id), bulk (Precedence: bulk/list/junk), bcl (Microsoft's own
 *   "bulk sender" level), auto (sent automatically), esp (sent through a mailing service), thread (a reply in a conversation).
 */
export function signalsFromHeaders(headers: { name: string; value: string }[] | undefined): string[] {
  const first = new Map<string, string>();
  for (const x of headers ?? []) {
    const n = String(x?.name ?? '').trim().toLowerCase();
    if (n && !first.has(n)) first.set(n, String(x.value ?? ''));
  }
  const out: string[] = [];
  const add = (t: string) => { if (!out.includes(t)) out.push(t); };
  const get = (n: string) => (first.get(n) ?? '').trim();

  if (get('list-unsubscribe')) add('unsub');
  if (first.has('list-unsubscribe-post')) add('oneclick');
  if (get('list-id')) add('list');
  const precedence = get('precedence');
  if (/^(bulk|list|junk)$/i.test(precedence)) add('bulk');
  if (/^auto[-_ ]?reply$/i.test(precedence)) add('auto');
  const autoSubmitted = get('auto-submitted').toLowerCase();
  if (autoSubmitted && autoSubmitted !== 'no') add('auto');
  if (first.has('x-auto-response-suppress') || first.has('x-autoreply') || first.has('x-autorespond')) add('auto');
  const bcl = /\bBCL:(\d+)/i.exec(get('x-microsoft-antispam'));
  if (bcl && Number(bcl[1]) >= 1) add('bcl');
  for (const n of first.keys()) if (ESP_HEADER.test(n)) { add('esp'); break; }
  if (ESP_MAILER.test(get('x-mailer')) || ESP_MAILER.test(get('x-mailer-sw'))) add('esp');
  if (first.has('in-reply-to') || first.has('references')) add('thread');
  return out;
}

// ---- words people (and robots) use, in Norwegian and English -----------------------------------------------------------------------

const NOT_BEFORE = '(?<![\\p{L}\\p{N}])';
const NOT_AFTER = '(?![\\p{L}\\p{N}])';
/** A whole word or phrase. Letters include æ ø å, so "sale" does not match inside "resale" and "salg" not inside "usalg". */
const word = (src: string) => new RegExp(`${NOT_BEFORE}(?:${src})${NOT_AFTER}`, 'iu');
/** A piece of a word. Norwegian builds long compounds ("sommertilbud", "ordrebekreftelse"), so these may start or end anywhere. */
const piece = (src: string) => new RegExp(src, 'iu');
const any = (res: RegExp[], s: string) => res.some((r) => r.test(s));

// Plainly a receipt or an invoice, whoever sends it.
const RECEIPT_SURE = [piece('kvittering|faktura|ordrebekreftelse|bestillingsbekreftelse|betalingsbekreftelse|kontoutskrift'), word('receipt|invoice|order confirmation|payment confirmation|purchase confirmation|booking confirmation|e-?ticket')];
const RECEIPT = [...RECEIPT_SURE, piece('ordre ?(nr|nummer)|ordrenr|takk for (din |ditt )?(bestilling|ordre|kjøp|betaling)|betaling (mottatt|gjennomført|mislyktes)|regning|abonnement'), word('your order|order #?\\d+|payment (received|successful|failed|reminder)|thank you for (your )?(order|purchase|payment)|statement|subscription|renewal|renewed|billing')];
// A parcel, a booking, an appointment, a trip.
const DELIVERY = [piece('levert|forsendelse|leveranse|utlevering|hentes|henting|sporing|pakken din|din pakke|(bestilling|ordre).{0,40}(sendt|mottatt|klar|bekreftet|levert)|timeavtale|timebestilling|din time|avtalen din|reservasjon|billett|boarding|innsjekking|avreise|avgang'), word('pakke|pakken|sendingen( din)?'), word('delivered|shipped|shipment|out for delivery|parcel|package|tracking|appointment|booking|reservation|check-?in|boarding pass|flight|itinerary|pickup|ready for collection|your trip|your ride')];
// Codes and sign-in alerts.
const SECURITY = [piece('bekreftelseskode|engangskode|engangspassord|sikkerhetskode|verifiseringskode|påloggingskode|passord|pålogging|innlogging|bekreft (din |ditt )?(e-?post|konto|identitet)'), word('verification( code)?|verify (your|this)|one-?time|security (alert|code|info|notice)|sign-?in|log-?in|login|2fa|two-?step|two-?factor|password|your code|confirm your (email|account|identity)|unusual (activity|sign-?in)|new device|account recovery')];
// Codes that nobody types to a friend. (The broader SECURITY list also has "password", which a person might well write.)
const SECURITY_SURE = [piece('engangskode|engangspassord|bekreftelseskode|verifiseringskode|sikkerhetskode|påloggingskode'), word('verification code|security code|one-?time (code|password|passcode)|login code|sign-?in code|your code is|your code:')];
// Selling things. PROMO_SURE is specific enough to trust even on mail that looks personal; PROMO is the broad list, used only once
// something else says the mail was sent in bulk or by a robot (a person writing "tilbud" about a car must not land in Promotions).
const PROMO_SURE = [piece('\\d+\\s?%|%\\s?(off|rabatt|avslag)|black ?friday|cyber ?monday|kupong|gavekort|gratis frakt|fri frakt|(sommer|vinter|høst|vår|jule|lager|nett|påske|helge)salg|utsalg'), word('coupon|voucher|promo code|rabattkode|sale|free shipping|up to \\d+%')];
const PROMO = [...PROMO_SURE, piece('rabatt|kampanje|tilbud|spar |bonus|poeng|gratis|medlem(s)?(fordel|tilbud|pris|klubb)|din kode|bruk koden|eksklusiv|begrenset|siste (sjanse|dag|frist)|bare i dag|kun i dag|handle nå|ny kolleksjon'), word('deals?|offers?|discounts?|save|limited( time| offer)?|last chance|ends (today|tonight|soon|tomorrow|sunday|midnight)|don.t miss|miss out|exclusive|shop now|new (arrivals?|collection|in)|bestsellers?|rewards?|points|members?-only')];
// Editorial mail and social or work notifications.
const NEWS = [word('newsletter|digest|weekly|monthly|daily|briefing|round-?up|what.s new|this week|your week|bulletin|edition|issue #?\\d+|podcast|episode'), piece('nyhetsbrev|ukens|månedens|dagens|ukesoppsummering|siste nytt|nytt fra|oppdatering|nyheter|magasin')];
const SOCIAL = [word('liked|commented|mentioned|invited you|connection request|followed you|new follower|tagged you|sent you a message|friend request|viewed your profile|replied to'), piece('ny melding|nytt innlegg|har kommentert|har invitert deg|følger deg')];
const PLATFORM = /(^|\.)(facebookmail|facebook|linkedin|github|gitlab|twitter|x|instagram|reddit|redditmail|slack|notion|medium|substack|discord|pinterest|quora|trello|atlassian|figma|zoom|dropbox|asana|miro|airtable|calendly|eventbrite|meetup|youtube|tiktok|snapchat|twitch|stackoverflow|stackexchange)\.(com|net|so|us|org|io)$/i;

// Sender names. The strong list is mail no person wrote by hand; the weak list is a role mailbox that people also answer from.
const ROBOT_PREFIX = /^(no[-_.]?reply|do[-_.]?not[-_.]?reply|donotreply|mailer-daemon|postmaster|bounces?)/i;
const ROBOT = /^(notifications?|notify|newsletters?|nyhetsbrev|marketing|campaigns?|kampanje|offers?|deals?|tilbud|promo(tions?)?|alerts?|varsel|automated|auto|system)([-_.][\w.-]*)?$/i;
const ROLE = /^(info|post|mail|hello|hei|hi|team|service|kundeservice|kundesenter|support|help|contact|kontakt|sales|salg|orders?|ordre|billing|faktura|invoice|receipts?|kvittering|booking|bestilling|bestillinger|reservasjon|tickets?|billett(er)?|news|updates?|account|accounts|konto|security|sikkerhet|admin|shop|store|butikk|nettbutikk|webshop|medlem|members?|club|klubb|bank)([-_.][\w.-]*)?$/i;

const REPLY = /^\s*(re|sv|svar|aw|vs|vb|fw|fwd)\s*:/i;
const BOUNCE_SUBJECT = /^\s*(undeliverable|returned mail|mail delivery (failed|subsystem)|delivery (status )?notification|delivery has failed|kunne ikke leveres|ikke levert)/i;

// ---- companies and free mail providers -------------------------------------------------------------------------------------------

/** "mail.elkjop.no" gives "elkjop.no"; "shop.example.co.uk" gives "example.co.uk". Takes an address or a domain. */
export function orgDomain(addressOrDomain: string): string {
  const d = (addressOrDomain.includes('@') ? addressOrDomain.split('@')[1] : addressOrDomain).toLowerCase().trim();
  const parts = d.split('.').filter(Boolean);
  if (parts.length <= 2) return parts.join('.');
  const sld = parts[parts.length - 2];
  const tld = parts[parts.length - 1];
  const keep = tld.length === 2 && ['co', 'com', 'org', 'net', 'gov', 'ac', 'edu', 'ltd', 'plc'].includes(sld) ? 3 : 2;
  return parts.slice(-keep).join('.');
}

/** Everyone shares these, so "everything from gmail.com" is never a useful rule. */
const FREEMAIL = new Set(['gmail.com', 'googlemail.com', 'outlook.com', 'hotmail.com', 'hotmail.no', 'hotmail.co.uk', 'live.com', 'live.no', 'msn.com', 'icloud.com', 'me.com', 'mac.com', 'yahoo.com', 'yahoo.no', 'online.no', 'getmail.no', 'start.no', 'c2i.net', 'protonmail.com', 'proton.me', 'gmx.com', 'aol.com', 'yandex.com', 'mail.com', 'tutanota.com']);
export const isFreemail = (addressOrDomain: string) => FREEMAIL.has(orgDomain(addressOrDomain));

/** The saved choice that decides this sender: the sender's own, else the one for their company. */
export function ruleFor(overrides: Record<string, Kind> | undefined, address: string): { key: string; kind: Kind; scope: 'sender' | 'company' } | null {
  if (!overrides) return null;
  const addr = address.trim().toLowerCase();
  if (overrides[addr]) return { key: addr, kind: overrides[addr], scope: 'sender' };
  const labels = (addr.split('@')[1] ?? '').split('.').filter(Boolean);
  for (let i = 0; i <= labels.length - 2; i++) {
    const key = `@${labels.slice(i).join('.')}`;
    if (overrides[key]) return { key, kind: overrides[key], scope: 'company' };
  }
  return null;
}

/**
 * A short fingerprint of the saved choices, so a phone and the alert server can tell whether they hold the same ones without sending them
 * (the same text on both sides: the server's copy of this file is generated from this one).
 */
export function rulesDigest(overrides: Record<string, Kind> | undefined): string {
  const lines = Object.entries(overrides ?? {}).map(([who, kind]) => `${who.trim().toLowerCase()}=${kind}`).sort();
  let h = 0x811c9dc5; // FNV-1a over the code points of every line
  for (const ch of lines.join('\n')) { h ^= ch.codePointAt(0)!; h = Math.imul(h, 0x01000193) >>> 0; }
  return `${lines.length}:${h.toString(16)}`;
}

/** The shape of a saved choice an alert server can hold: "anna@x.no" for one sender, "@x.no" for a company. */
export const isRuleKey = (who: string): boolean => who.length <= 120 && /^(@[^\s@]+|[^\s@]+@[^\s@]+)$/.test(who);

/**
 * The saved choices the phone tells the alert server. A key of any other shape (the internal address an Exchange server gives a colleague, say)
 * stays on the phone: one such key must not make the server refuse all the others.
 */
export function sendableRules(overrides: Record<string, Kind> | undefined): Record<string, Kind> {
  const out: Record<string, Kind> = {};
  for (const [who, kind] of Object.entries(overrides ?? {})) { const key = who.trim().toLowerCase(); if (isRuleKey(key)) out[key] = kind; }
  return out;
}

const flat = (t: string) => t.toLowerCase().replace(/æ/g, 'ae').replace(/ø/g, 'o').replace(/å/g, 'a').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]/g, '');

/** A company writing under its own name ("Elkjøp Norge" from elkjop.no). "Ola Hansen" from hansen.no is a person: the first word has to be the company. */
function isBrandSender(fromName: string | undefined, domain: string): boolean {
  if (!fromName || !domain || isFreemail(domain)) return false;
  const org = flat(orgDomain(domain).split('.')[0]);
  const first = flat(fromName.trim().split(/\s+/)[0] ?? '');
  return org.length >= 3 && first.startsWith(org);
}

// ---- the verdict -----------------------------------------------------------------------------------------------------------------------

const R = {
  sender: 'You moved this sender here',
  vip: 'On your VIP list',
  bounce: 'A problem delivering mail you sent',
  known: 'You have written to this address',
  thread: 'Part of a conversation',
  unsub: 'Has an unsubscribe link',
  list: 'Sent to a mailing list',
  bulk: 'Sent as bulk mail, not to you personally',
  mailer: 'Sent through a mailing service',
  auto: 'Sent automatically',
  robot: 'Sent from a no-reply style address',
  receipt: 'Looks like a receipt or an invoice',
  delivery: 'Looks like a delivery, booking or appointment',
  security: 'Looks like a security code or sign-in alert',
  promo: 'Sounds like an offer or a sale',
  news: 'Looks like a newsletter or news',
  platform: 'From a social or work app',
  person: 'Written by a person',
};

/** A one-time code or a sign-in alert: it sits in Transactions, yet it cannot wait for you to open Post (the alert server lets these through). */
export function isSecurityMail(v: { kind: Kind; why: string[] }): boolean {
  return v.kind === 'transaction' && v.why.includes(R.security);
}

export function classify(m: ClassifyInput, ctx: ClassifyContext = {}): { kind: Kind; why: string[] } {
  const addr = (m.fromAddress ?? '').trim().toLowerCase();
  const [localFull = '', domain = ''] = addr.split('@');
  const local = localFull.split('+')[0];
  const subject = m.subject ?? '';
  const text = `${subject} ${m.preview ?? ''}`;

  // 1. What the person decided always wins, then the VIP list.
  const rule = ruleFor(ctx.overrides, addr);
  if (rule) return { kind: rule.kind, why: [rule.scope === 'sender' ? R.sender : `You moved everything from ${rule.key.slice(1)} here`] };
  if (addr && ctx.vips?.has(addr)) return { kind: 'person', why: [R.vip] };

  // 2. Facts from the headers (undefined until they have been read).
  const sig = m.signals ?? [];
  const has = (t: string) => sig.includes(t);
  const bulk = has('unsub') || has('list') || has('bulk') || has('bcl');
  const auto = has('auto');
  const mailer = has('esp');
  const robot = ROBOT_PREFIX.test(local) || ROBOT.test(local);
  const role = ROLE.test(local) || isBrandSender(m.fromName, domain);
  const thread = REPLY.test(subject) || has('thread');
  const known = !!addr && !!ctx.known?.has(addr);

  const why: string[] = [];
  if (has('unsub')) why.push(R.unsub);
  if (has('list')) why.push(R.list);
  if (has('bulk') || has('bcl')) why.push(R.bulk);
  if (mailer && !bulk) why.push(R.mailer);
  if (auto) why.push(R.auto);
  if (robot) why.push(R.robot);

  // 3. Mail that needs the person's attention whatever it looks like: a bounce of something they sent.
  if (/^(mailer-daemon|postmaster)$/i.test(local) || BOUNCE_SUBJECT.test(subject)) return { kind: 'person', why: [R.bounce] };

  const cues = {
    receiptSure: any(RECEIPT_SURE, text), receipt: any(RECEIPT, text), promoSure: any(PROMO_SURE, text), promo: any(PROMO, text),
    security: any(SECURITY, text), delivery: any(DELIVERY, text), news: any(NEWS, text), platform: PLATFORM.test(domain) || any(SOCIAL, text),
  };
  const anyCue = cues.receipt || cues.promo || cues.security || cues.delivery || cues.news || cues.platform;
  const byWords = (): { kind: Kind; why: string[] } | null => {
    const v = verdictFromWords(cues);
    return v ? { kind: v.kind, why: [...why, v.reason] } : null;
  };

  // 4. People: someone you have written to, or a reply in a conversation, unless the mail itself says it was sent in bulk.
  if (known && !bulk && !auto && !((robot || role) && (cues.receipt || cues.delivery || cues.security || cues.promo))) return { kind: 'person', why: [R.known] };
  if (thread && !bulk && !auto && !robot) return { kind: 'person', why: [R.thread] };

  // 5. Sent in bulk (an unsubscribe link, a mailing list, bulk headers): never a person.
  if (bulk) {
    const v = byWords();
    if (v) return v;
    // A mailing list without an unsubscribe link is a group or a discussion, not an advertisement.
    if (has('list') && !has('unsub')) return { kind: 'update', why };
    return { kind: 'promo', why };
  }

  // 6. Sent by a robot: automatic, a no-reply address, or a mailing service plus one more hint (a role mailbox, or words that say what it is).
  if (auto || robot || (mailer && (role || anyCue)) || (role && (cues.receipt || cues.delivery || cues.security || cues.promo))) {
    return byWords() ?? { kind: 'update', why: why.length ? why : [R.auto] };
  }

  // 7. Nothing says "robot", but the subject plainly is a receipt or an offer (a person rarely writes these).
  if (any(RECEIPT_SURE, subject)) return { kind: 'transaction', why: [R.receipt] };
  if (any(SECURITY_SURE, subject)) return { kind: 'transaction', why: [R.security] };
  if (any(PROMO_SURE, subject)) return { kind: 'promo', why: [R.promo] };

  return { kind: 'person', why: [R.person] };
}

/** What the words alone say, strongest first: a receipt or a sale is unmistakable; a code beats a mere offer; an offer beats a mention of delivery. */
function verdictFromWords(c: { receiptSure: boolean; receipt: boolean; promoSure: boolean; promo: boolean; security: boolean; delivery: boolean; news: boolean; platform: boolean }): { kind: Kind; reason: string } | null {
  if (c.receiptSure) return { kind: 'transaction', reason: R.receipt };
  if (c.promoSure) return { kind: 'promo', reason: R.promo };
  if (c.security) return { kind: 'transaction', reason: R.security };
  if ((c.delivery || c.receipt) && !c.promo) return { kind: 'transaction', reason: c.delivery ? R.delivery : R.receipt };
  if (c.promo) return { kind: 'promo', reason: R.promo };
  if (c.platform) return { kind: 'update', reason: R.platform };
  if (c.news) return { kind: 'update', reason: R.news };
  return null;
}

// ---- logic ----
// Pure logic for the `post-alerts` edge function: Microsoft Graph change notifications for new mail, the decision "does this deserve
// an alert", the alert text, token encryption, and the few Graph calls (with an injected fetch so they are unit tested).
// Tested in tests/post-alerts.test.ts. Names here start with "alert"/"graph" so this file can be bundled with notify-partner's logic.
// classify.ts next to it is the Post app's own sorting (generated by build-functions.mjs): the icon number follows the same Primary tab the app shows.

export type AlertMode = 'people' | 'all' | 'vips' | 'off';
/** Alerts are allowed only inside this window. days: 1 = Monday ... 7 = Sunday. */
export type AlertQuiet = { days: number[]; from: string; to: string };
export type AlertAccount = {
  id: string; email: string; label: string; mode: AlertMode; vips: string[]; quiet: AlertQuiet | null; tz: string; inbox_folder_id?: string | null;
};
export type GraphMessage = {
  id: string; subject?: string; bodyPreview?: string; isRead?: boolean; parentFolderId?: string; inferenceClassification?: string;
  from?: { emailAddress?: { name?: string; address?: string } };
  internetMessageHeaders?: { name: string; value: string }[];
};

// ---- the webhook ----

/** Graph proves it owns the subscription by sending ?validationToken=...; we must echo it back as plain text within 10 seconds. */
export function alertValidationToken(url: string): string | null {
  const t = new URL(url).searchParams.get('validationToken');
  return t && t.length > 0 ? t : null;
}

export type AlertNotification = { subscriptionId: string; messageId: string; changeType: string };
export type AlertLifecycle = { subscriptionId: string; event: string };

const lastSegment = (s: string) => decodeURIComponent(s.split('/').filter(Boolean).pop() ?? '');

/** The new-mail notifications in a webhook body whose clientState matches the one we set. Anything else is ignored (it did not come from our subscription). */
export function alertParseNotifications(body: unknown, clientStates: Map<string, string>): AlertNotification[] {
  const list = (body as { value?: unknown[] } | null)?.value;
  if (!Array.isArray(list)) return [];
  const out: AlertNotification[] = [];
  for (const n of list as Record<string, any>[]) {
    const sub = String(n?.subscriptionId ?? '');
    const expected = clientStates.get(sub);
    if (!expected || n?.clientState !== expected || n?.lifecycleEvent) continue;
    const id = n?.resourceData?.id ?? (typeof n?.resource === 'string' ? lastSegment(n.resource) : '');
    if (!id) continue;
    out.push({ subscriptionId: sub, messageId: String(id), changeType: String(n?.changeType ?? '') });
  }
  return out;
}

export function alertParseLifecycle(body: unknown, clientStates: Map<string, string>): AlertLifecycle[] {
  const list = (body as { value?: unknown[] } | null)?.value;
  if (!Array.isArray(list)) return [];
  return (list as Record<string, any>[])
    .filter((n) => n?.lifecycleEvent && clientStates.get(String(n?.subscriptionId)) === n?.clientState)
    .map((n) => ({ subscriptionId: String(n.subscriptionId), event: String(n.lifecycleEvent) }));
}

// ---- does it deserve an alert? ----

const BULK_SENDER = /^(no[-_.]?reply|do[-_.]?not[-_.]?reply|donotreply|notifications?|newsletters?|mailer-daemon|postmaster|bounces?|marketing)$/i;

function alertHeaders(m: GraphMessage): Record<string, string> {
  const out: Record<string, string> = {};
  for (const h of m.internetMessageHeaders ?? []) if (h?.name && !(h.name.toLowerCase() in out)) out[h.name.toLowerCase()] = String(h.value ?? '');
  return out;
}

/** Bulk mail (newsletters, notifications, receipts-by-robot) versus a person writing to you.
 *  Outlook's own Focused/Other is deliberately NOT used to stay quiet: a missed alert is worse than an extra one, so when unsure we alert. */
export function alertKind(m: GraphMessage): 'person' | 'bulk' {
  const h = alertHeaders(m);
  if (h['list-unsubscribe'] || h['list-id']) return 'bulk';
  if (/^(bulk|list|junk)$/i.test((h['precedence'] ?? '').trim())) return 'bulk';
  const auto = (h['auto-submitted'] ?? '').trim().toLowerCase();
  if (auto && auto !== 'no') return 'bulk';
  const local = (m.from?.emailAddress?.address ?? '').split('@')[0];
  if (BULK_SENDER.test(local)) return 'bulk';
  return 'person';
}

const alertMinutes = (hhmm: string) => Number(hhmm.slice(0, 2)) * 60 + Number(hhmm.slice(3, 5));

/** Weekday (1 = Monday ... 7 = Sunday) and minutes since midnight at `now` in a time zone. */
export function alertLocal(now: Date, tz: string): { day: number; minutes: number } {
  const wd = new Intl.DateTimeFormat('en-US', { timeZone: tz, weekday: 'short' }).format(now);
  const day = ({ Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6, Sun: 7 } as Record<string, number>)[wd] ?? 1;
  return { day, minutes: localNow(now, tz).minutes };
}

export function alertWithinWindow(q: AlertQuiet | null, now: Date, tz: string): boolean {
  if (!q) return true;
  const { day, minutes } = alertLocal(now, tz);
  return q.days.includes(day) && minutes >= alertMinutes(q.from) && minutes < alertMinutes(q.to);
}

// ---- what the phone taught the server ----
// The server sorts new mail exactly like the app does (it runs the app's own file, see build-functions.mjs), so the icon number follows the
// Primary tab. What only the phone knows is sent here: the senders and companies the person moved to another tab, and what else may count.

export type AlertExtra = 'none' | 'codes' | 'transactions';
export const ALERT_EXTRAS: AlertExtra[] = ['none', 'codes', 'transactions'];
/** What counts besides Primary mail until the person says otherwise: one-time codes and sign-in alerts. */
export const ALERT_EXTRA_DEFAULT: AlertExtra = 'codes';
/** What the alert rules here can do. The app reads it from `status` to know whether this server follows the Primary tab (an older copy of the function does not know it). */
export const ALERT_SMART = 1;
const ALERT_KINDS: Kind[] = ['person', 'transaction', 'update', 'promo'];
const ALERT_RULES_MAX = 1000;

export type AlertTaught = { rules: Record<string, Kind>; extra: AlertExtra };
export const alertTaughtDefault = (): AlertTaught => ({ rules: {}, extra: ALERT_EXTRA_DEFAULT });
/** The same fingerprint the app computes of its own choices (they match when both hold the same rules). */
export const alertRulesDigest = (t: AlertTaught): string => rulesDigest(t.rules);

/** The choices the phone sent, checked. Refuses anything that is not a sender or company mapped to one of the four kinds. */
export function alertCleanRules(input: unknown): Record<string, Kind> {
  if (!input || typeof input !== 'object' || Array.isArray(input)) throw new Error('bad rules');
  const entries = Object.entries(input as Record<string, unknown>);
  if (entries.length > ALERT_RULES_MAX) throw new Error('too many rules');
  const out: Record<string, Kind> = {};
  for (const [who, kind] of entries) {
    const key = who.trim().toLowerCase();
    if (!isRuleKey(key) || !ALERT_KINDS.includes(kind as Kind)) throw new Error('bad rules'); // "anna@x.no" for one sender, "@x.no" for a whole company
    out[key] = kind as Kind;
  }
  return out;
}

/** What is stored, read defensively: anything unreadable falls back to the defaults (Post then simply sorts without the person's choices). */
export function alertParseTaught(raw: string | null | undefined): AlertTaught {
  const base = alertTaughtDefault();
  if (!raw) return base;
  try {
    const o = JSON.parse(raw) as { rules?: Record<string, unknown>; extra?: unknown } | null;
    const rules: Record<string, Kind> = {};
    for (const [who, kind] of Object.entries(o?.rules && typeof o.rules === 'object' ? o.rules : {})) if (isRuleKey(who) && ALERT_KINDS.includes(kind as Kind)) rules[who] = kind as Kind;
    return { rules, extra: ALERT_EXTRAS.includes(o?.extra as AlertExtra) ? (o!.extra as AlertExtra) : base.extra };
  } catch { return base; }
}

/** Applies the keys the phone sent (only those) to what is stored. */
export function alertTaughtPatch(current: AlertTaught, input: { rules?: unknown; extra?: unknown }): AlertTaught {
  const next: AlertTaught = { rules: current.rules, extra: current.extra };
  if ('rules' in input) next.rules = alertCleanRules(input.rules);
  if ('extra' in input) {
    if (!ALERT_EXTRAS.includes(input.extra as AlertExtra)) throw new Error('bad extra');
    next.extra = input.extra as AlertExtra;
  }
  return next;
}

/** One message as the sorting sees it. `code`: a one-time code or sign-in alert. `unsure`: the sorting could not be done, which counts. */
export type AlertSorted = { kind: Kind; why: string[]; code: boolean; unsure?: boolean };
const alertUnsure = (): AlertSorted => ({ kind: 'person', why: [], code: false, unsure: true });

/** The app's verdict on a new message. `known`: the person has written to this address (Sent Items), which can turn a company-looking mail into Primary. */
export function alertSort(m: GraphMessage, taught: AlertTaught, vips: string[], known = false): AlertSorted {
  const addr = (m.from?.emailAddress?.address ?? '').trim().toLowerCase();
  const input = {
    fromAddress: addr, fromName: m.from?.emailAddress?.name ?? '', subject: m.subject ?? '',
    preview: (m.bodyPreview ?? '').replace(/\s+/g, ' ').trim().slice(0, 200), signals: signalsFromHeaders(m.internetMessageHeaders),
  };
  const ctx = { overrides: taught.rules, vips: new Set(vips.map((v) => v.toLowerCase())), known: known && addr ? new Set([addr]) : undefined };
  const v = classify(input, ctx);
  // A sender moved to Transactions keeps its place there, yet a code from it is still a code: the words decide that, not the rule.
  const code = isSecurityMail(v) || (v.kind === 'transaction' && isSecurityMail(classify(input, { ...ctx, overrides: undefined })));
  return { kind: v.kind, why: v.why, code };
}

const KIND_WORDS: Record<Kind, string> = { person: 'a person', transaction: 'a receipt, delivery or booking', update: 'an update', promo: 'a promotion' };

/** Does a sorted message add to the icon number? Primary does; of what is not, codes (and with "transactions" the whole Transactions tab) may. */
export function alertCounts(s: AlertSorted, extra: AlertExtra): { count: boolean; reason: string } {
  if (s.unsure) return { count: true, reason: 'could not tell, so it counts' };
  if (s.kind === 'person') return { count: true, reason: 'a person' };
  if (s.kind === 'transaction' && s.code && extra !== 'none') return { count: true, reason: 'a security code or sign-in alert' };
  if (s.kind === 'transaction' && extra === 'transactions') return { count: true, reason: 'a receipt, delivery or booking' };
  return { count: false, reason: `not in Primary (${s.code ? 'a security code' : KIND_WORDS[s.kind]})` };
}

export type AlertSmart = { sorted: AlertSorted; extra: AlertExtra };

/** Everything but the sorting: mode, read state, folder, VIPs, hours. `smart` is the sorting for a "Primary" account; without it the old header-only rule decides. */
export function alertDecide(m: GraphMessage, a: AlertAccount, now: Date, smart?: AlertSmart): { send: boolean; reason: string; /** Only because it is not Primary. */ notPrimary?: boolean } {
  if (a.mode === 'off') return { send: false, reason: 'alerts are off for this account' };
  if (m.isRead) return { send: false, reason: 'already read' };
  if (a.inbox_folder_id && m.parentFolderId && m.parentFolderId !== a.inbox_folder_id) return { send: false, reason: 'not in the inbox' };
  const addr = (m.from?.emailAddress?.address ?? '').toLowerCase();
  const vip = addr !== '' && a.vips.some((v) => v.toLowerCase() === addr);
  if (vip) return { send: true, reason: 'VIP' }; // VIPs break through the schedule
  if (!alertWithinWindow(a.quiet, now, a.tz)) return { send: false, reason: 'outside this account’s alert hours' };
  if (a.mode === 'vips') return { send: false, reason: 'not a VIP' };
  if (a.mode === 'people') {
    if (!smart) { if (alertKind(m) === 'bulk') return { send: false, reason: 'bulk mail' }; }
    else {
      const c = alertCounts(smart.sorted, smart.extra);
      return c.count ? { send: true, reason: c.reason } : { send: false, reason: c.reason, notPrimary: true };
    }
  }
  return { send: true, reason: a.mode === 'all' ? 'all mail' : 'a person' };
}

const alertClip = (s: string, n: number) => (s.length > n ? `${s.slice(0, n - 1).trimEnd()}…` : s);

/** The notification text. Shows the account only when more than one is watched. */
export function alertBuild(m: GraphMessage, a: Pick<AlertAccount, 'id' | 'label'>, multi: boolean, lang: 'en' | 'nb' = 'en'): { title: string; body: string; url: string; tag: string } {
  const name = (m.from?.emailAddress?.name || m.from?.emailAddress?.address || '').trim() || (lang === 'nb' ? 'Ukjent avsender' : 'Unknown sender');
  const subject = (m.subject ?? '').replace(/\s+/g, ' ').trim() || (lang === 'nb' ? '(uten emne)' : '(no subject)');
  return {
    title: alertClip(multi && a.label ? `${name} · ${a.label}` : name, 60),
    body: alertClip(subject, 110),
    url: `/post/#/m/${encodeURIComponent(a.id)}/${encodeURIComponent(m.id)}`,
    tag: m.id,
  };
}

// ---- keeping the refresh token safe ----

/** AES-GCM with a 256-bit key given as base64url. Output "v1.<iv>.<ciphertext>". */
export async function alertEncrypt(plain: string, keyB64u: string): Promise<string> {
  const key = await crypto.subtle.importKey('raw', b64uToBytes(keyB64u), 'AES-GCM', false, ['encrypt']);
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ct = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, new TextEncoder().encode(plain)));
  return `v1.${bytesToB64u(iv)}.${bytesToB64u(ct)}`;
}

export async function alertDecrypt(stored: string, keyB64u: string): Promise<string> {
  const [v, iv, ct] = stored.split('.');
  if (v !== 'v1' || !iv || !ct) throw new Error('bad stored secret');
  const key = await crypto.subtle.importKey('raw', b64uToBytes(keyB64u), 'AES-GCM', false, ['decrypt']);
  return new TextDecoder().decode(await crypto.subtle.decrypt({ name: 'AES-GCM', iv: b64uToBytes(iv) }, key, b64uToBytes(ct)));
}

/** Constant-time string comparison for the shared secret. */
export function alertSameSecret(a: string | null, b: string): boolean {
  if (a === null || a.length !== b.length) return false;
  let x = 0;
  for (let i = 0; i < a.length; i++) x |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return x === 0;
}

// ---- Microsoft Graph ----

const GRAPH = 'https://graph.microsoft.com/v1.0';
/** What Post may do with the mail: read and change it, and send. Mail.Read is listed on its own although Mail.ReadWrite covers it: Microsoft only
 *  lets a refresh token be redeemed for scopes that were in the original sign-in request, and the server's own refreshes use the full set, so a
 *  rotated refresh token never ends up with fewer permissions than the sign-in gave it. */
export const ALERT_APP_SCOPE = 'offline_access User.Read https://graph.microsoft.com/Mail.Read https://graph.microsoft.com/Mail.ReadWrite https://graph.microsoft.com/Mail.Send';

export class AlertGraphError extends Error {
  status: number;
  code: string;
  constructor(status: number, code: string, message: string) {
    super(message);
    this.name = 'AlertGraphError';
    this.status = status;
    this.code = code;
  }
}

async function graphJson(res: Response): Promise<any> {
  const text = await res.text();
  let body: any = null;
  try { body = text ? JSON.parse(text) : null; } catch { /* not JSON */ }
  if (!res.ok) throw new AlertGraphError(res.status, String(body?.error?.code ?? body?.error ?? 'error'), String(body?.error?.message ?? body?.error_description ?? text).slice(0, 200));
  return body;
}

/** Trades the stored refresh token for a short-lived access token (and a rotated refresh token, which must be stored). */
export async function alertRefresh(f: typeof fetch, p: { clientId: string; refreshToken: string; scope?: string }): Promise<{ accessToken: string; refreshToken: string; expiresIn: number }> {
  const res = await f('https://login.microsoftonline.com/common/oauth2/v2.0/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ client_id: p.clientId, grant_type: 'refresh_token', refresh_token: p.refreshToken, scope: p.scope ?? ALERT_APP_SCOPE }).toString(),
  });
  const b = await graphJson(res);
  return { accessToken: String(b.access_token), refreshToken: String(b.refresh_token ?? p.refreshToken), expiresIn: Number(b.expires_in ?? 3600) };
}

/** Trades the one-time code from the Microsoft sign-in page (PKCE, done in a normal browser tab) for tokens. Public client: no secret. */
export async function alertExchangeCode(f: typeof fetch, p: { clientId: string; code: string; verifier: string; redirectUri: string }): Promise<{ accessToken: string; refreshToken: string }> {
  const res = await f('https://login.microsoftonline.com/common/oauth2/v2.0/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ client_id: p.clientId, grant_type: 'authorization_code', code: p.code, code_verifier: p.verifier, redirect_uri: p.redirectUri, scope: ALERT_APP_SCOPE }).toString(),
  });
  const b = await graphJson(res);
  if (!b.refresh_token) throw new AlertGraphError(400, 'no_refresh_token', 'Microsoft did not give a refresh token');
  return { accessToken: String(b.access_token), refreshToken: String(b.refresh_token) };
}

const authHeaders = (token: string) => ({ Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' });

export async function alertGetMessage(f: typeof fetch, token: string, id: string): Promise<GraphMessage> {
  const sel = 'subject,bodyPreview,from,isRead,parentFolderId,inferenceClassification,internetMessageHeaders';
  return await graphJson(await f(`${GRAPH}/me/messages/${encodeURIComponent(id)}?$select=${sel}`, { headers: authHeaders(token) }));
}

export async function alertGetInboxId(f: typeof fetch, token: string): Promise<string> {
  const b = await graphJson(await f(`${GRAPH}/me/mailFolders/inbox?$select=id`, { headers: authHeaders(token) }));
  return String(b.id);
}

/** Has this mailbox ever written to that address (Sent Items)? Microsoft's own answer; throws when Microsoft cannot give one. */
export async function alertKnownSender(f: typeof fetch, token: string, address: string): Promise<boolean> {
  const addr = address.trim().toLowerCase();
  if (!/^[^\s@'"]+@[^\s@'"]+$/.test(addr)) return false;
  const base = `${GRAPH}/me/mailFolders/sentitems/messages`;
  const hit = (b: { value?: unknown[] } | null) => Array.isArray(b?.value) && b!.value.length > 0;
  try {
    return hit(await graphJson(await f(`${base}?$filter=${encodeURIComponent(`toRecipients/any(r:r/emailAddress/address eq '${addr}')`)}&$top=1&$select=id`, { headers: authHeaders(token) })));
  } catch { /* not every mailbox takes that filter: search Sent Items for the address instead */ }
  return hit(await graphJson(await f(`${base}?$search=${encodeURIComponent(`"to:${addr}"`)}&$top=1&$select=id`, { headers: authHeaders(token) })));
}

/** Outlook message subscriptions last under 7 days for work accounts but under 3 days (4 230 minutes) for personal Outlook.com and Hotmail
 *  accounts, and Microsoft refuses anything longer. We ask for 4 200 minutes everywhere and renew when 30 hours are left. */
export const alertExpiry = (now: Date, minutes = 4200) => new Date(now.getTime() + minutes * 60_000).toISOString();

/** Microsoft explains a too-long request as "Subscription expiration can only be 4230 minutes in the future": that number, or null. */
const alertCapMinutes = (message: string): number | null => {
  const m = /(\d{3,6})\s+minutes/.exec(message);
  return m ? Number(m[1]) : null;
};

export async function alertCreateSubscription(
  f: typeof fetch, token: string, p: { notificationUrl: string; lifecycleUrl: string; clientState: string; expires: string; now?: () => Date },
): Promise<{ id: string; expires: string }> {
  let expires = p.expires;
  let lifecycle = true;
  for (let attempt = 0; ; attempt++) {
    try {
      const b = await graphJson(await f(`${GRAPH}/subscriptions`, {
        method: 'POST',
        headers: authHeaders(token),
        body: JSON.stringify({
          changeType: 'created', notificationUrl: p.notificationUrl, ...(lifecycle ? { lifecycleNotificationUrl: p.lifecycleUrl } : {}),
          resource: "me/mailFolders('inbox')/messages", expirationDateTime: expires, clientState: p.clientState,
        }),
      }));
      return { id: String(b.id), expires: String(b.expirationDateTime ?? expires) };
    } catch (e) {
      if (!(e instanceof AlertGraphError) || e.status !== 400 || attempt >= 2) throw e;
      const cap = alertCapMinutes(e.message);
      if (cap !== null) expires = alertExpiry((p.now ?? (() => new Date()))(), Math.max(60, cap - 30)); // "too far ahead": ask for less
      else if (lifecycle) lifecycle = false; // some accounts do not take lifecycle notifications: alerts still work, renewal just relies on the schedule
      else throw e;
    }
  }
}

export async function alertRenewSubscription(f: typeof fetch, token: string, id: string, expires: string, now: () => Date = () => new Date()): Promise<string> {
  for (let attempt = 0; ; attempt++) {
    try {
      const b = await graphJson(await f(`${GRAPH}/subscriptions/${encodeURIComponent(id)}`, {
        method: 'PATCH', headers: authHeaders(token), body: JSON.stringify({ expirationDateTime: expires }),
      }));
      return String(b?.expirationDateTime ?? expires);
    } catch (e) {
      const cap = e instanceof AlertGraphError && e.status === 400 ? alertCapMinutes(e.message) : null;
      if (cap === null || attempt >= 1) throw e;
      expires = alertExpiry(now(), Math.max(60, cap - 30));
    }
  }
}

/** Accounts whose subscription is missing or ends within `withinHours`: those get renewed (or created again).
 *  An account Microsoft refused a subscription for a moment ago is left alone for `retryAfterMinutes`, so opening the app does not hammer Microsoft. */
export function alertPlanRenewals<T extends { subscription_id: string | null; subscription_expires_at: string | null; sub_error_at?: string | null }>(accounts: T[], now: Date, withinHours = 30, retryAfterMinutes = 30): T[] {
  const limit = now.getTime() + withinHours * 3_600_000;
  const recent = now.getTime() - retryAfterMinutes * 60_000;
  return accounts.filter((a) => (!a.subscription_id || !a.subscription_expires_at || new Date(a.subscription_expires_at).getTime() < limit)
    && !(a.sub_error_at && new Date(a.sub_error_at).getTime() > recent));
}

// ---- orchestration (the edge function only wires these to Supabase and Deno) ----

export type AlertStored = AlertAccount & {
  refresh_token_enc: string; client_state: string; subscription_id: string | null; subscription_expires_at: string | null;
  /** Why Microsoft would not start the new-mail alerts for this mailbox (the mailbox itself still works), and when that happened. */
  sub_error?: string | null; sub_error_at?: string | null;
  /** SHA-256 of the secret of each phone or computer signed in to this mailbox (at most 8, the oldest drop off). */
  session_hashes?: string[];
};
export type AlertDevice = PushSub & { id: string; lang: string; badge?: number };
export type AlertStore = {
  accountBySubscription(subscriptionId: string): Promise<AlertStored | null>;
  allAccounts(): Promise<AlertStored[]>;
  /** true when this message had not been announced yet */
  markSeen(accountId: string, messageId: string): Promise<boolean>;
  update(accountId: string, patch: Record<string, unknown>): Promise<void>;
  upsertAccount(row: Record<string, unknown>): Promise<AlertStored>;
  deleteAccount(accountId: string): Promise<void>;
  devices(): Promise<AlertDevice[]>;
  removeDevices(ids: string[]): Promise<void>;
  /** What the phone taught the server for this account (the defaults when nothing was sent yet). Never throws. */
  getTaught(accountId: string): Promise<AlertTaught>;
  setTaught(accountId: string, taught: AlertTaught): Promise<void>;
  /** The number shown on that phone's icon. */
  setBadge(deviceId: string, badge: number): Promise<void>;
  /** The phone opened Post: its number goes back to zero. true when the phone is known. */
  resetBadge(endpoint: string): Promise<boolean>;
  /** A finished sign-in (sealed) waiting for the app that started it. */
  putSignin(handle: string, enc: string): Promise<void>;
  /** Returns it and removes it; null when there is none. */
  takeSignin(handle: string): Promise<string | null>;
  pruneSignins(beforeIso: string): Promise<void>;
};
export type AlertDeps = {
  store: AlertStore;
  fetch: typeof fetch;
  clientId: string;
  encKey: string;
  notificationUrl: string;
  send: (sub: PushSub, payload: unknown) => Promise<number>;
  now: () => Date;
  /** Mailboxes allowed to sign in to this server (`post_setup` / `post_allow`, or POST_ALLOWED_EMAILS). Without this list nobody can, so strangers cannot use your server. */
  allowedEmails?: string[];
  /** One line per new mail, for the function's Logs: what was decided and why. */
  log?: (line: string) => void;
};

/** A fresh access token for an account. If Microsoft rotated the refresh token, the new one is stored (encrypted). */
export async function alertAccessToken(d: AlertDeps, a: AlertStored): Promise<string> {
  const current = await alertDecrypt(a.refresh_token_enc, d.encKey);
  const t = await alertRefresh(d.fetch, { clientId: d.clientId, refreshToken: current });
  if (t.refreshToken !== current) await d.store.update(a.id, { refresh_token_enc: await alertEncrypt(t.refreshToken, d.encKey) });
  return t.accessToken;
}

// Every push shows a notification (iOS requires it) and carries the new icon number: alerts delivered to that phone since it last opened Post.
async function alertPushAll(d: AlertDeps, payload: (lang: 'en' | 'nb') => Record<string, unknown>): Promise<number> {
  const devices = await d.store.devices();
  const gone: string[] = [];
  let sent = 0;
  await Promise.all(devices.map(async (dev) => {
    try {
      const badge = (dev.badge ?? 0) + 1;
      const status = await d.send(dev, { ...payload(dev.lang === 'nb' ? 'nb' : 'en'), badge });
      if (status >= 200 && status < 300) { sent++; await d.store.setBadge(dev.id, badge); }
      else if (isGone(status)) gone.push(dev.id);
    } catch { /* one phone failing must not stop the others */ }
  }));
  if (gone.length) await d.store.removeDevices(gone);
  return sent;
}

/** Whether one new message adds to the icon number: the account's settings, and for a "Primary" account the same sorting the app does. */
export async function alertVerdict(d: Pick<AlertDeps, 'store' | 'fetch' | 'now'>, token: string, m: GraphMessage, a: AlertAccount): Promise<{ send: boolean; reason: string }> {
  if (a.mode !== 'people') return alertDecide(m, a, d.now());
  const taught = await d.store.getTaught(a.id).catch(() => alertTaughtDefault()); // not being able to read the choices only means they are not applied
  let first: AlertSorted;
  try { first = alertSort(m, taught, a.vips); } catch { first = alertUnsure(); }
  const v = alertDecide(m, a, d.now(), { sorted: first, extra: taught.extra });
  if (!v.notPrimary) return v;
  // Not Primary as far as the server can tell. The sorting makes mail Primary when the person has written to the sender, which only the phone
  // knew: when that would change the verdict, ask Outlook (Sent Items) before staying quiet. If it cannot answer, the mail counts.
  let ifKnown: AlertSorted;
  try { ifKnown = alertSort(m, taught, a.vips, true); } catch { return v; }
  if (ifKnown.kind === first.kind) return v;
  try {
    return (await alertKnownSender(d.fetch, token, m.from?.emailAddress?.address ?? '')) ? alertDecide(m, a, d.now(), { sorted: ifKnown, extra: taught.extra }) : v;
  } catch {
    return { send: true, reason: 'could not tell, so it counts' };
  }
}

/** New-mail notifications from Microsoft: look each message up, decide, alert. Returns what happened, for logs and tests. */
export async function alertProcess(d: AlertDeps, list: AlertNotification[]): Promise<{ id: string; outcome: string }[]> {
  const results: { id: string; outcome: string }[] = [];
  // The Logs say why a mail did or did not count, and which company it came from (the domain only: never a subject, a name or an address).
  const done = (id: string, outcome: string, m?: GraphMessage) => {
    results.push({ id, outcome });
    try { d.log?.(m ? `${outcome} · from ${(m.from?.emailAddress?.address ?? '').split('@')[1]?.toLowerCase() || 'an unknown sender'}` : outcome); } catch { /* a log line must never stop an alert */ }
  };
  const tokens = new Map<string, string>();
  const all = list.length ? await d.store.allAccounts() : [];
  for (const n of list) {
    const a = await d.store.accountBySubscription(n.subscriptionId);
    if (!a) { done(n.messageId, 'unknown subscription'); continue; }
    if (!(await d.store.markSeen(a.id, n.messageId))) { done(n.messageId, 'duplicate'); continue; }
    let m: GraphMessage | undefined;
    try {
      let token = tokens.get(a.id);
      if (!token) { token = await alertAccessToken(d, a); tokens.set(a.id, token); }
      m = await alertGetMessage(d.fetch, token, n.messageId);
      const verdict = await alertVerdict(d, token, m, a);
      if (!verdict.send) { done(n.messageId, `skipped: ${verdict.reason}`, m); continue; }
      const sent = await alertPushAll(d, (lang) => alertBuild(m!, a, all.length > 1, lang));
      if (sent > 0) await d.store.update(a.id, { last_alert_at: d.now().toISOString() });
      done(n.messageId, sent > 0 ? `alerted (${verdict.reason})` : 'no device to alert', m);
    } catch (e) {
      done(n.messageId, `error: ${e instanceof Error ? e.message : String(e)}`, m);
    }
  }
  return results;
}

export type AlertRegisterInput = { email: string; label?: string; refreshToken: string; mode?: AlertMode; vips?: string[]; quiet?: AlertQuiet | null; tz?: string };

const MODES: AlertMode[] = ['people', 'all', 'vips', 'off'];
export function alertCleanQuiet(q: unknown): AlertQuiet | null {
  if (!q || typeof q !== 'object') return null;
  const { days, from, to } = q as AlertQuiet;
  if (!Array.isArray(days) || !days.every((x) => Number.isInteger(x) && x >= 1 && x <= 7) || !/^\d\d:\d\d$/.test(from) || !/^\d\d:\d\d$/.test(to)) throw new Error('bad schedule');
  return { days: [...new Set(days)].sort(), from, to };
}

/** Asks Microsoft to tell us about new mail in this mailbox. Never throws: the alerts are the extra, and the mailbox works without them
 *  (the reason is kept so Settings can show it, and the schedule tries again). */
async function alertSubscribe(d: AlertDeps, a: Pick<AlertStored, 'id' | 'client_state'>, token: string): Promise<{ expires: string | null; error: string | null }> {
  try {
    const sub = await alertCreateSubscription(d.fetch, token, {
      notificationUrl: d.notificationUrl, lifecycleUrl: `${d.notificationUrl}?lifecycle=1`, clientState: a.client_state, expires: alertExpiry(d.now()), now: d.now,
    });
    await d.store.update(a.id, { subscription_id: sub.id, subscription_expires_at: sub.expires, sub_error: null, sub_error_at: null });
    return { expires: sub.expires, error: null };
  } catch (e) {
    const error = (e instanceof Error ? e.message : String(e)).slice(0, 200);
    await d.store.update(a.id, { subscription_id: null, subscription_expires_at: null, sub_error: error, sub_error_at: d.now().toISOString() });
    return { expires: null, error };
  }
}

/** Starts watching a mailbox: stores the (encrypted) sign-in, finds the inbox, asks Microsoft to tell us about new mail. */
export async function alertRegister(d: AlertDeps, input: AlertRegisterInput): Promise<{ id: string; email: string; expires: string; alertsError: string | null }> {
  const email = String(input.email ?? '').trim().toLowerCase();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new Error('bad email');
  if (!input.refreshToken || typeof input.refreshToken !== 'string') throw new Error('missing sign-in');
  const mode = input.mode ?? 'people';
  if (!MODES.includes(mode)) throw new Error('bad mode');
  const row = await d.store.upsertAccount({
    email, label: (input.label ?? '').slice(0, 30), refresh_token_enc: await alertEncrypt(input.refreshToken, d.encKey),
    client_state: bytesToB64u(crypto.getRandomValues(new Uint8Array(24))), mode, vips: (input.vips ?? []).map((v) => String(v).toLowerCase()).slice(0, 200),
    quiet: alertCleanQuiet(input.quiet), tz: input.tz && /^[A-Za-z_]+\/[A-Za-z_\-+0-9]+$/.test(input.tz) ? input.tz : 'Europe/Oslo',
  });
  let token: string;
  try {
    token = await alertAccessToken(d, row);
    await d.store.update(row.id, { inbox_folder_id: await alertGetInboxId(d.fetch, token) });
  } catch (e) {
    await d.store.deleteAccount(row.id); // never keep a sign-in that did not work
    throw e;
  }
  const alerts = await alertSubscribe(d, row, token);
  return { id: row.id, email, expires: alerts.expires ?? '', alertsError: alerts.error };
}

/** Keeps every subscription alive (run on a schedule, and whenever Post is opened). A sign-in Microsoft no longer accepts triggers one "sign in again" alert. */
export async function alertRenewAll(d: AlertDeps, accounts?: AlertStored[]): Promise<{ email: string; outcome: string }[]> {
  const list = alertPlanRenewals(accounts ?? await d.store.allAccounts(), d.now());
  const out: { email: string; outcome: string }[] = [];
  for (const a of list) {
    try {
      const token = await alertAccessToken(d, a);
      try {
        if (!a.subscription_id) throw new AlertGraphError(404, 'none', 'no subscription');
        const exp = await alertRenewSubscription(d.fetch, token, a.subscription_id, alertExpiry(d.now()), d.now);
        await d.store.update(a.id, { subscription_expires_at: exp, sub_error: null, sub_error_at: null });
        out.push({ email: a.email, outcome: 'renewed' });
      } catch (e) {
        if (!(e instanceof AlertGraphError) || (e.status !== 404 && e.status !== 410)) throw e;
        const r = await alertSubscribe(d, a, token);
        out.push({ email: a.email, outcome: r.error ? `error: ${r.error}` : 'recreated' });
      }
    } catch (e) {
      const needsSignIn = e instanceof AlertGraphError && (e.code === 'invalid_grant' || e.status === 401 || e.status === 403);
      const message = e instanceof Error ? e.message : String(e);
      out.push({ email: a.email, outcome: needsSignIn ? 'needs sign-in' : `error: ${message}` });
      if (!needsSignIn) await d.store.update(a.id, { sub_error: message.slice(0, 200), sub_error_at: d.now().toISOString() }).catch(() => {});
      if (needsSignIn) {
        await alertPushAll(d, (lang) => ({
          title: lang === 'nb' ? 'Post-varsler trenger innlogging' : 'Post alerts need you to sign in',
          body: lang === 'nb' ? `Logg inn p\u00e5 ${a.label || a.email} igjen i Post for \u00e5 fortsette \u00e5 f\u00e5 varsler.` : `Sign in to ${a.label || a.email} again in Post to keep getting alerts.`,
          url: '/post/#/accounts', tag: `signin-${a.id}`,
        }));
      }
    }
  }
  return out;
}

/** Microsoft says a subscription needs attention: renew it right away (renewal re-authorises it). */
export async function alertLifecycle(d: AlertDeps, events: AlertLifecycle[]): Promise<string[]> {
  const out: string[] = [];
  for (const ev of events) {
    const a = await d.store.accountBySubscription(ev.subscriptionId);
    if (!a) continue;
    if (ev.event === 'reauthorizationRequired') out.push(...(await alertRenewAll(d, [{ ...a, subscription_expires_at: null }])).map((r) => r.outcome));
    else if (ev.event === 'subscriptionRemoved') out.push(...(await alertRenewAll(d, [{ ...a, subscription_id: null }])).map((r) => r.outcome));
  }
  return out;
}

export async function alertTest(d: AlertDeps): Promise<number> {
  return await alertPushAll(d, (lang) => ({
    title: lang === 'nb' ? 'Post-varsler fungerer' : 'Post alerts work',
    body: lang === 'nb' ? 'Slik ser et varsel ut n\u00e5r det kommer ny e-post.' : 'This is what an alert looks like when new mail arrives.',
    url: '/post/', tag: 'test',
  }));
}

export type AlertStatusAccount = {
  id: string; email: string; label: string; mode: AlertMode; quiet: AlertQuiet | null; vips: string[];
  subscription_expires_at: string | null; last_alert_at: string | null; sub_error: string | null;
  /** What counts besides Primary mail, and a fingerprint of the choices the phone taught the server (the phone sends them again when it differs). */
  extra: AlertExtra; rules_digest: string;
};

/** One mailbox as the app's Alerts screen sees it. */
export function alertStatusRow(a: AlertStored & { last_alert_at?: string | null }, taught: AlertTaught): AlertStatusAccount {
  return {
    id: a.id, email: a.email, label: a.label, mode: a.mode, quiet: a.quiet, vips: a.vips,
    subscription_expires_at: a.subscription_expires_at, last_alert_at: a.last_alert_at ?? null, sub_error: a.sub_error ?? null,
    extra: taught.extra, rules_digest: alertRulesDigest(taught),
  };
}

/** Validated changes to an account's alert settings (only the keys that were sent). */
export function alertSettingsPatch(input: { label?: unknown; mode?: unknown; vips?: unknown; quiet?: unknown; tz?: unknown }): Record<string, unknown> {
  const patch: Record<string, unknown> = {};
  if ('label' in input) patch.label = String(input.label ?? '').slice(0, 30);
  if ('mode' in input) {
    if (!MODES.includes(input.mode as AlertMode)) throw new Error('bad mode');
    patch.mode = input.mode;
  }
  if ('vips' in input) {
    if (!Array.isArray(input.vips)) throw new Error('bad vips');
    patch.vips = input.vips.map((v) => String(v).toLowerCase()).slice(0, 200);
  }
  if ('quiet' in input) patch.quiet = alertCleanQuiet(input.quiet);
  if ('tz' in input) {
    if (typeof input.tz !== 'string' || !/^[A-Za-z_]+\/[A-Za-z_\-+0-9]+$/.test(input.tz)) throw new Error('bad time zone');
    patch.tz = input.tz;
  }
  return patch;
}

/** Stops alerts for a mailbox: tells Microsoft to stop (best effort) and forgets the sign-in. */
export async function alertUnregister(d: AlertDeps, email: string): Promise<boolean> {
  const a = (await d.store.allAccounts()).find((x) => x.email === email.trim().toLowerCase());
  if (!a) return false;
  if (a.subscription_id) {
    try {
      const token = await alertAccessToken(d, a);
      await d.fetch(`${GRAPH}/subscriptions/${encodeURIComponent(a.subscription_id)}`, { method: 'DELETE', headers: authHeaders(token) });
    } catch { /* the subscription expires by itself within days */ }
  }
  await d.store.deleteAccount(a.id);
  return true;
}

/** The phone opened Post: clear its icon number on the server so the next alert starts again from 1. */
export async function alertSeen(d: AlertDeps, endpoint: string): Promise<boolean> {
  return await d.store.resetBadge(endpoint);
}

// ---- sign-in without any shared key ----
// A phone or computer proves which mailbox it belongs to with a session secret that the server hands out once, right after Microsoft has
// confirmed who signed in. Only a hash is stored. Nothing has to be typed or pasted into the app.

async function sha256Hex(s: string): Promise<string> {
  return [...new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(s)))].map((b) => b.toString(16).padStart(2, '0')).join('');
}

export type AlertSignedIn = { id: string; email: string; label: string; session: string; expires: string; /** Why new-mail alerts could not start (the mailbox itself works), or null. */ alertsError?: string | null };

/** The account behind an `x-post-session` header ("<account id>.<secret>"), or null. */
export async function alertFindBySession(store: AlertStore, header: string | null): Promise<AlertStored | null> {
  if (!header) return null;
  const dot = header.indexOf('.');
  if (dot < 1) return null;
  const id = header.slice(0, dot), secret = header.slice(dot + 1);
  if (secret.length < 20) return null;
  const a = (await store.allAccounts()).find((x) => x.id === id);
  if (!a) return null;
  const hash = await sha256Hex(secret);
  return (a.session_hashes ?? []).some((h) => alertSameSecret(h, hash)) ? a : null;
}

async function issueSession(d: AlertDeps, accountId: string): Promise<string> {
  const secret = bytesToB64u(crypto.getRandomValues(new Uint8Array(32)));
  const a = (await d.store.allAccounts()).find((x) => x.id === accountId);
  const hashes = [...(a?.session_hashes ?? []), await sha256Hex(secret)].slice(-8);
  await d.store.update(accountId, { session_hashes: hashes });
  return `${accountId}.${secret}`;
}

/** Common end of both sign-in routes: learn which mailbox it is, check it is allowed, start watching it, hand out a session. */
async function finishSignIn(d: AlertDeps, tokens: { accessToken: string; refreshToken: string }, wantedLabel?: string): Promise<AlertSignedIn> {
  const me = await graphJson(await d.fetch(`${GRAPH}/me?$select=mail,userPrincipalName`, { headers: authHeaders(tokens.accessToken) }));
  const email = String(me.mail ?? me.userPrincipalName ?? '').trim().toLowerCase();
  const allowed = (d.allowedEmails ?? []).map((x) => x.trim().toLowerCase()).filter(Boolean);
  if (!allowed.length) throw new Error(`This server does not know which mailboxes may sign in yet. In the Supabase SQL editor run: select post_allow('${email || 'you@outlook.com'}');`);
  if (!allowed.includes(email)) throw new Error(`${email || 'This account'} is not on this server's allowed list. In the Supabase SQL editor run: select post_allow('${email || 'you@outlook.com'}');`);
  const label = (wantedLabel ?? '').trim() || (/@(outlook|hotmail|live|msn)\./i.test(email) ? 'Personal' : 'Work');
  const r = await alertRegister(d, { email, label, refreshToken: tokens.refreshToken });
  return { id: r.id, email, label, session: await issueSession(d, r.id), expires: r.expires, alertsError: r.alertsError };
}

// One-button sign-in, the same on a phone and a computer. The server builds the Microsoft sign-in address (with its own PKCE secret sealed inside
// `state`), so whichever browser window Microsoft sends you back to can finish the job. If that window is not the app (iOS can open the sign-in
// in a separate view), the finished sign-in waits under the app's handle, and the app collects it as soon as it is looked at again.
const SIGNIN_TTL_MS = 15 * 60_000;
const AUTHORIZE = 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize';

export async function alertSigninStart(d: AlertDeps, input: { redirectUri: string; hint?: string }): Promise<{ url: string; handle: string }> {
  if (!/^https:\/\/[^\s]+$/.test(input.redirectUri ?? '')) throw new Error('bad request');
  const verifier = bytesToB64u(crypto.getRandomValues(new Uint8Array(48)));
  const handle = bytesToB64u(crypto.getRandomValues(new Uint8Array(24)));
  const challenge = bytesToB64u(new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(verifier))));
  const state = await alertEncrypt(JSON.stringify({ v: verifier, h: handle, r: input.redirectUri, x: d.now().getTime() + SIGNIN_TTL_MS }), d.encKey);
  const q = new URLSearchParams({
    client_id: d.clientId, response_type: 'code', redirect_uri: input.redirectUri, response_mode: 'query', scope: ALERT_APP_SCOPE,
    code_challenge: challenge, code_challenge_method: 'S256', state, prompt: 'select_account',
  });
  if (input.hint && /^[^\s@]+@[^\s@]+$/.test(input.hint)) q.set('login_hint', input.hint);
  await d.store.pruneSignins(new Date(d.now().getTime() - 2 * SIGNIN_TTL_MS).toISOString());
  return { url: `${AUTHORIZE}?${q.toString()}`, handle };
}

export type AlertSigninResult = { status: 'pending' } | ({ status: 'done' } & AlertSignedIn);

/** Microsoft sent someone back with a code: finish the sign-in, keep the result for the app's handle, and hand it to whoever asks. */
export async function alertSigninFinish(d: AlertDeps, input: { code: string; state: string; label?: string }): Promise<{ status: 'done'; handle: string } & AlertSignedIn> {
  if (!input.code || !input.state) throw new Error('bad request');
  let sealed: { v: string; h: string; r: string; x: number };
  try { sealed = JSON.parse(await alertDecrypt(input.state, d.encKey)); } catch { throw new Error('This sign-in did not start here. Try again.'); }
  if (d.now().getTime() > sealed.x) throw new Error('The sign-in took too long. Try again.');
  const t = await alertExchangeCode(d.fetch, { clientId: d.clientId, code: input.code, verifier: sealed.v, redirectUri: sealed.r });
  const done = await finishSignIn(d, t, input.label);
  await d.store.putSignin(sealed.h, await alertEncrypt(JSON.stringify(done), d.encKey));
  return { status: 'done', handle: sealed.h, ...done };
}

/** The app asks whether the sign-in it started has finished somewhere. The result is handed over once. */
export async function alertSigninPoll(d: AlertDeps, handle: string): Promise<AlertSigninResult> {
  if (!handle || typeof handle !== 'string' || handle.length < 20) throw new Error('bad request');
  const enc = await d.store.takeSignin(handle);
  if (!enc) return { status: 'pending' };
  return { status: 'done', ...(JSON.parse(await alertDecrypt(enc, d.encKey)) as AlertSignedIn) };
}

/** Called by the app once it has the result from the landing window itself, so nothing is left waiting on the server. */
export async function alertSigninForget(d: AlertDeps, handle: string): Promise<void> {
  if (typeof handle === 'string' && handle.length >= 20) await d.store.takeSignin(handle);
}

/** What the app needs to know before anyone has signed in: nothing secret. */
export function alertPublicConfig(d: Pick<AlertDeps, 'clientId'>) {
  return { clientId: d.clientId };
}

/** A short-lived Graph access token (about an hour) for the web app to read and change mail directly. The long-lived sign-in never leaves the server. */
export async function alertMintToken(d: AlertDeps, email: string): Promise<{ accessToken: string; expiresIn: number; email: string }> {
  const a = (await d.store.allAccounts()).find((x) => x.email === email.trim().toLowerCase());
  if (!a) throw new Error('unknown account');
  const current = await alertDecrypt(a.refresh_token_enc, d.encKey);
  const t = await alertRefresh(d.fetch, { clientId: d.clientId, refreshToken: current });
  if (t.refreshToken !== current) await d.store.update(a.id, { refresh_token_enc: await alertEncrypt(t.refreshToken, d.encKey) });
  return { accessToken: t.accessToken, expiresIn: t.expiresIn, email: a.email };
}

// ---- setup without secrets ----
// Everything Post's server needs can come from Supabase's secrets (the old way) or from the `post_config` table, which `select post_setup(...)` fills.
// What is not given is made up: the key that seals sign-ins is derived from the service role key the function already has, and the key pair for
// Web Push and the key the 6-hourly renewal uses are generated once and kept in the table.

/** A 256-bit key (base64url) derived from a secret the function already holds, so sealing sign-ins needs no extra secret. */
export async function alertDeriveKey(secret: string): Promise<string> {
  const ikm = await crypto.subtle.importKey('raw', new TextEncoder().encode(secret), 'HKDF', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits({ name: 'HKDF', hash: 'SHA-256', salt: new TextEncoder().encode('post-alerts'), info: new TextEncoder().encode('sealing key v1') }, ikm, 256);
  return bytesToB64u(new Uint8Array(bits));
}

/** A fresh VAPID key pair in the form `sendPush` takes: the 65-byte public point and the 32-byte private scalar, both base64url. */
export async function alertNewVapid(): Promise<{ publicKey: string; privateKey: string }> {
  const kp = await crypto.subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-256' }, true, ['sign']);
  const jwk = await crypto.subtle.exportKey('jwk', kp.privateKey);
  return { publicKey: bytesToB64u(new Uint8Array(await crypto.subtle.exportKey('raw', kp.publicKey))), privateKey: String(jwk.d) };
}

/** "a@x.no, b@y.no" (commas, semicolons or spaces) as a list of lower-case addresses. */
export const alertEmails = (list: string | null | undefined): string[] => (list ?? '').split(/[,;\s]+/).map((x) => x.trim().toLowerCase()).filter(Boolean);

export type AlertConfigStore = {
  /** Every row of the post_config table. Throws when the table does not exist yet. */
  load(): Promise<Record<string, string>>;
  /** Writes only when the key has no value yet, so two requests at once cannot overwrite each other. */
  putIfMissing(key: string, value: string): Promise<void>;
  /** Writes always. */
  put(key: string, value: string): Promise<void>;
};
export type AlertConfig = {
  clientId: string | null; encKey: string | null; allowedEmails: string[];
  /** What the renewal schedule must send (header x-alerts-key). Either of these is accepted. */
  adminKeys: string[];
  vapid: { publicKey: string; privateKey: string } | null;
};

/** Settings from the environment (Supabase secrets) first, then from the post_config table; whatever is still missing and can be made up is made up and kept. */
export async function alertResolveConfig(env: (name: string) => string | undefined, store: AlertConfigStore, functionUrl: string): Promise<AlertConfig> {
  let rows: Record<string, string> = {};
  let canStore = true;
  try { rows = await store.load(); } catch { canStore = false; } // the table is not there yet: secrets only
  const e = (name: string) => env(name)?.trim() || null;

  const made: [string, string][] = [];
  const vapidEnv = e('VAPID_PUBLIC_KEY') && e('VAPID_PRIVATE_KEY') ? { publicKey: e('VAPID_PUBLIC_KEY')!, privateKey: e('VAPID_PRIVATE_KEY')! } : null;
  if (canStore && !rows.cron_key) made.push(['cron_key', bytesToB64u(crypto.getRandomValues(new Uint8Array(24)))]);
  if (canStore && !vapidEnv && !rows.vapid) made.push(['vapid', JSON.stringify(await alertNewVapid())]);
  if (made.length) {
    try {
      for (const [k, v] of made) await store.putIfMissing(k, v);
      rows = await store.load(); // if two requests raced, both read the same winner
    } catch { /* keep going with what we have */ }
  }
  if (canStore && rows.function_url !== functionUrl) { try { await store.put('function_url', functionUrl); } catch { /* the schedule just waits */ } }

  let vapid = vapidEnv;
  if (!vapid && rows.vapid) { try { const v = JSON.parse(rows.vapid); if (v?.publicKey && v?.privateKey) vapid = { publicKey: String(v.publicKey), privateKey: String(v.privateKey) }; } catch { /* regenerated never: the row is ours */ } }
  const service = e('SUPABASE_SERVICE_ROLE_KEY');
  return {
    clientId: e('MS_CLIENT_ID') ?? (rows.ms_client_id?.trim() || null),
    encKey: e('ALERTS_ENC_KEY') ?? (service ? await alertDeriveKey(service) : null),
    allowedEmails: [...new Set([...alertEmails(env('POST_ALLOWED_EMAILS')), ...alertEmails(rows.allowed_emails)])],
    adminKeys: [e('POST_ALERTS_KEY'), rows.cron_key?.trim() || null].filter((x): x is string => !!x),
    vapid,
  };
}

// ---- handler ----
// sign in. Nothing else has to be set. Supabase secrets still work and win when present: MS_CLIENT_ID, POST_ALLOWED_EMAILS, ALERTS_ENC_KEY (otherwise derived
// from the service role key), VAPID_PUBLIC_KEY / VAPID_PRIVATE_KEY / VAPID_SUBJECT (otherwise made once and kept in the database), POST_ALERTS_KEY.
// Deploy with "Verify JWT" OFF: Microsoft and the schedule cannot send a Supabase login. The webhook is protected by a secret clientState per mailbox.

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'content-type, x-alerts-key, x-post-session',
};
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, 'Content-Type': 'application/json' } });

// Microsoft wants an answer within 3 seconds, so the real work continues after we have replied.
function later(p: Promise<unknown>) {
  const rt = (globalThis as { EdgeRuntime?: { waitUntil?: (p: Promise<unknown>) => void } }).EdgeRuntime;
  if (rt?.waitUntil) rt.waitUntil(p.catch((e) => console.error('post-alerts', e instanceof Error ? e.message : e)));
  else p.catch((e) => console.error('post-alerts', e instanceof Error ? e.message : e));
}

Deno.serve(async (req) => {
  // Microsoft proves it owns the subscription by sending ?validationToken=...: echo it back as plain text.
  const validation = alertValidationToken(req.url);
  if (validation) return new Response(validation, { status: 200, headers: { 'Content-Type': 'text/plain' } });
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors });

  const admin = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
  const functionUrl = `${Deno.env.get('SUPABASE_URL')}/functions/v1/post-alerts`;
  const configStore: AlertConfigStore = {
    load: async () => {
      // What the phones taught the server is kept in this table too (one row per mailbox, "taught:<id>"): not settings, so not read here.
      // Should the database refuse that filter, everything is read and those rows are left out below: the settings must always load.
      let read = await admin.from('post_config').select('key, value').not('key', 'like', 'taught:%');
      if (read.error) read = await admin.from('post_config').select('key, value');
      if (read.error) throw new Error(read.error.message);
      return Object.fromEntries(((read.data ?? []) as { key: string; value: string }[]).filter((r) => !r.key.startsWith('taught:')).map((r) => [r.key, r.value]));
    },
    putIfMissing: async (k, v) => { await admin.from('post_config').upsert({ key: k, value: v }, { onConflict: 'key', ignoreDuplicates: true }); },
    put: async (k, v) => { await admin.from('post_config').upsert({ key: k, value: v, updated_at: new Date().toISOString() }, { onConflict: 'key' }); },
  };
  const cfg = await alertResolveConfig((k) => Deno.env.get(k), configStore, functionUrl);
  if (!cfg.clientId || !cfg.encKey) {
    return json({ error: 'not_configured', message: 'Post\u2019s server has no Microsoft client ID yet. In the Supabase SQL editor run: select post_setup(\'<client id>\', \'you@outlook.com\');' }, 503);
  }
  const vapid = cfg.vapid ? { ...cfg.vapid, subject: Deno.env.get('VAPID_SUBJECT') ?? `mailto:${cfg.allowedEmails[0] ?? 'admin@example.com'}` } : null;
  const accounts = () => admin.from('post_alert_accounts');
  const store: AlertStore = {
    accountBySubscription: async (id) => ((await accounts().select('*').eq('subscription_id', id).maybeSingle()).data as AlertStored | null) ?? null,
    allAccounts: async () => ((await accounts().select('*')).data ?? []) as AlertStored[],
    markSeen: async (accountId, messageId) => {
      const { data } = await admin.from('post_alert_seen').upsert({ account_id: accountId, message_id: messageId }, { onConflict: 'account_id,message_id', ignoreDuplicates: true }).select('message_id');
      return (data ?? []).length > 0;
    },
    update: async (id, patch) => { await accounts().update(patch).eq('id', id); },
    upsertAccount: async (row) => {
      const { data, error } = await accounts().upsert({ ...row, subscription_id: null, subscription_expires_at: null }, { onConflict: 'email' }).select('*').single();
      if (error) throw new Error(error.message);
      return data as AlertStored;
    },
    deleteAccount: async (id) => { await accounts().delete().eq('id', id); await admin.from('post_config').delete().eq('key', `taught:${id}`); },
    getTaught: async (id): Promise<AlertTaught> => {
      try { return alertParseTaught(((await admin.from('post_config').select('value').eq('key', `taught:${id}`).maybeSingle()).data as { value: string } | null)?.value); } catch { return alertParseTaught(null); }
    },
    setTaught: async (id, taught) => {
      const { error } = await admin.from('post_config').upsert({ key: `taught:${id}`, value: JSON.stringify(taught), updated_at: new Date().toISOString() }, { onConflict: 'key' });
      if (error) throw new Error(error.message);
    },
    devices: async () => ((await admin.from('post_alert_devices').select('id, endpoint, p256dh, auth, lang, badge')).data ?? []) as { id: string; endpoint: string; p256dh: string; auth: string; lang: string; badge: number }[],
    removeDevices: async (ids) => { await admin.from('post_alert_devices').delete().in('id', ids); },
    setBadge: async (id, badge) => { await admin.from('post_alert_devices').update({ badge }).eq('id', id); },
    putSignin: async (handle, enc) => { await admin.from('post_signins').upsert({ handle, result_enc: enc, created_at: new Date().toISOString() }, { onConflict: 'handle' }); },
    takeSignin: async (handle) => {
      const { data } = await admin.from('post_signins').delete().eq('handle', handle).select('result_enc');
      return ((data ?? [])[0] as { result_enc: string } | undefined)?.result_enc ?? null;
    },
    pruneSignins: async (beforeIso) => { await admin.from('post_signins').delete().lt('created_at', beforeIso); },
    resetBadge: async (endpoint) => ((await admin.from('post_alert_devices').update({ badge: 0 }).eq('endpoint', endpoint).select('id')).data ?? []).length > 0,
  };
  const deps: AlertDeps = {
    store, fetch, clientId: cfg.clientId, encKey: cfg.encKey, now: () => new Date(),
    allowedEmails: cfg.allowedEmails,
    notificationUrl: functionUrl,
    send: async (sub, payload) => { if (!vapid) throw new Error('push is not set up'); return await sendPush(sub, payload, vapid); },
    log: (line) => console.log('post-alerts:', line),
  };

  let body: Record<string, any> | null = null;
  if (req.method === 'POST') body = await req.json().catch(() => null);

  // From Microsoft: a body of notifications (no "op"), authenticated by each mailbox's secret clientState.
  if (req.method === 'POST' && body && typeof body.op !== 'string') {
    const states = new Map((await store.allAccounts()).filter((a) => a.subscription_id).map((a) => [a.subscription_id!, a.client_state]));
    if (new URL(req.url).searchParams.get('lifecycle')) later(alertLifecycle(deps, alertParseLifecycle(body, states)));
    else later(alertProcess(deps, alertParseNotifications(body, states)));
    return new Response(null, { status: 202 });
  }
  if (!body) return json({ error: 'bad_request' }, 400);

  try {
    // Open to everyone (they reveal nothing and cannot do anything without a Microsoft sign-in the allowed list accepts).
    switch (body.op) {
      case 'config': return json(alertPublicConfig(deps));
      case 'vapid': return vapid ? json({ publicKey: vapid.publicKey }) : json({ error: 'push_not_configured' }, 503);
      case 'signin_start': return json(await alertSigninStart(deps, { redirectUri: String(body.redirectUri ?? ''), hint: typeof body.hint === 'string' ? body.hint : undefined }));
      case 'signin_finish': return json(await alertSigninFinish(deps, { code: String(body.code ?? ''), state: String(body.state ?? ''), label: typeof body.label === 'string' ? body.label : undefined }));
      case 'signin_poll': return json(await alertSigninPoll(deps, String(body.handle ?? '')));
      case 'signin_forget': await alertSigninForget(deps, String(body.handle ?? '')); return json({ ok: true });
    }

    // Everything else: either a session from a signed-in phone or computer (its own mailbox only), or the admin key (the schedule).
    const sent = req.headers.get('x-alerts-key');
    const admin_ok = !!sent && cfg.adminKeys.some((k) => alertSameSecret(sent, k));
    const me = admin_ok ? null : await alertFindBySession(store, req.headers.get('x-post-session'));
    if (!admin_ok && !me) return json({ error: 'unauthorized' }, 401);
    const emailOf = () => (me ? me.email : String(body!.email ?? '').trim().toLowerCase());

    switch (body.op) {
      case 'token': return json(await alertMintToken(deps, emailOf()));
      case 'update': {
        const patch = alertSettingsPatch(body);
        const { data } = await accounts().update(patch).eq('email', emailOf()).select('id');
        return (data ?? []).length ? json({ ok: true }) : json({ error: 'not_found' }, 404);
      }
      case 'unregister': return json({ removed: await alertUnregister(deps, emailOf()) });
      case 'status': {
        const devices = await store.devices();
        const list = me ? [me] : await store.allAccounts();
        // Opening Post is also a good moment to renew alerts that are about to lapse (does nothing when none is due).
        if (me) later(alertRenewAll(deps));
        return json({
          smart: ALERT_SMART, // this copy of the function can follow the Primary tab
          devices: devices.length,
          accounts: await Promise.all(list.map(async (a) => alertStatusRow(a, await store.getTaught(a.id)))),
        });
      }
      // What only the phone knows (the senders it moved to another tab, and what else counts besides Primary mail), so that alerts follow the Primary tab.
      case 'taught': {
        const mine = me ?? (await store.allAccounts()).find((x) => x.email === emailOf());
        if (!mine) return json({ error: 'not_found' }, 404);
        const next = alertTaughtPatch(await store.getTaught(mine.id), body);
        await store.setTaught(mine.id, next);
        return json({ ok: true, extra: next.extra, rules_digest: alertRulesDigest(next) });
      }
      case 'seen': return json({ ok: await alertSeen(deps, String(body.endpoint ?? '')) });
      case 'test': return json({ sent: await alertTest(deps) });
      case 'pair': {
        const { endpoint, p256dh, auth, lang } = body;
        if (!vapid) return json({ error: 'push_not_configured' }, 503);
        if (typeof endpoint !== 'string' || !endpoint.startsWith('https://') || typeof p256dh !== 'string' || typeof auth !== 'string') return json({ error: 'bad_request' }, 400);
        await admin.from('post_alert_devices').upsert({ endpoint, p256dh, auth, lang: lang === 'nb' ? 'nb' : 'en' }, { onConflict: 'endpoint' });
        return json({ ok: true });
      }
      // Admin only: used by the schedule and by hand.
      case 'register': return admin_ok ? json(await alertRegister(deps, body as never)) : json({ error: 'unauthorized' }, 401);
      case 'renew': return admin_ok ? json({ results: await alertRenewAll(deps) }) : json({ error: 'unauthorized' }, 401);
      default: return json({ error: 'bad_request' }, 400);
    }
  } catch (e) {
    return json({ error: e instanceof Error ? e.message : 'failed' }, 400);
  }
});

