// GENERATED by supabase/build-functions.mjs from functions/post-alerts/{index,logic}.ts. Do not edit by hand.
// Paste this whole file into the Supabase dashboard editor for a function named "post-alerts".
// Supabase Edge Function (Deno): instant new-mail alerts for the Post mail app. Microsoft calls it when mail arrives; it decides whether the mail
// deserves an alert and sends a Web Push to the "Post alerts" home-screen web app. The Post app calls it (header x-alerts-key) to register, change or stop.
// Secrets: POST_ALERTS_KEY (any long random text), ALERTS_ENC_KEY (32 random bytes, base64url), MS_CLIENT_ID, VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_SUBJECT (optional).
// Deploy with "Verify JWT" OFF: Microsoft and the schedule cannot send a Supabase login. The webhook is protected by a secret clientState per mailbox, the rest by POST_ALERTS_KEY.
import { createClient } from 'npm:@supabase/supabase-js@2';

// ---- logic (notify-partner) ----
// Pure logic for the `notify-partner` edge function: Web Push (RFC 8030) with payload encryption (RFC 8291, aes128gcm)
// and VAPID (RFC 8292), written on WebCrypto so it runs in Deno, browsers and Node. Unit tested (tests/notify-partner.test.ts).

const enc = new TextEncoder();

export function b64uToBytes(s: string): Uint8Array {
  const b = s.replace(/-/g, '+').replace(/_/g, '/') + '='.repeat((4 - (s.length % 4)) % 4);
  return Uint8Array.from(atob(b), (c) => c.charCodeAt(0));
}
export function bytesToB64u(bytes: Uint8Array): string {
  let s = '';
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
const concat = (...parts: Uint8Array[]) => {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let o = 0;
  for (const p of parts) { out.set(p, o); o += p.length; }
  return out;
};

async function hkdf(salt: Uint8Array, ikm: Uint8Array, info: Uint8Array, bytes: number): Promise<Uint8Array> {
  const key = await crypto.subtle.importKey('raw', ikm, 'HKDF', false, ['deriveBits']);
  return new Uint8Array(await crypto.subtle.deriveBits({ name: 'HKDF', hash: 'SHA-256', salt, info }, key, bytes * 8));
}

export type EncryptOptions = { salt?: Uint8Array; senderKeys?: CryptoKeyPair };

/** Encrypts `payload` for a push subscription. Returns the request body (header + one record). */
export async function encryptPayload(payload: Uint8Array, uaPublic: Uint8Array, authSecret: Uint8Array, opts: EncryptOptions = {}): Promise<Uint8Array> {
  if (uaPublic.length !== 65 || uaPublic[0] !== 4) throw new Error('bad subscription key');
  if (payload.length > 3993) throw new Error('payload too large'); // one 4096-byte record: 4096 - 16 tag - 1 delimiter - 86 header
  const salt = opts.salt ?? crypto.getRandomValues(new Uint8Array(16));
  const sender = opts.senderKeys ?? (await crypto.subtle.generateKey({ name: 'ECDH', namedCurve: 'P-256' }, true, ['deriveBits']));
  const asPublic = new Uint8Array(await crypto.subtle.exportKey('raw', sender.publicKey));
  const uaKey = await crypto.subtle.importKey('raw', uaPublic, { name: 'ECDH', namedCurve: 'P-256' }, false, []);
  const ecdh = new Uint8Array(await crypto.subtle.deriveBits({ name: 'ECDH', public: uaKey }, sender.privateKey, 256));
  const keyInfo = concat(enc.encode('WebPush: info\0'), uaPublic, asPublic);
  const ikm = await hkdf(authSecret, ecdh, keyInfo, 32);
  const cek = await hkdf(salt, ikm, enc.encode('Content-Encoding: aes128gcm\0'), 16);
  const nonce = await hkdf(salt, ikm, enc.encode('Content-Encoding: nonce\0'), 12);
  const aes = await crypto.subtle.importKey('raw', cek, 'AES-GCM', false, ['encrypt']);
  const cipher = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv: nonce }, aes, concat(payload, new Uint8Array([2]))));
  const rs = new Uint8Array([0, 0, 0x10, 0]); // 4096, big endian
  return concat(salt, rs, new Uint8Array([asPublic.length]), asPublic, cipher);
}

/** VAPID `Authorization` header value for a push endpoint. `privateD` is the 32-byte private scalar, `publicKey` the 65-byte point. */
export async function vapidAuthorization(endpoint: string, subject: string, publicKey: Uint8Array, privateD: Uint8Array, now = Date.now()): Promise<string> {
  const key = await crypto.subtle.importKey(
    'jwk',
    { kty: 'EC', crv: 'P-256', x: bytesToB64u(publicKey.slice(1, 33)), y: bytesToB64u(publicKey.slice(33, 65)), d: bytesToB64u(privateD) },
    { name: 'ECDSA', namedCurve: 'P-256' }, false, ['sign'],
  );
  const part = (o: unknown) => bytesToB64u(enc.encode(JSON.stringify(o)));
  const signingInput = `${part({ typ: 'JWT', alg: 'ES256' })}.${part({ aud: new URL(endpoint).origin, exp: Math.floor(now / 1000) + 12 * 3600, sub: subject })}`;
  const sig = new Uint8Array(await crypto.subtle.sign({ name: 'ECDSA', hash: 'SHA-256' }, key, enc.encode(signingInput)));
  return `vapid t=${signingInput}.${bytesToB64u(sig)}, k=${bytesToB64u(publicKey)}`;
}

export type PushSub = { endpoint: string; p256dh: string; auth: string };

/** Builds and sends one push. Resolves with the push service's HTTP status. */
export async function sendPush(sub: PushSub, payload: unknown, vapid: { subject: string; publicKey: string; privateKey: string }, fetchImpl: typeof fetch = fetch): Promise<number> {
  const body = await encryptPayload(enc.encode(JSON.stringify(payload)), b64uToBytes(sub.p256dh), b64uToBytes(sub.auth));
  const res = await fetchImpl(sub.endpoint, {
    method: 'POST',
    headers: {
      Authorization: await vapidAuthorization(sub.endpoint, vapid.subject, b64uToBytes(vapid.publicKey), b64uToBytes(vapid.privateKey)),
      'Content-Encoding': 'aes128gcm', 'Content-Type': 'application/octet-stream', TTL: '86400', Urgency: 'normal',
    },
    body,
  });
  return res.status;
}

/** 404 and 410 mean the subscription is gone for good: forget it. */
export const isGone = (status: number) => status === 404 || status === 410;

const clip = (s: string, n: number) => (s.length > n ? `${s.slice(0, n - 1).trimEnd()}…` : s);
const firstLine = (s: string) => s.split('\n')[0].trim();

/** The notification a partner sees, in their language. */
export function buildMessage(lang: 'en' | 'nb', who: string, bodies: string[], forYou = false): { title: string; body: string; url: string } {
  const name = clip(who.trim() || (lang === 'nb' ? 'Partneren din' : 'Your partner'), 30);
  const texts = bodies.map(firstLine).filter(Boolean);
  const verb = lang === 'nb' ? (forYou ? 'ga deg' : 'la til') : forYou ? 'gave you' : 'added';
  let body: string;
  if (bodies.length === 1) body = texts[0] ? `${name} ${verb}: ${clip(texts[0], 120)}` : (lang === 'nb' ? `${name} la til et bilde` : `${name} added a photo`);
  else body = lang === 'nb' ? `${name} ${verb} ${bodies.length} oppgaver` : `${name} ${verb} ${bodies.length} to-dos`;
  return { title: 'Home Memory', body, url: '/' };
}

// ---- reminders at the due time (called every few minutes by a schedule, see docs/NOTIFICATIONS.md) ----

export type DueMemory = { id: string; household_id: string; body: string; due_on: string | null; due_time: string | null; assignee_id: string | null; remind_before?: number | null };

/** The date (YYYY-MM-DD) and minutes since midnight at `now` in a time zone, e.g. "Europe/Oslo". */
export function localNow(now: Date, tz: string): { date: string; minutes: number } {
  const parts = new Intl.DateTimeFormat('en-CA', { timeZone: tz, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(now);
  const get = (t: string) => parts.find((p) => p.type === t)?.value ?? '00';
  return { date: `${get('year')}-${get('month')}-${get('day')}`, minutes: Number(get('hour')) * 60 + Number(get('minute')) };
}

const wallMinutes = (date: string, hhmm: string) => Date.UTC(+date.slice(0, 4), +date.slice(5, 7) - 1, +date.slice(8, 10), +hhmm.slice(0, 2), +hhmm.slice(3, 5)) / 60_000;

/** To-dos whose time has come: the reminder moment (the due time minus "remind me before") has passed, but by less than `windowMin`, so a missed run still catches up. */
export function dueNow(list: DueMemory[], now: Date, tz: string, windowMin = 30): DueMemory[] {
  const { date, minutes } = localNow(now, tz);
  const nowMin = wallMinutes(date, '00:00') + minutes;
  return list.filter((m) => {
    if (!m.due_on || !m.due_time || !/^\d\d:\d\d/.test(m.due_time)) return false;
    const at = wallMinutes(m.due_on, m.due_time) - (m.remind_before ?? 0);
    return nowMin >= at && nowMin < at + windowMin;
  });
}

/** Who hears about a due to-do: the person it is for, or everyone in the household when it is for anyone. */
export const recipientsFor = (m: Pick<DueMemory, 'assignee_id'>, memberIds: string[]): string[] =>
  m.assignee_id && memberIds.includes(m.assignee_id) ? [m.assignee_id] : memberIds;

/** "30 min", "2 h", "1 day" in the reader's language. */
export function leadText(lang: 'en' | 'nb', minutes: number): string {
  if (minutes % 1440 === 0) { const d = minutes / 1440; return lang === 'nb' ? `${d} ${d === 1 ? 'dag' : 'dager'}` : `${d} ${d === 1 ? 'day' : 'days'}`; }
  if (minutes % 60 === 0) return lang === 'nb' ? `${minutes / 60} t` : `${minutes / 60} h`;
  return `${minutes} min`;
}

export function buildDueMessage(lang: 'en' | 'nb', bodies: string[], lead = 0): { title: string; body: string; url: string } {
  const texts = bodies.map(firstLine).filter(Boolean);
  const when = lead > 0 ? (lang === 'nb' ? `Om ${leadText(lang, lead)}` : `In ${leadText(lang, lead)}`) : lang === 'nb' ? 'N\u00e5' : 'Now';
  const body = bodies.length === 1 && texts[0]
    ? `${when}: ${clip(texts[0], 120)}`
    : lang === 'nb' ? `${bodies.length} oppgaver skal gj\u00f8res ${lead > 0 ? `om ${leadText(lang, lead)}` : 'n\u00e5'}` : `${bodies.length} to-dos are due ${lead > 0 ? `in ${leadText(lang, lead)}` : 'now'}`;
  return { title: 'Home Memory', body, url: '/' };
}

// ---- logic ----
// Pure logic for the `post-alerts` edge function: Microsoft Graph change notifications for new mail, the decision "does this deserve
// an alert", the alert text, token encryption, and the few Graph calls (with an injected fetch so they are unit tested).
// Tested in tests/post-alerts.test.ts. Names here start with "alert"/"graph" so this file can be bundled with notify-partner's logic.

export type AlertMode = 'people' | 'all' | 'vips' | 'off';
/** Alerts are allowed only inside this window. days: 1 = Monday ... 7 = Sunday. */
export type AlertQuiet = { days: number[]; from: string; to: string };
export type AlertAccount = {
  id: string; email: string; label: string; mode: AlertMode; vips: string[]; quiet: AlertQuiet | null; tz: string; inbox_folder_id?: string | null;
};
export type GraphMessage = {
  id: string; subject?: string; isRead?: boolean; parentFolderId?: string; inferenceClassification?: string;
  from?: { emailAddress?: { name?: string; address?: string } };
  internetMessageHeaders?: { name: string; value: string }[];
};

// ---- the webhook ----

/** Graph proves it owns the subscription by sending ?validationToken=...; we must echo it back as plain text within 10 seconds. */
export function alertValidationToken(url: string): string | null {
  const t = new URL(url).searchParams.get('validationToken');
  return t && t.length > 0 ? t : null;
}

export type AlertNotification = { subscriptionId: string; messageId: string; changeType: string };
export type AlertLifecycle = { subscriptionId: string; event: string };

const lastSegment = (s: string) => decodeURIComponent(s.split('/').filter(Boolean).pop() ?? '');

/** The new-mail notifications in a webhook body whose clientState matches the one we set. Anything else is ignored (it did not come from our subscription). */
export function alertParseNotifications(body: unknown, clientStates: Map<string, string>): AlertNotification[] {
  const list = (body as { value?: unknown[] } | null)?.value;
  if (!Array.isArray(list)) return [];
  const out: AlertNotification[] = [];
  for (const n of list as Record<string, any>[]) {
    const sub = String(n?.subscriptionId ?? '');
    const expected = clientStates.get(sub);
    if (!expected || n?.clientState !== expected || n?.lifecycleEvent) continue;
    const id = n?.resourceData?.id ?? (typeof n?.resource === 'string' ? lastSegment(n.resource) : '');
    if (!id) continue;
    out.push({ subscriptionId: sub, messageId: String(id), changeType: String(n?.changeType ?? '') });
  }
  return out;
}

export function alertParseLifecycle(body: unknown, clientStates: Map<string, string>): AlertLifecycle[] {
  const list = (body as { value?: unknown[] } | null)?.value;
  if (!Array.isArray(list)) return [];
  return (list as Record<string, any>[])
    .filter((n) => n?.lifecycleEvent && clientStates.get(String(n?.subscriptionId)) === n?.clientState)
    .map((n) => ({ subscriptionId: String(n.subscriptionId), event: String(n.lifecycleEvent) }));
}

// ---- does it deserve an alert? ----

const BULK_SENDER = /^(no[-_.]?reply|do[-_.]?not[-_.]?reply|donotreply|notifications?|newsletters?|mailer-daemon|postmaster|bounces?|marketing)$/i;

function alertHeaders(m: GraphMessage): Record<string, string> {
  const out: Record<string, string> = {};
  for (const h of m.internetMessageHeaders ?? []) if (h?.name && !(h.name.toLowerCase() in out)) out[h.name.toLowerCase()] = String(h.value ?? '');
  return out;
}

/** Bulk mail (newsletters, notifications, receipts-by-robot) versus a person writing to you.
 *  Outlook's own Focused/Other is deliberately NOT used to stay quiet: a missed alert is worse than an extra one, so when unsure we alert. */
export function alertKind(m: GraphMessage): 'person' | 'bulk' {
  const h = alertHeaders(m);
  if (h['list-unsubscribe'] || h['list-id']) return 'bulk';
  if (/^(bulk|list|junk)$/i.test((h['precedence'] ?? '').trim())) return 'bulk';
  const auto = (h['auto-submitted'] ?? '').trim().toLowerCase();
  if (auto && auto !== 'no') return 'bulk';
  const local = (m.from?.emailAddress?.address ?? '').split('@')[0];
  if (BULK_SENDER.test(local)) return 'bulk';
  return 'person';
}

const alertMinutes = (hhmm: string) => Number(hhmm.slice(0, 2)) * 60 + Number(hhmm.slice(3, 5));

/** Weekday (1 = Monday ... 7 = Sunday) and minutes since midnight at `now` in a time zone. */
export function alertLocal(now: Date, tz: string): { day: number; minutes: number } {
  const wd = new Intl.DateTimeFormat('en-US', { timeZone: tz, weekday: 'short' }).format(now);
  const day = ({ Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6, Sun: 7 } as Record<string, number>)[wd] ?? 1;
  return { day, minutes: localNow(now, tz).minutes };
}

export function alertWithinWindow(q: AlertQuiet | null, now: Date, tz: string): boolean {
  if (!q) return true;
  const { day, minutes } = alertLocal(now, tz);
  return q.days.includes(day) && minutes >= alertMinutes(q.from) && minutes < alertMinutes(q.to);
}

export function alertDecide(m: GraphMessage, a: AlertAccount, now: Date): { send: boolean; reason: string } {
  if (a.mode === 'off') return { send: false, reason: 'alerts are off for this account' };
  if (m.isRead) return { send: false, reason: 'already read' };
  if (a.inbox_folder_id && m.parentFolderId && m.parentFolderId !== a.inbox_folder_id) return { send: false, reason: 'not in the inbox' };
  const addr = (m.from?.emailAddress?.address ?? '').toLowerCase();
  const vip = addr !== '' && a.vips.some((v) => v.toLowerCase() === addr);
  if (vip) return { send: true, reason: 'VIP' }; // VIPs break through the schedule
  if (!alertWithinWindow(a.quiet, now, a.tz)) return { send: false, reason: 'outside this account’s alert hours' };
  if (a.mode === 'vips') return { send: false, reason: 'not a VIP' };
  if (a.mode === 'people' && alertKind(m) === 'bulk') return { send: false, reason: 'bulk mail' };
  return { send: true, reason: a.mode === 'all' ? 'all mail' : 'a person' };
}

const alertClip = (s: string, n: number) => (s.length > n ? `${s.slice(0, n - 1).trimEnd()}…` : s);

/** The notification text. Shows the account only when more than one is watched. */
export function alertBuild(m: GraphMessage, a: Pick<AlertAccount, 'id' | 'label'>, multi: boolean, lang: 'en' | 'nb' = 'en'): { title: string; body: string; url: string; tag: string } {
  const name = (m.from?.emailAddress?.name || m.from?.emailAddress?.address || '').trim() || (lang === 'nb' ? 'Ukjent avsender' : 'Unknown sender');
  const subject = (m.subject ?? '').replace(/\s+/g, ' ').trim() || (lang === 'nb' ? '(uten emne)' : '(no subject)');
  return {
    title: alertClip(multi && a.label ? `${name} · ${a.label}` : name, 60),
    body: alertClip(subject, 110),
    url: `/post/#/m/${encodeURIComponent(a.id)}/${encodeURIComponent(m.id)}`,
    tag: m.id,
  };
}

// ---- keeping the refresh token safe ----

/** AES-GCM with a 256-bit key given as base64url. Output "v1.<iv>.<ciphertext>". */
export async function alertEncrypt(plain: string, keyB64u: string): Promise<string> {
  const key = await crypto.subtle.importKey('raw', b64uToBytes(keyB64u), 'AES-GCM', false, ['encrypt']);
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ct = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, new TextEncoder().encode(plain)));
  return `v1.${bytesToB64u(iv)}.${bytesToB64u(ct)}`;
}

export async function alertDecrypt(stored: string, keyB64u: string): Promise<string> {
  const [v, iv, ct] = stored.split('.');
  if (v !== 'v1' || !iv || !ct) throw new Error('bad stored secret');
  const key = await crypto.subtle.importKey('raw', b64uToBytes(keyB64u), 'AES-GCM', false, ['decrypt']);
  return new TextDecoder().decode(await crypto.subtle.decrypt({ name: 'AES-GCM', iv: b64uToBytes(iv) }, key, b64uToBytes(ct)));
}

/** Constant-time string comparison for the shared secret. */
export function alertSameSecret(a: string | null, b: string): boolean {
  if (a === null || a.length !== b.length) return false;
  let x = 0;
  for (let i = 0; i < a.length; i++) x |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return x === 0;
}

// ---- Microsoft Graph ----

const GRAPH = 'https://graph.microsoft.com/v1.0';
// Read-only on purpose: the server can read headers of new mail to decide on an alert, and cannot send, change or delete anything.
export const ALERT_SCOPE = 'offline_access https://graph.microsoft.com/Mail.Read';

export class AlertGraphError extends Error {
  status: number;
  code: string;
  constructor(status: number, code: string, message: string) {
    super(message);
    this.name = 'AlertGraphError';
    this.status = status;
    this.code = code;
  }
}

async function graphJson(res: Response): Promise<any> {
  const text = await res.text();
  let body: any = null;
  try { body = text ? JSON.parse(text) : null; } catch { /* not JSON */ }
  if (!res.ok) throw new AlertGraphError(res.status, String(body?.error?.code ?? body?.error ?? 'error'), String(body?.error?.message ?? body?.error_description ?? text).slice(0, 200));
  return body;
}

/** Trades the stored refresh token for a short-lived access token (and a rotated refresh token, which must be stored). */
export async function alertRefresh(f: typeof fetch, p: { clientId: string; refreshToken: string; scope?: string }): Promise<{ accessToken: string; refreshToken: string; expiresIn: number }> {
  const res = await f('https://login.microsoftonline.com/common/oauth2/v2.0/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ client_id: p.clientId, grant_type: 'refresh_token', refresh_token: p.refreshToken, scope: p.scope ?? ALERT_SCOPE }).toString(),
  });
  const b = await graphJson(res);
  return { accessToken: String(b.access_token), refreshToken: String(b.refresh_token ?? p.refreshToken), expiresIn: Number(b.expires_in ?? 3600) };
}

/** What the Post web app may do with the mail: read and change it, and send. Only ever handed out as a short-lived access token. */
export const ALERT_APP_SCOPE = 'offline_access User.Read https://graph.microsoft.com/Mail.ReadWrite https://graph.microsoft.com/Mail.Send';

/** Trades the one-time code from the Microsoft sign-in page (PKCE, done in a normal browser tab) for tokens. Public client: no secret. */
export async function alertExchangeCode(f: typeof fetch, p: { clientId: string; code: string; verifier: string; redirectUri: string }): Promise<{ accessToken: string; refreshToken: string }> {
  const res = await f('https://login.microsoftonline.com/common/oauth2/v2.0/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ client_id: p.clientId, grant_type: 'authorization_code', code: p.code, code_verifier: p.verifier, redirect_uri: p.redirectUri, scope: ALERT_APP_SCOPE }).toString(),
  });
  const b = await graphJson(res);
  if (!b.refresh_token) throw new AlertGraphError(400, 'no_refresh_token', 'Microsoft did not give a refresh token');
  return { accessToken: String(b.access_token), refreshToken: String(b.refresh_token) };
}

const authHeaders = (token: string) => ({ Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' });

export async function alertGetMessage(f: typeof fetch, token: string, id: string): Promise<GraphMessage> {
  const sel = 'subject,from,isRead,parentFolderId,inferenceClassification,internetMessageHeaders';
  return await graphJson(await f(`${GRAPH}/me/messages/${encodeURIComponent(id)}?$select=${sel}`, { headers: authHeaders(token) }));
}

export async function alertGetInboxId(f: typeof fetch, token: string): Promise<string> {
  const b = await graphJson(await f(`${GRAPH}/me/mailFolders/inbox?$select=id`, { headers: authHeaders(token) }));
  return String(b.id);
}

/** Outlook message subscriptions last under 7 days (10 080 minutes). We ask for 4 days and renew daily. */
export const alertExpiry = (now: Date, minutes = 5760) => new Date(now.getTime() + minutes * 60_000).toISOString();

export async function alertCreateSubscription(
  f: typeof fetch, token: string, p: { notificationUrl: string; lifecycleUrl: string; clientState: string; expires: string },
): Promise<{ id: string; expires: string }> {
  const b = await graphJson(await f(`${GRAPH}/subscriptions`, {
    method: 'POST',
    headers: authHeaders(token),
    body: JSON.stringify({
      changeType: 'created', notificationUrl: p.notificationUrl, lifecycleNotificationUrl: p.lifecycleUrl,
      resource: "me/mailFolders('inbox')/messages", expirationDateTime: p.expires, clientState: p.clientState,
    }),
  }));
  return { id: String(b.id), expires: String(b.expirationDateTime ?? p.expires) };
}

export async function alertRenewSubscription(f: typeof fetch, token: string, id: string, expires: string): Promise<string> {
  const b = await graphJson(await f(`${GRAPH}/subscriptions/${encodeURIComponent(id)}`, {
    method: 'PATCH', headers: authHeaders(token), body: JSON.stringify({ expirationDateTime: expires }),
  }));
  return String(b?.expirationDateTime ?? expires);
}

/** Accounts whose subscription is missing or ends within `withinHours`: those get renewed (or created again). */
export function alertPlanRenewals<T extends { subscription_id: string | null; subscription_expires_at: string | null }>(accounts: T[], now: Date, withinHours = 30): T[] {
  const limit = now.getTime() + withinHours * 3_600_000;
  return accounts.filter((a) => !a.subscription_id || !a.subscription_expires_at || new Date(a.subscription_expires_at).getTime() < limit);
}

// ---- orchestration (the edge function only wires these to Supabase and Deno) ----

export type AlertStored = AlertAccount & {
  refresh_token_enc: string; client_state: string; subscription_id: string | null; subscription_expires_at: string | null;
};
export type AlertDevice = PushSub & { id: string; lang: string; badge?: number };
export type AlertStore = {
  accountBySubscription(subscriptionId: string): Promise<AlertStored | null>;
  allAccounts(): Promise<AlertStored[]>;
  /** true when this message had not been announced yet */
  markSeen(accountId: string, messageId: string): Promise<boolean>;
  update(accountId: string, patch: Record<string, unknown>): Promise<void>;
  upsertAccount(row: Record<string, unknown>): Promise<AlertStored>;
  deleteAccount(accountId: string): Promise<void>;
  devices(): Promise<AlertDevice[]>;
  removeDevices(ids: string[]): Promise<void>;
  /** The number shown on that phone's icon. */
  setBadge(deviceId: string, badge: number): Promise<void>;
  /** The phone opened Post: its number goes back to zero. true when the phone is known. */
  resetBadge(endpoint: string): Promise<boolean>;
};
export type AlertDeps = {
  store: AlertStore;
  fetch: typeof fetch;
  clientId: string;
  encKey: string;
  notificationUrl: string;
  send: (sub: PushSub, payload: unknown) => Promise<number>;
  now: () => Date;
};

/** A fresh access token for an account. If Microsoft rotated the refresh token, the new one is stored (encrypted). */
export async function alertAccessToken(d: AlertDeps, a: AlertStored): Promise<string> {
  const current = await alertDecrypt(a.refresh_token_enc, d.encKey);
  const t = await alertRefresh(d.fetch, { clientId: d.clientId, refreshToken: current });
  if (t.refreshToken !== current) await d.store.update(a.id, { refresh_token_enc: await alertEncrypt(t.refreshToken, d.encKey) });
  return t.accessToken;
}

// Every push shows a notification (iOS requires it) and carries the new icon number: alerts delivered to that phone since it last opened Post.
async function alertPushAll(d: AlertDeps, payload: (lang: 'en' | 'nb') => Record<string, unknown>): Promise<number> {
  const devices = await d.store.devices();
  const gone: string[] = [];
  let sent = 0;
  await Promise.all(devices.map(async (dev) => {
    try {
      const badge = (dev.badge ?? 0) + 1;
      const status = await d.send(dev, { ...payload(dev.lang === 'nb' ? 'nb' : 'en'), badge });
      if (status >= 200 && status < 300) { sent++; await d.store.setBadge(dev.id, badge); }
      else if (isGone(status)) gone.push(dev.id);
    } catch { /* one phone failing must not stop the others */ }
  }));
  if (gone.length) await d.store.removeDevices(gone);
  return sent;
}

/** New-mail notifications from Microsoft: look each message up, decide, alert. Returns what happened, for logs and tests. */
export async function alertProcess(d: AlertDeps, list: AlertNotification[]): Promise<{ id: string; outcome: string }[]> {
  const results: { id: string; outcome: string }[] = [];
  const tokens = new Map<string, string>();
  const all = list.length ? await d.store.allAccounts() : [];
  for (const n of list) {
    const a = await d.store.accountBySubscription(n.subscriptionId);
    if (!a) { results.push({ id: n.messageId, outcome: 'unknown subscription' }); continue; }
    if (!(await d.store.markSeen(a.id, n.messageId))) { results.push({ id: n.messageId, outcome: 'duplicate' }); continue; }
    try {
      let token = tokens.get(a.id);
      if (!token) { token = await alertAccessToken(d, a); tokens.set(a.id, token); }
      const m = await alertGetMessage(d.fetch, token, n.messageId);
      const verdict = alertDecide(m, a, d.now());
      if (!verdict.send) { results.push({ id: n.messageId, outcome: `skipped: ${verdict.reason}` }); continue; }
      const sent = await alertPushAll(d, (lang) => alertBuild(m, a, all.length > 1, lang));
      if (sent > 0) await d.store.update(a.id, { last_alert_at: d.now().toISOString() });
      results.push({ id: n.messageId, outcome: sent > 0 ? `alerted (${verdict.reason})` : 'no device to alert' });
    } catch (e) {
      results.push({ id: n.messageId, outcome: `error: ${e instanceof Error ? e.message : String(e)}` });
    }
  }
  return results;
}

export type AlertRegisterInput = { email: string; label?: string; refreshToken: string; mode?: AlertMode; vips?: string[]; quiet?: AlertQuiet | null; tz?: string };

const MODES: AlertMode[] = ['people', 'all', 'vips', 'off'];
export function alertCleanQuiet(q: unknown): AlertQuiet | null {
  if (!q || typeof q !== 'object') return null;
  const { days, from, to } = q as AlertQuiet;
  if (!Array.isArray(days) || !days.every((x) => Number.isInteger(x) && x >= 1 && x <= 7) || !/^\d\d:\d\d$/.test(from) || !/^\d\d:\d\d$/.test(to)) throw new Error('bad schedule');
  return { days: [...new Set(days)].sort(), from, to };
}

/** Starts watching a mailbox: stores the (encrypted) sign-in, finds the inbox, asks Microsoft to tell us about new mail. */
export async function alertRegister(d: AlertDeps, input: AlertRegisterInput): Promise<{ id: string; email: string; expires: string }> {
  const email = String(input.email ?? '').trim().toLowerCase();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new Error('bad email');
  if (!input.refreshToken || typeof input.refreshToken !== 'string') throw new Error('missing sign-in');
  const mode = input.mode ?? 'people';
  if (!MODES.includes(mode)) throw new Error('bad mode');
  const row = await d.store.upsertAccount({
    email, label: (input.label ?? '').slice(0, 30), refresh_token_enc: await alertEncrypt(input.refreshToken, d.encKey),
    client_state: bytesToB64u(crypto.getRandomValues(new Uint8Array(24))), mode, vips: (input.vips ?? []).map((v) => String(v).toLowerCase()).slice(0, 200),
    quiet: alertCleanQuiet(input.quiet), tz: input.tz && /^[A-Za-z_]+\/[A-Za-z_\-+0-9]+$/.test(input.tz) ? input.tz : 'Europe/Oslo',
  });
  try {
    const token = await alertAccessToken(d, row);
    const inbox = await alertGetInboxId(d.fetch, token);
    const sub = await alertCreateSubscription(d.fetch, token, {
      notificationUrl: d.notificationUrl, lifecycleUrl: `${d.notificationUrl}?lifecycle=1`, clientState: row.client_state, expires: alertExpiry(d.now()),
    });
    await d.store.update(row.id, { inbox_folder_id: inbox, subscription_id: sub.id, subscription_expires_at: sub.expires });
    return { id: row.id, email, expires: sub.expires };
  } catch (e) {
    await d.store.deleteAccount(row.id); // never keep a sign-in that did not work
    throw e;
  }
}

/** Keeps every subscription alive (run on a schedule). A sign-in Microsoft no longer accepts triggers one "sign in again" alert. */
export async function alertRenewAll(d: AlertDeps, accounts?: AlertStored[]): Promise<{ email: string; outcome: string }[]> {
  const list = alertPlanRenewals(accounts ?? await d.store.allAccounts(), d.now());
  const out: { email: string; outcome: string }[] = [];
  for (const a of list) {
    try {
      const token = await alertAccessToken(d, a);
      const expires = alertExpiry(d.now());
      try {
        if (!a.subscription_id) throw new AlertGraphError(404, 'none', 'no subscription');
        const exp = await alertRenewSubscription(d.fetch, token, a.subscription_id, expires);
        await d.store.update(a.id, { subscription_expires_at: exp });
        out.push({ email: a.email, outcome: 'renewed' });
      } catch (e) {
        if (!(e instanceof AlertGraphError) || (e.status !== 404 && e.status !== 410)) throw e;
        const sub = await alertCreateSubscription(d.fetch, token, { notificationUrl: d.notificationUrl, lifecycleUrl: `${d.notificationUrl}?lifecycle=1`, clientState: a.client_state, expires });
        await d.store.update(a.id, { subscription_id: sub.id, subscription_expires_at: sub.expires });
        out.push({ email: a.email, outcome: 'recreated' });
      }
    } catch (e) {
      const needsSignIn = e instanceof AlertGraphError && (e.code === 'invalid_grant' || e.status === 401 || e.status === 403);
      out.push({ email: a.email, outcome: needsSignIn ? 'needs sign-in' : `error: ${e instanceof Error ? e.message : String(e)}` });
      if (needsSignIn) {
        await alertPushAll(d, (lang) => ({
          title: lang === 'nb' ? 'Post-varsler trenger innlogging' : 'Post alerts need you to sign in',
          body: lang === 'nb' ? `Logg inn p\u00e5 ${a.label || a.email} igjen i Post for \u00e5 fortsette \u00e5 f\u00e5 varsler.` : `Sign in to ${a.label || a.email} again in Post to keep getting alerts.`,
          url: '/post/#/accounts', tag: `signin-${a.id}`,
        }));
      }
    }
  }
  return out;
}

/** Microsoft says a subscription needs attention: renew it right away (renewal re-authorises it). */
export async function alertLifecycle(d: AlertDeps, events: AlertLifecycle[]): Promise<string[]> {
  const out: string[] = [];
  for (const ev of events) {
    const a = await d.store.accountBySubscription(ev.subscriptionId);
    if (!a) continue;
    if (ev.event === 'reauthorizationRequired') out.push(...(await alertRenewAll(d, [{ ...a, subscription_expires_at: null }])).map((r) => r.outcome));
    else if (ev.event === 'subscriptionRemoved') out.push(...(await alertRenewAll(d, [{ ...a, subscription_id: null }])).map((r) => r.outcome));
  }
  return out;
}

export async function alertTest(d: AlertDeps): Promise<number> {
  return await alertPushAll(d, (lang) => ({
    title: lang === 'nb' ? 'Post-varsler fungerer' : 'Post alerts work',
    body: lang === 'nb' ? 'Slik ser et varsel ut n\u00e5r det kommer ny e-post.' : 'This is what an alert looks like when new mail arrives.',
    url: '/post/', tag: 'test',
  }));
}

/** Validated changes to an account's alert settings (only the keys that were sent). */
export function alertSettingsPatch(input: { label?: unknown; mode?: unknown; vips?: unknown; quiet?: unknown; tz?: unknown }): Record<string, unknown> {
  const patch: Record<string, unknown> = {};
  if ('label' in input) patch.label = String(input.label ?? '').slice(0, 30);
  if ('mode' in input) {
    if (!MODES.includes(input.mode as AlertMode)) throw new Error('bad mode');
    patch.mode = input.mode;
  }
  if ('vips' in input) {
    if (!Array.isArray(input.vips)) throw new Error('bad vips');
    patch.vips = input.vips.map((v) => String(v).toLowerCase()).slice(0, 200);
  }
  if ('quiet' in input) patch.quiet = alertCleanQuiet(input.quiet);
  if ('tz' in input) {
    if (typeof input.tz !== 'string' || !/^[A-Za-z_]+\/[A-Za-z_\-+0-9]+$/.test(input.tz)) throw new Error('bad time zone');
    patch.tz = input.tz;
  }
  return patch;
}

/** Stops alerts for a mailbox: tells Microsoft to stop (best effort) and forgets the sign-in. */
export async function alertUnregister(d: AlertDeps, email: string): Promise<boolean> {
  const a = (await d.store.allAccounts()).find((x) => x.email === email.trim().toLowerCase());
  if (!a) return false;
  if (a.subscription_id) {
    try {
      const token = await alertAccessToken(d, a);
      await d.fetch(`${GRAPH}/subscriptions/${encodeURIComponent(a.subscription_id)}`, { method: 'DELETE', headers: authHeaders(token) });
    } catch { /* the subscription expires by itself within days */ }
  }
  await d.store.deleteAccount(a.id);
  return true;
}

/** The phone opened Post: clear its icon number on the server so the next alert starts again from 1. */
export async function alertSeen(d: AlertDeps, endpoint: string): Promise<boolean> {
  return await d.store.resetBadge(endpoint);
}

/** The sign-in page finished: redeem the code, learn which mailbox it is, start watching it for alerts and keep the sign-in (encrypted). */
export async function alertConnect(d: AlertDeps, input: { code: string; verifier: string; redirectUri: string; label?: string }): Promise<{ id: string; email: string; expires: string }> {
  if (!input.code || !input.verifier || !/^https:\/\//.test(input.redirectUri ?? '')) throw new Error('bad request');
  const t = await alertExchangeCode(d.fetch, { clientId: d.clientId, code: input.code, verifier: input.verifier, redirectUri: input.redirectUri });
  const me = await graphJson(await d.fetch(`${GRAPH}/me?$select=mail,userPrincipalName`, { headers: authHeaders(t.accessToken) }));
  const email = String(me.mail ?? me.userPrincipalName ?? '').toLowerCase();
  const label = (input.label ?? '').trim() || (/@(outlook|hotmail|live|msn)\./i.test(email) ? 'Personal' : 'Work');
  return await alertRegister(d, { email, label, refreshToken: t.refreshToken });
}

/** A short-lived Graph access token (about an hour) for the web app to read and change mail directly. The long-lived sign-in never leaves the server. */
export async function alertMintToken(d: AlertDeps, email: string): Promise<{ accessToken: string; expiresIn: number; email: string }> {
  const a = (await d.store.allAccounts()).find((x) => x.email === email.trim().toLowerCase());
  if (!a) throw new Error('unknown account');
  const current = await alertDecrypt(a.refresh_token_enc, d.encKey);
  const t = await alertRefresh(d.fetch, { clientId: d.clientId, refreshToken: current, scope: ALERT_APP_SCOPE });
  if (t.refreshToken !== current) await d.store.update(a.id, { refresh_token_enc: await alertEncrypt(t.refreshToken, d.encKey) });
  return { accessToken: t.accessToken, expiresIn: t.expiresIn, email: a.email };
}

// ---- handler ----
const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'content-type, x-alerts-key',
};
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, 'Content-Type': 'application/json' } });

// Microsoft wants an answer within 3 seconds, so the real work continues after we have replied.
function later(p: Promise<unknown>) {
  const rt = (globalThis as { EdgeRuntime?: { waitUntil?: (p: Promise<unknown>) => void } }).EdgeRuntime;
  if (rt?.waitUntil) rt.waitUntil(p.catch((e) => console.error('post-alerts', e instanceof Error ? e.message : e)));
  else p.catch((e) => console.error('post-alerts', e instanceof Error ? e.message : e));
}

Deno.serve(async (req) => {
  // Microsoft proves it owns the subscription by sending ?validationToken=...: echo it back as plain text.
  const validation = alertValidationToken(req.url);
  if (validation) return new Response(validation, { status: 200, headers: { 'Content-Type': 'text/plain' } });
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors });

  const key = Deno.env.get('POST_ALERTS_KEY');
  const encKey = Deno.env.get('ALERTS_ENC_KEY');
  const clientId = Deno.env.get('MS_CLIENT_ID');
  const vapidPublic = Deno.env.get('VAPID_PUBLIC_KEY');
  const vapidPrivate = Deno.env.get('VAPID_PRIVATE_KEY');
  if (!key || !encKey || !clientId || !vapidPublic || !vapidPrivate) return json({ error: 'not_configured' }, 503);
  const vapid = { publicKey: vapidPublic, privateKey: vapidPrivate, subject: Deno.env.get('VAPID_SUBJECT') ?? 'mailto:admin@example.com' };

  const admin = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
  const accounts = () => admin.from('post_alert_accounts');
  const store: AlertStore = {
    accountBySubscription: async (id) => ((await accounts().select('*').eq('subscription_id', id).maybeSingle()).data as AlertStored | null) ?? null,
    allAccounts: async () => ((await accounts().select('*')).data ?? []) as AlertStored[],
    markSeen: async (accountId, messageId) => {
      const { data } = await admin.from('post_alert_seen').upsert({ account_id: accountId, message_id: messageId }, { onConflict: 'account_id,message_id', ignoreDuplicates: true }).select('message_id');
      return (data ?? []).length > 0;
    },
    update: async (id, patch) => { await accounts().update(patch).eq('id', id); },
    upsertAccount: async (row) => {
      const { data, error } = await accounts().upsert({ ...row, subscription_id: null, subscription_expires_at: null }, { onConflict: 'email' }).select('*').single();
      if (error) throw new Error(error.message);
      return data as AlertStored;
    },
    deleteAccount: async (id) => { await accounts().delete().eq('id', id); },
    devices: async () => ((await admin.from('post_alert_devices').select('id, endpoint, p256dh, auth, lang, badge')).data ?? []) as { id: string; endpoint: string; p256dh: string; auth: string; lang: string; badge: number }[],
    removeDevices: async (ids) => { await admin.from('post_alert_devices').delete().in('id', ids); },
    setBadge: async (id, badge) => { await admin.from('post_alert_devices').update({ badge }).eq('id', id); },
    resetBadge: async (endpoint) => ((await admin.from('post_alert_devices').update({ badge: 0 }).eq('endpoint', endpoint).select('id')).data ?? []).length > 0,
  };
  const deps: AlertDeps = {
    store, fetch, clientId, encKey, now: () => new Date(),
    notificationUrl: `${Deno.env.get('SUPABASE_URL')}/functions/v1/post-alerts`,
    send: (sub, payload) => sendPush(sub, payload, vapid),
  };

  // From Microsoft: no x-alerts-key header, a body of notifications, authenticated by each mailbox's secret clientState.
  if (req.method === 'POST' && !req.headers.get('x-alerts-key')) {
    const body = await req.json().catch(() => null);
    const states = new Map((await store.allAccounts()).filter((a) => a.subscription_id).map((a) => [a.subscription_id!, a.client_state]));
    if (new URL(req.url).searchParams.get('lifecycle')) later(alertLifecycle(deps, alertParseLifecycle(body, states)));
    else later(alertProcess(deps, alertParseNotifications(body, states)));
    return new Response(null, { status: 202 });
  }

  // From the Post app, the alerts page or the schedule.
  if (!alertSameSecret(req.headers.get('x-alerts-key'), key)) return json({ error: 'unauthorized' }, 401);
  let body: Record<string, any>;
  try { body = await req.json(); } catch { return json({ error: 'bad_request' }, 400); }

  try {
    switch (body.op) {
      case 'connect': return json(await alertConnect(deps, body as never));
      case 'token': return json(await alertMintToken(deps, String(body.email ?? '')));
      case 'register': return json(await alertRegister(deps, body as never));
      case 'update': {
        const email = String(body.email ?? '').trim().toLowerCase();
        const patch = alertSettingsPatch(body);
        const { data } = await accounts().update(patch).eq('email', email).select('id');
        return (data ?? []).length ? json({ ok: true }) : json({ error: 'not_found' }, 404);
      }
      case 'unregister': return json({ removed: await alertUnregister(deps, String(body.email ?? '')) });
      case 'status': {
        const list = await store.allAccounts();
        const devices = await store.devices();
        return json({
          devices: devices.length,
          accounts: list.map((a) => ({ email: a.email, label: a.label, mode: a.mode, quiet: a.quiet, vips: a.vips.length, subscription_expires_at: a.subscription_expires_at, last_alert_at: (a as { last_alert_at?: string }).last_alert_at ?? null })),
        });
      }
      case 'seen': return json({ ok: await alertSeen(deps, String(body.endpoint ?? '')) });
      case 'vapid': return json({ publicKey: vapid.publicKey });
      case 'renew': return json({ results: await alertRenewAll(deps) });
      case 'test': return json({ sent: await alertTest(deps) });
      case 'pair': {
        const { endpoint, p256dh, auth, lang } = body;
        if (typeof endpoint !== 'string' || !endpoint.startsWith('https://') || typeof p256dh !== 'string' || typeof auth !== 'string') return json({ error: 'bad_request' }, 400);
        await admin.from('post_alert_devices').upsert({ endpoint, p256dh, auth, lang: lang === 'nb' ? 'nb' : 'en' }, { onConflict: 'endpoint' });
        return json({ ok: true });
      }
      default: return json({ error: 'bad_request' }, 400);
    }
  } catch (e) {
    return json({ error: e instanceof Error ? e.message : 'failed' }, 400);
  }
});

