// The phone app shares its logic with the web app (dates, labels, place search, repeat rules, translations).
// The web app is the source; this copies the files into apps/mobile/src/shared (Metro cannot import outside the app).
// The only change: JSON imports lose their `with { type: 'json' }` attribute, which Node needs and Metro does not.
// Run:  node scripts/sync-shared.mjs     A web test fails when the copies are stale.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

export const SHARED = [
  'i18n/core.ts', 'i18n/en.json', 'i18n/nb.json', 'i18n/houseTasks.nb.json',
  'lib/when.ts', 'lib/labels.ts', 'lib/recurrence.ts', 'lib/placeSearch.ts', 'lib/geo.ts', 'lib/avatar.ts', 'lib/swipe.ts', 'lib/calendar.ts', 'lib/types.ts',
  'lib/quickAdd.ts', 'lib/checklist.ts', 'lib/todoGroups.ts', 'lib/tags.ts', 'lib/todoFilter.ts', 'lib/order.ts', 'lib/agenda.ts', 'lib/details.ts', 'lib/search.ts', 'lib/report.ts', 'lib/export.ts', 'lib/moving.ts', 'lib/route.ts', 'lib/routing.ts',
];
const root = new URL('../', import.meta.url);
export const source = (f) => new URL(`apps/web/src/${f}`, root);
export const target = (f) => new URL(`apps/mobile/src/shared/${f}`, root);

const HEADER = '// GENERATED by scripts/sync-shared.mjs from apps/web/src. Do not edit here: change the web file and run the script.\n';
export function render(f) {
  const text = readFileSync(source(f), 'utf8');
  if (f.endsWith('.json')) return text;
  return HEADER + text.replace(/ with \{ type: 'json' \}/g, '');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  for (const f of SHARED) {
    mkdirSync(dirname(target(f).pathname), { recursive: true });
    writeFileSync(target(f), render(f));
  }
  console.log(`copied ${SHARED.length} files to apps/mobile/src/shared`);
}
